### ISSUE TITLE
Southpark.cc player Issue

### ISSUE THREAD

**Issue by MALLER-LAGOON** [i-rinat/freshplayerplugin#101]
there is a issue with the player of this page: http://southpark.cc.com/full-episodes/s18e03-the-cissy
the thing is, when i play the chapter, is not a problem, i can reproduce it well. when i play it for a first time (understood by "first time", the first time that i play with a current version of freshplayer, recently compiled).
if the chapter is play in fullscreen, it will play well, the problem is after play the chapter completely, it is supposed to go out of the fullscreen mode, reload the page, and start playing the new chapter.
well, it doesn't happen, the fullscreen just turn in black, and i now the player is still playing, because its possible to hear the sounds in background.
Until here, is not a big problem, i can go out the fullscreen mode with the Esc Key, but when i try to go on the fullscreen mode again, the flash player crushes. it doesn't matters if i reboot firefox or the system, after the first full play of any chapter in those page, if i try to re-enter to a fullscreen mode, the flash plugin crashes.

The only way that i found to overcome this problem, is recompiling and reinstalling freshplayer. and i don't now why it works in this way :/

**Comment by i-rinat** [comment]
Aside from freezing randomly (deficiency in message loop code, there are race conditions possible), the issue should be fixed by f17f376b9d20688fd75b1db1b3a64b3eab202619. Wrapper now closes fullscreen window on plugin instance destroy.

**Comment by i-rinat** [comment]
Message loop if fixed now too; referenced movie doesn't hang when going to fullscreen on my machine anymore.
