### ISSUE TITLE
fresh floods system log

### ISSUE THREAD

**Issue by kubrickfr** [i-rinat/freshplayerplugin#102]
fresh plugin wrapper floods the system log with

Dec 09 17:59:12 xx gnome-session[2515]: [fresh  4023] [PPB] {fake} ppb_audio_input_enumerate_devices

messages, one every two or 3 seconds.

**Comment by i-rinat** [comment]
Fixed in 54fd8deb3ce63a27316642fa07976809c55f45ad.

If you want to decrease amount of data printed to stdout, add `quiet = 1` line to `~/.config/freshwrapper.conf`

**Comment by i-rinat** [comment]
(Actually those messages was left on purpose, as a reminders.)
