### ISSUE TITLE
crunchyroll crashing on switch to fullscreen

### ISSUE THREAD

**Issue by toddfraser88** [i-rinat/freshplayerplugin#103]
I'm not sure if anyone else is experiencing this problem, but I've noticed with the most recent version of this plugin that if I try to switch to fullscreen within the first 7 seconds of a stream on crunchyroll.com the plugin will crash. after 8 seconds it switches to fullscreen just fine.

just wondering if anyone else is having this problem?

**Comment by i-rinat** [comment]
By the way, does it still crash?

If current version works fine, can you also try version prior to ec8cdf4ee1b79e159420f47b28bd540408db5e9d to check whenever it was the fixing change?

**Comment by i-rinat** [comment]
bump
