### ISSUE TITLE
freshplayerplugin can not be disabled seperately

### ISSUE THREAD

**Issue by redhatlinux10** [i-rinat/freshplayerplugin#104]
os : openSUSE 13.2
firefox: 34.0.5 64bit
my firefox has  libflashplayer.so 11.2.202.425 installed by default. after libfreshwrapper-pepperflash.so 16.0.0.235 installed , i can see them both in about:plugins , and of course, i can play flash in firefox using pepper plugin flash
but if i disable Shockwave Flash 16.0 r0  in about:addons ,  Shockwave Flash 11.2 is also disabled. and vise versa. so i can not let Shockwave Flash 16.0 disabled and Shockwave Flash 11.2 enabled.

**Comment by beew** [comment]
Hi, I am wondering if it is possible to switch with update-alternatives for Debian based distros.

**Comment by i-rinat** [comment]
> if it is possible to switch with update-alternatives for Debian based distros.

Both freshwrapper and Flash plugin are NPAPI plugins with the same interface, so it should be possible to switch them using `update-alternatives`.
