### ISSUE TITLE
Weird Message 3

### ISSUE THREAD

**Issue by MALLER-LAGOON** [i-rinat/freshplayerplugin#109]
playing in a facebook game:

>[fresh] [error] _execute_script_ptac, NPN_Evaluate failed
>[WARNING:flash/platform/pepper/pep_url_request_info.cpp(219)] Missing colon in H".P header line "

the error message was a way too long than this, but is repeating the same message than before.

**Comment by i-rinat** [comment]
I've finally found why this is happening. At least one way to cause it is to have external server to send multiple `Set-Cookie` headers. Firefox merges them, but with `\n`, not with `,` as other headers. Header recreation code only creates one `Set-Cookie`, and other line spills out without a name.

I've filed an issue at: https://bugzilla.mozilla.org/show_bug.cgi?id=1120113

**Comment by MALLER-LAGOON** [comment]
excellent!!!!!

:+1:
