### ISSUE TITLE
freezes in this page.

### ISSUE THREAD

**Issue by wzhy90** [i-rinat/freshplayerplugin#111]
http://www.cnbeta.com/articles/358363.htm
It freezes after playing about 9 seconds.
It use tudou.com's video. 

Another cnbeta's page use the youku.com video which is working fine!

**Comment by i-rinat** [comment]
I've changed task handling in ec8cdf4ee1b79e159420f47b28bd540408db5e9d (and some previous commits), which fixed hangs on other sites for me. It's very likely freezes you experienced was due to the same issue.

Please try again with the newest version.

**Comment by wzhy90** [comment]
still freeze

**Comment by wzhy90** [comment]
It's fixed. But it seems my system's problem.
last week I have reinstall my system and found the freeze was gone.

**Comment by i-rinat** [comment]
OK, I'm closing this issue then. Feel free to reopen or to file another issue if problem occurs again.
