### ISSUE TITLE
fresh player spawning separate window

### ISSUE THREAD

**Issue by toddfraser88** [i-rinat/freshplayerplugin#114]
ever since the 100x100 px version fresh player has been spawning a separate window instead of getting full-screen resolution

seems to do it when i switch out of a firefox tab then switch back.

see screenshot
http://i.imgur.com/ZjcMBMF.jpg

**Comment by i-rinat** [comment]
> fresh player has been spawning a separate window instead of getting full-screen resolution

This is how it's actually done. I create window, set some properties for it. Then window manager detects those changes and makes the window full screen, i.e. maximizes it, and removes decorations. I set the window transient for browser window, just like open file dialogs do. So it _feels like_ browser window itself goes fullscreen.

But for some reason Compiz removes `_NET_WM_STATE_FULLSCREEN` property from a window occasionally. I still don't understand why it does so, and what actual reasons are.

**Comment by toddfraser88** [comment]
will there be a fix for this?

**Comment by i-rinat** [comment]
> will there be a fix for this?

Yes, as soon as I discover magic sequence of actions that Compiz will accept :-)
By the way, check recent version, I've changed sequence in 3a9747e42cb9009c036a6104e57ae9d7392530e1 and 4788328f4247e513d00d3cf7872f632ab3e5df7c.

**Comment by toddfraser88** [comment]
most recent version seems to be fixed.

thanks very much.
