### ISSUE TITLE
compile errors

### ISSUE THREAD

**Issue by MALLER-LAGOON** [i-rinat/freshplayerplugin#115]
>~/freshplayerplugin/freshplayerplugin-master/src/screensaver_control.c: In function ‘screensaver_type_detect’:
~/freshplayerplugin/freshplayerplugin-master/src/screensaver_control.c:222:19: warning: ‘flags’ may be used uninitialized in this function [-Wmaybe-uninitialized]
~/freshplayerplugin/freshplayerplugin-master/src/screensaver_control.c:182:14: note: ‘flags’ was declared here

**Comment by i-rinat** [comment]
Fixed by 0770e312d36a42bcab23ca4e99bd10f0436eeaeb
