### ISSUE TITLE
Compile error on debian jessie

### ISSUE THREAD

**Issue by letsjustfixit** [i-rinat/freshplayerplugin#116]
make 
[  1%] Built target parson-obj
Scanning dependencies of target freshwrapper-obj
[  2%] Building C object src/CMakeFiles/freshwrapper-obj.dir/async_network.c.o
In file included from /usr/local/src/freshpp/src/pp_resource.h:44:0,
                 from /usr/local/src/freshpp/src/async_network.c:37:
/usr/include/GLES2/gl2.h:69:25: error: conflicting types for ‘GLsizeiptr’
 typedef khronos_ssize_t GLsizeiptr;
                         ^
In file included from /usr/include/GL/gl.h:2055:0,
                 from /usr/include/GL/glx.h:32,
                 from /usr/local/src/freshpp/src/pp_resource.h:43,
                 from /usr/local/src/freshpp/src/async_network.c:37:
/usr/include/GL/glext.h:468:19: note: previous declaration of ‘GLsizeiptr’ was here
 typedef ptrdiff_t GLsizeiptr;
                   ^
In file included from /usr/local/src/freshpp/src/pp_resource.h:44:0,
                 from /usr/local/src/freshpp/src/async_network.c:37:
/usr/include/GLES2/gl2.h:70:26: error: conflicting types for ‘GLintptr’
 typedef khronos_intptr_t GLintptr;
                          ^
In file included from /usr/include/GL/gl.h:2055:0,
                 from /usr/include/GL/glx.h:32,
                 from /usr/local/src/freshpp/src/pp_resource.h:43,
                 from /usr/local/src/freshpp/src/async_network.c:37:
/usr/include/GL/glext.h:469:19: note: previous declaration of ‘GLintptr’ was here
 typedef ptrdiff_t GLintptr;
                   ^
src/CMakeFiles/freshwrapper-obj.dir/build.make:54: recipe for target 'src/CMakeFiles/freshwrapper-obj.dir/async_network.c.o' failed
make[2]: *** [src/CMakeFiles/freshwrapper-obj.dir/async_network.c.o] Error 1
CMakeFiles/Makefile2:166: recipe for target 'src/CMakeFiles/freshwrapper-obj.dir/all' failed
make[1]: *** [src/CMakeFiles/freshwrapper-obj.dir/all] Error 2
Makefile:76: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by i-rinat** [comment]
Fixed by 7574bb368bad480e13da9a6cf8fb6de2f35b6406.
