### ISSUE TITLE
np_functions.c hardcodes screen=0 instead of using DefaultScreen(dpy)

### ISSUE THREAD

**Issue by noahfriedman** [i-rinat/freshplayerplugin#118]
If you have more than one screen and they are not the same size, trying to run flash programs on screen :0.1 produces garbled output.

The patch is so trivial I figured I would just inline it rather than fork the entire repo.
<pre>
--- a/src/np_functions.c
+++ b/src/np_functions.c
@@ -640,7 +640,7 @@ handle_graphics_expose_event(NPP npp, void *event)
     struct pp_graphics3d_s *g3d = pp_resource_acquire(pp_i->graphics, PP_RESOURCE_GRAPHICS3D);
     Display *dpy = ev->display;
     Drawable drawable = ev->drawable;
-    int screen = 0;
+    int screen = DefaultScreen(dpy);
     cairo_surface_t *src_surf, *dst_surf;
     cairo_t *cr;
     int retval;
@@ -769,7 +769,7 @@ handle_placeholder_graphics_expose_event(NPP npp, void *event)
     XGraphicsExposeEvent   *ev = event;
     Display                *dpy = ev->display;
     Drawable                drawable = ev->drawable;
-    int                     screen = 0;
+    int                     screen = DefaultScreen(dpy);
     unsigned int            width, height, border_width, depth;
     Window                  root_wnd;
     int                     x, y;
</pre>

**Comment by i-rinat** [comment]
Fixed in 371ff952c7c8ec9872a08c8668455af3c97c0c27

**Comment by noahfriedman** [comment]
Thanks!  I missed the 3d calls.  I haven't even tried enabling that yet.
