### ISSUE TITLE
crunchyroll broken?

### ISSUE THREAD

**Issue by toddfraser88** [i-rinat/freshplayerplugin#120]
crunchyroll broken?

sorry to be a bother, 
but i only just now went to watch crunchyroll.com and noticed that the player doesn't show up, just a blank space where the player should be.

**Comment by ahjolinna** [comment]
I just checked I have the same problem, using the git version

**Comment by i-rinat** [comment]
Yeah, this is second time I fix Coverity warnings, and introduce errors by those changes :)

Fixed in c021f39b81ed4fd2aff2573bafdfdd49ec5530df.
