### ISSUE TITLE
Issue full screen

### ISSUE THREAD

**Issue by i-mirror** [i-rinat/freshplayerplugin#121]
Some versions, when using the full screen with some player you get this result:
![sat-13-20](https://cloud.githubusercontent.com/assets/7964751/5729536/4afd8164-9b73-11e4-9995-e4f070b8e7ff.png)

**Comment by dyskette** [comment]
I'm running version 0.2.2 on Fedora 21 with Firefox 35/Epiphany 3.14 and I have the same issue with Dramafever's player.

![captura de pantalla de 2015-01-16 10 55 14](https://cloud.githubusercontent.com/assets/6687927/5780352/87ab264a-9d6f-11e4-9eb0-1662c8a32272.png)

With youtube is not so bad... but it doesn't fill the screen. Having black borders on top, left and right.

![captura de pantalla de 2015-01-16 10 52 25](https://cloud.githubusercontent.com/assets/6687927/5780372/b5d41cde-9d6f-11e4-8b8a-7962ba0317a9.png)

**Comment by i-rinat** [comment]
Please try again with version 154a3eaa1d1b8f9f56af7a2404bbbfd1aac466aa.
Now smallest width and height across all monitors are reported as fullscreen width and height correspondingly. Multi-monitor setups with affected Flash movies can still result in a partial screen fill, but this is inevitable, I think.

If you use one of the monitors for full screen videos exclusively, you can specify its resolution as `fullscreen_width` and `fullscreen_height` parameters in `~/.config/freshwrapper.conf`.

**Comment by i-mirror** [comment]
Now it works.

**Comment by dyskette** [comment]
Not there yet for me. I still have issues with fullscreen. See http://youtu.be/-X7hJANQqzQ

The working area is smaller than my screen, so my clics are not in sync with the image. That horizontal black bar above or below the video. And sometimes it doesn't want to fill the screen, just showing a really small player (it's just the image, because clicks are still working within the player).

All of that is shown in the video above.

Laptop screen with Radeon HD 7520G
- Fedora 21 x86_64
- Firefox 35
- Xorg 1.16.2.901
- Mesa 10.4
- Kernel 3.17.8-300

**Comment by trinaldi** [comment]
I'm still having trouble with embbed videos in vBulletin forums. 

Right clicking the area where the video should be, I get a "Movie not loaded" context menu.
3d and 3d transparent all set to 0.

Screenshot: http://i.imgur.com/iacY0IN.png

The dotted border does not appear.

**Comment by i-rinat** [comment]
@trinaldi, can you share a link to a page where issue you're talking about can be reproduced? "Movie not loaded" means flash player can not load swf file at all, so changing 3d settings won't help here. Issue is about something else.

**Comment by trinaldi** [comment]
Sure.

http://www.hardmob.com.br/showthread.php?t=359310

This is a Brazilian forum, this thread is an off topic type. You should see
some pics and videos, nothing NSFW.

If you need anything else, I'll be around.

**Comment by i-rinat** [comment]
@trinaldi, I tried some last pages from that forum thread, there were some videos from Youtube, and they work. So I can't reproduce it.
Maybe you use some addons? Can you try start Firefox in [safe mode](https://support.mozilla.org/en-US/kb/troubleshoot-firefox-issues-using-safe-mode) and check again? (It's better to backup your Firefox profile folder before, just in case).

**Comment by trinaldi** [comment]
Weird.

Is there anyway I can debug this?

Thanks!

**Comment by trinaldi** [comment]
I was thinking about it.

I have a hybrid graphics laptop and I'm using the Intel one. Is it possible
that this might be caused by some hardware decoding?

Funny thing is, the only way I can get HW decoding (VDPAU) with mplayer is
switching to iGPU. The AMD one does not work properly.

My setup is:
Ubuntu 14.04.1
FF 35.0.1 (HW acceleration disabled)
fglrx 13.5

Using mplayer with VDPAU causes no tearing and less than 10% of CPU power.

**Comment by i-rinat** [comment]
> I have a hybrid graphics laptop and I'm using the Intel one. Is it possible that this might be caused by some hardware decoding?

Nope, that should not interfere anyhow.

> Is there anyway I can debug this?

You can try to run freshwrapper with tracing enabled. Configure with `cmake -DTRACE_ALL=1 ..` and build again with `make` to enable tracing. You then need to run browser from terminal emulator, and redirect its output to a file. Go to the failing site, load page, try to reproduce the issue, then close the browser. In the generated trace file look for NPP_New call. There will be "src" parameter nearby, which is where swf file should loaded from. Then look for NPP_NewStream calls. Browser creates one stream for swf file, but freshwrapper ignores it and request a new stream on its own.

Previously you told that you see "movie not loaded". That means there is something wrong with that movie download sequence. (Note that by "move" Flash player means ".swf" file).

**Comment by trinaldi** [comment]
Ok.
I've build it with "-DCMAKE_BUILD_TYPE=RelWithDebInfo -DTRACE_ALL=1" and copied the .so file to /usr/lib/mozilla/plugins.

The browser recognizes the plugin (http://i.imgur.com/ahUGwhh.png) and the 'original' flash (http://i.imgur.com/ahUGwhh.png).

So I ran firefox via console and went directly to that same thread.
I piped the output to a text file, this is the result:
http://pastebin.com/fxpSW3d9

**Comment by i-rinat** [comment]
Here, that line:
`[fresh 17407] [NPP] {full} NPP_URLNotify npp=0x7fa518078068, url=http://www.youtube.com/v/1IG5-3Q_NCc, reason=1, notifyData=22`
`reason=1` means stream was terminated by because of "problems with network, disk I/O, lack of memory, or other problems."

That could be HTTPS/HTTP related. Some security enforcing plugins could disallow loading content over HTTP on a HTTPS page. "HTTPS Everywhere", for example. Or even browser itself. But that only makes sense if main page is over HTTPS.

**Comment by trinaldi** [comment]
Indeed!

I edited my last post. HTTPS Everywhere is the issue!

**Comment by cyberalex4life** [comment]
In my case this freshwrapper.conf did the job
# Configuration options for FreshPlayerPlugin

# This configuration file is optional. Wrapper will search for it first
# in ~/.config/freshwrapper.conf, then in /etc/freshwrapper.conf.
# If wrapper fails to find configuration, it will use default values,
# which you can find below

# Audio buffer is used to continuously provide sound adapter with data.
# Values too low may lead to buffer underruns and stuttering.  Values
# too high will lead to noticeable latency. Usually plugin selects size
# on its own, but you may override bounds here

# lower bound for audio buffer size, in milliseconds
audio_buffer_min_ms = 20

# higher bound of audio buffer size, in milliseconds
audio_buffer_max_ms = 500

# Path to the Pepper Flash plugin
pepperflash_path = "/usr/lib/pepperflashplugin-nonfree/libpepflashplayer.so"

# "Command-line" arguments for Flash
#flash_command_line = "enable_hw_video_decode=0,enable_stagevideo_auto=1"

# enable 3d and stage 3d
enable_3d = 1

# enable 3d for wmode=transparent instances
enable_3d_transparent = 0

# when set to 1, limits output to warnings and errors only
quiet = 0

# When multiple monitors with different resolutions are used, size
# of fullscreen window can vary. But some Flash movies request these
# parameters once at startup and rely on them to be correct. By default,
# if zeros are used here, freshwrapper will select minimal width and
# height across all monitors.
fullscreen_width = 0
fullscreen_height = 0

# Enables DNS query case randomization to partially protect against DNS
# poisoning attacks. It was reported that some Mikrotik routers do not
# support this trick. Set parameter to 0 if you have an affected model
randomize_dns_case = 1

**Comment by cyberalex4life** [comment]
Actually 
enable_3d = 1
seems to do the job.
Maybe you should also try do delete pluginreg.dat from ~/.mozilla/firefox/[your_code].default
My issue was only with youtube on Ubuntu Gnome Trusty amd64

**Comment by i-rinat** [comment]
@dyskette, could you check whenever fullscreen now fills entire screen?
There were changes 7d0895aa07a1bfdb14717db9dcceaa9d49f20ebf and 2cda8ccc29b1ae5bdcf28e18df3ba528e1678322 which are related to fullscreen window size under Gnome 3. Under that DE, windows without`_NET_WM_STATE_MAXIMIZED_HORZ` and `_NET_WM_STATE_MAXIMIZED_VERT`  flags can be a bit smaller for unknown reason.

**Comment by cyberalex4life** [comment]
I noticed this too especially on youtube

**Comment by i-rinat** [comment]
@cyberalex4life, is it still filling only part of a screen? Have you tried version from `master` branch?

**Comment by cyberalex4life** [comment]
I managed to compile master branch on OpenSUSE 13.2 and tested on a few videos on three different websites and things seem ok.

**Comment by dyskette** [comment]
Sorry for the delay.

I compiled it on Fedora 22 (GNOME Shell 3.16) and is working good (on youtube, dramafever and crunchyroll), the issue is gone.

**Comment by i-rinat** [comment]
@cyberalex4life, @dyskette , good to hear. Thanks for testing.

**Comment by trinaldi** [comment]
I should mention that my problems are also gone.

It turns out that another extension was the issue with the embedded videos.

Keep the great work!

**Comment by i-rinat** [comment]
OK great.

**Comment by trinaldi** [comment]
@i-rinat Thanks for all your support!
