### ISSUE TITLE
using DRM play.google.com videos menu will not show up

### ISSUE THREAD

**Issue by ChrisFernandez** [i-rinat/freshplayerplugin#125]
I got freshplayer working very well so far with the chromeos plugin on firefox under Kubuntu 14.10, but it will not show up the google play menus to forward,make full screen, play/pause etc. If I move the cursor over it will change the cursor type and actually click the full screen etc.. so is working but not showing..

**Comment by toddfraser88** [comment]
I tried out one of the free videos to test it.

The player and video seems to load properly, but playback does not work - stats for nerds has "null video decoding" for some reason.

**Comment by i-rinat** [comment]
Are there any free videos to test? I didn't find any. Maybe that's a regional restriction.
Can you post a link to any of that videos?

**Comment by toddfraser88** [comment]
there's "free TV episodes" below "new release highlights"

but maybe it's different in your region?

this one is free for me 
https://play.google.com/store/tv/show?id=CP0cRhozbnk&cdid=tvseason-zknj5guhmWa2N3A_O6HmFQ&gdid=tvepisode-FpA2aDPSC0E&hl=en

**Comment by i-rinat** [comment]
> but maybe it's different in your region?

`Sorry! TV on Google Play is not available in your country yet.`

**Comment by toddfraser88** [comment]
ah, shame.

I just tried this site in chromium, and i got the same result, so it might be pepperflash itself the problem here.

**Comment by ChrisFernandez** [comment]
Hello I have to add that yesterday night I did a git pull and recompiled and now in firefox does show the menus... not sure what have changed. but will be worth to note that.

**Comment by toddfraser88** [comment]
how did you get it to work? it doesn't play for me.

**Comment by ChrisFernandez** [comment]
I'm using the chromeOS plugin, have google chromiun installed(but using this with firefox) but I have read that you do need google Chromium, also there is a setting in the config for freshplayerplugin that you need to switch  from 0 to 1 that the file name is ~/.config/freshwrapper.conf
and change the entrie:
# enable 3d and stage 3d
enable_3d = 0  (here to 1)

hope this helps.
in regards to my original question above, I always had DRM working I just was not able to see the menus below in google play.. for some reason last night I did a code pull from git(here) and re-compiled, put it in place ~/.mozilla/plugins/  next to the chromeOS plugin and works like a charm.. I wish the quality will be better since I have a 32" monitor but so far so good, I hope it gets better.

**Comment by toddfraser88** [comment]
where can i find the chromeOS plugin?

**Comment by i-rinat** [comment]
> where can i find the chromeOS plugin?

You need to download ChromeOS recovery image and extract PepperFlash from it. Here is a [brief instruction](https://github.com/i-rinat/freshplayerplugin/issues/13#issuecomment-60490990).

**Comment by i-rinat** [comment]
Oh, it looks like issue was solved by itself ([link](https://github.com/i-rinat/freshplayerplugin/issues/125#issuecomment-71234163)), but I missed the comment.

I'm closing current issue. Feel free to open new one, if problem re-occurs.
