### ISSUE TITLE
Won't load after firefox update.

### ISSUE THREAD

**Issue by Benguin** [i-rinat/freshplayerplugin#126]
After updating to FF35, freshplayer won't work anymore. When trying to load youtube videos it gives "Failed to load 'libpepflashplayer.so'", and it won't work on other sites either. I tried recompiling from the latest release but that didn't fix it.

Any ideas? For some reason Firefox won't open in a terminal properly (forks and gives the prompt back, rather than giving me terminal output..

**Comment by Benguin** [comment]
Agh, sorry. I removed google chrome yesterday after forgetting why I needed it installed. I'm silly.

**Comment by ecjbosu** [comment]
I have had this problem on Fedora 25 workstation.  
failed to load libpepflashplayer.so.  freshwraopper is a translation layer which needs PPAPI plugin backend

This program notes up to as dozen locations searched, but the library files is not found.   Even thought the library is physically in on of the locations, and many of the other, not google directories, have symbolic links.  This search and load algorithm is not working.

HACK: is to edit /etc/freshwrapper.conf and add the last line.  This physical location is the default installation location for libpepflashplayer on Fedora spins.

# Path to the Pepper Flash plugin.
# If the option is absent, freshwrapper will search for Pepper Flash in
# a number of locations where it could be. Usually that's enough, but if
# not, you should manually enter the right path. Multiple paths could
# be specified, separated by colon.
#pepperflash_path = "/opt/google/chrome/PepperFlash/libpepflashplayer.so"
pepperflash_path = "/usr/lib64/flash-plugin/libpepflashplayer.so"

I hope this helps.
