### ISSUE TITLE
full screen and button not working 

### ISSUE THREAD

**Issue by beew** [i-rinat/freshplayerplugin#127]
Hi,
I compiled and installed freshplayerplugin form git Jan 20 2015 on  Fedora 21 64 bit. There are a few problems.

On youtube cannot exit from fullscreen by clicking the minimize button (has to press Esc) On some sites e.g http://www.cp24.com/ fullsscreen doesn't work, i.e when fullscreen is activated video remains the same size tugged to the upper right corner inside a big black window which should have been the video.

Thanks.

**Comment by i-rinat** [comment]
Hi. Couple of weeks ago there were fixes related to fullscreen under Gnome 3, which is used in Fedora by default. I strongly believe the issue should be solved now. Could you check again whenever it works now?
