### ISSUE TITLE
DRM content support

### ISSUE THREAD

**Issue by i-rinat** [i-rinat/freshplayerplugin#13]
It was reported by @blackwolf12333 in https://github.com/i-rinat/freshplayerplugin/issues/6#issuecomment-44205807 that copyrighted content doesn't work, while it works in Chrome.

**Comment by neuhaus** [comment]
You can mount images like that with kpartx as explained at https://tinyapps.org/docs/mount_partitions_from_disk_images.html

**Comment by beew** [comment]
I extracted flash from the same chromebook image but only got blackscreen (for any flash video, not just drmed ones)

**Comment by i-rinat** [comment]
@beew, one must enable 3d by adding `enable_3d = 1` line to `~/.config/freshwrapper.conf` to make ChromeOS' PepperFlash render video.

OpenGL|ES (that 3d) is disabled by default, as it causes rendering issues on some machines and/or Mesa versions. Regular PepperFlash seems to work well with 2d only, but one from ChromeOS doesn't.

(related issue: #122)

**Comment by sunbriel** [comment]
I just need to copy libpepflahsplayer.so from the image to /opt/google/chrome/PepperFlash? If I do that, browser just says that I don't have libpepflahplayer.so. Can somebody explain it to a noob?

**Comment by i-rinat** [comment]
> I just need to copy libpepflashplayer.so from the image to /opt/google/chrome/PepperFlash?

Yes, that should be enough. You can also put it anywhere you like and specify path as `pepperflash_path` parameter in `~/.config/freshwrapper.conf` file. Also make sure you are using right architecture. 32-bit plugin on 64-bit OS or 64-bit plugin on 32-bit OS won't work. (ARM versions also won't work on x86 machines.)

**Comment by sunbriel** [comment]
I downloaded chromeos_6457.107.0_zako_recovery_stable-channel_mp-v2.bin , placed the libpepflashplayer.so in /opt/google/chrome/PepperFlash, edited freshwrapper.conf to specify the right path, but when I open the browser (Chrome in this case) I get following error:

[67:67:0305/230932:ERROR:ppapi_thread.cc(280)] Failed to load Pepper module from /opt/google/chrome/PepperFlash/libpepflashplayer.so (error: /opt/google/chrome/PepperFlash/libpepflashplayer.so: cannot open shared object file: Operation not permitted)

**Comment by i-rinat** [comment]
> cannot open shared object file: Operation not permitted

Check if file actually readable. Make `chmod 755 libpepflashplayer.so` if required.

> but when I open the browser (Chrome in this case) I get following error

You don't need freshplayerplugin if you use Chrome. Moreover, you can't use the former, since it's a NPAPI plugin, and Chrome have no NPAPI support anymore.
If you are trying to make Flash DRM work in Chrome, it most probably won't work either.

**Comment by sunbriel** [comment]
Yes, I did that.

I understand that, but I couldn't see any specific errors when starting Firefox. This is what I get in Mozilla: http://i.imgur.com/cyCXv4k.png

**Comment by i-rinat** [comment]
> This is what I get in Mozilla

As you can see from the screenshot, freshwrapper tries to load file `/usr/lib/pepperflashplugin-nonfree/libpepflashplayer.so`, however you said before that you've put plugin to `/opt/google/chrome/PepperFlash`.

It could be you have two `freshwrapper.conf` files, both in `/etc` and in `~/.config`, but changed only `/etc/freshwrapper.conf`, while `~/.config/freshwrapper.conf` (which is preferred if exists) still have old version. Try to check both locations.

**Comment by sunbriel** [comment]
Currently it's there, but wherever I put it and change it in freshwrapper.conf, the outcome is the same. It always says it can't find it. There is only one freshwrapper.conf and it's located in ~/.config.

**Comment by i-rinat** [comment]
I think I get it. One need to use double quotes when specifying path:
`pepperflash_path = "/opt/google/chrome/PepperFlash/libpepflashplayer.so"`

Also if you remove `pepperflash_path` option completely, freshwrapper will try multiple paths, including Chrome stable, beta and unstable installations. So you really need to specify path only if it's non-common. Here is the list of default locations: [[link](https://github.com/i-rinat/freshplayerplugin/blob/1defbf0d0e28172a7de80d47e790b757a2b00098/src/config_pepperflash.c#L28)].

**Comment by sunbriel** [comment]
Double quotes are present. Also, when I comment out the path line (tried that a lot of times already), I still get the same error. It's as if something's wrong with the flash from Chrome OS. I wish I could try with a different one, but I don't know where to get it.

**Comment by i-rinat** [comment]
I tried it in Mint 17.1 and here is the reason: `libpepflashplayer.so` from ChromeOS requires `libstdc++.so.6` from gcc 4.9, while Mint 17.1 have only 4.8.
It was sufficient for me to install these packages:
* http://mirrors.kernel.org/ubuntu/pool/main/g/gcc-4.9/gcc-4.9-base_4.9.1-16ubuntu6_i386.deb
* http://mirrors.kernel.org/ubuntu/pool/main/g/gcc-4.9/gcc-4.9-base_4.9.1-16ubuntu6_amd64.deb
* http://mirrors.kernel.org/ubuntu/pool/main/g/gcc-4.9/libstdc++6_4.9.1-16ubuntu6_i386.deb
* http://mirrors.kernel.org/ubuntu/pool/main/g/gcc-4.9/libstdc++6_4.9.1-16ubuntu6_amd64.deb

**Comment by sunbriel** [comment]
Thank you for the help! I installed g++ 4.9 and now it's working.

**Comment by ChrisFernandez** [comment]
Hello I have same issue on arch linux.. was working before for a long time and after not using it for 3 weeks and not touching any configuration i get a blak video with sound only.

**Comment by i-rinat** [comment]
@ChrisFernandez, is `libpepflashplayer.so` from desktop Chrome working? Which version of freshwrapper do you use? Do you have `enable_3d=1` set in `~/.config/freshwrapper.conf`?

**Comment by ChrisFernandez** [comment]
yes it was working... i have not updated that piece.. the freshwrapper I do git pulls and recompile to update.. I did that today to see if this will fix it and still the same.. the freshwrapper config does have the enable_3d=1 I have double check, also what puzzles me is that it was working before..

**Comment by i-rinat** [comment]
@ChrisFernandez, two weeks ago, in 28fe9e7cfb61012f7e5419141ded5781a9ef3272 there were a transition to XRender. Try a snapshot before that change ([link](https://github.com/i-rinat/freshplayerplugin/tree/543fce72038b6064514450e7a70e96993d8be626))

**Comment by ChrisFernandez** [comment]
thanks.. one question. I follow the link and the github link to clone is the same as main page..how do i get a snapshot of that particular version? thanks

**Comment by i-rinat** [comment]
There is a button named [Download ZIP](https://github.com/i-rinat/freshplayerplugin/archive/543fce72038b6064514450e7a70e96993d8be626.zip).

Also, if you have local copy of git repository, you can select that snapshot by calling `git checkout 543fce72`. To move to master branch again, call `git checkout master`.

**Comment by ChrisFernandez** [comment]
Hello. sorry did not had time to look into this because of work until now.
i did the git pull on an existing repository that i have and still I get sound but no image.. is just black..

**Comment by i-rinat** [comment]
PepperFlash from ChromeOS doesn't show anything unless 3d is enabled and supported. Current versions of freshwrapper have enable_3d=1 by default, but version I gave you link to before (pre-XRender) have enable_3d=0 by default. So you need to ensure you have `~/.config/freshwrapper.conf` and it has line `enable_3d = 1`.

Also check if there any warnings or errors in stderr/stdout. Easiest way is to launch browser from terminal emulator and look at text output.

**Comment by JamesTheAwesomeDude** [comment]
I'm wondering if there's any way (which is not extremely illegal) to include the ChromeOS version of PepperFlash with freshplayerplugin? Or have an easy way (such as a shell script) to quickly download and extract the ChromeOS-PepperFlash and configure the freshplayerplugin to use it?

Just a thought.

**Comment by i-rinat** [comment]
> (which is not extremely illegal)

I don't think redistribution is allowed explicitly, so it's gray zone. It's unlikely to get DMCA notice, but if I get one, whole repo will be shut down. I therefore will avoid putting files here.

> Or have an easy way

That's questionable too. Once easy tool becomes available, download traffic will increase significantly. Remember, recovery images have sizes about 1-2 GB. Looks like distributing a DDoS tool. :-/

**Comment by JamesTheAwesomeDude** [comment]
@i-rinat Those packages you recommended: they will break local package configuration unless you also install `libgcc1_4.9.1-16ubuntu6_{i386,amd64}.deb`!

**Comment by i-rinat** [comment]
Probably yes, I don't remember. I think I only searched for packages with libraries that was strongly required by ChromeOS's PepperFlash build, but didn't check further package dependencies.
