### ISSUE TITLE
freshplayerplugin together with uBlock breaks youtube videos.

### ISSUE THREAD

**Issue by Ziemas** [i-rinat/freshplayerplugin#135]
Using freshplayerplugin and uBlock (https://github.com/gorhill/uBlock) together results in youtube videos with ads never loading. This was reported to the uBlock authors but they have been unable to understand where the problem is. It would be nice if you could take a look at it from your side.

For more information:
https://github.com/gorhill/uBlock/issues/578
https://github.com/gorhill/uBlock/issues/653

**Comment by i-rinat** [comment]
Fixed in 47332559e0668b5ad1d8027410855b13a19057ff

**Comment by Ziemas** [comment]
Yes, that works. Thank you.

**Comment by i-rinat** [comment]
Hello again. The fix for this issue have caused another one. I just wanted you to check whenever it still works for you after 9dd43f228eb5341e2906f63a1c89b1823c30e929.

**Comment by Ziemas** [comment]
Yes, this is still working.
