### ISSUE TITLE
Lag on Darkorbit.com

### ISSUE THREAD

**Issue by ThePierrezou** [i-rinat/freshplayerplugin#136]
Website : http://www.darkorbit.com/
Firefox version : 35.0.1
Flash version : 16.0.0.350
freshplayerplugin-0.2.2-3.fc21.x86_64
Fedora 21 64 bits 
I don't have lag on Chrome.
I have make a file ~/.config/freshwrapper.conf and i have write enable_3d = 1
But i have lags anyway :(
Thanks
ThePierrezou

**Comment by i-rinat** [comment]
OK, I've finally managed to register there. And I can't reproduce issue your are talking about.

Does it lag in a starter location? Have you tried latest version of freshwrapper from git?

**Comment by ThePierrezou** [comment]
I'm on archlinux now.
I use this : https://aur.archlinux.org/packages/freshplayerplugin/
<a href="http://imgur.com/QbbjrZe.gif"><img src="http://i.imgur.com/QbbjrZe.gif" title="source: imgur.com" /></a>

**Comment by i-rinat** [comment]
Try recent version from master branch. I've removed texture readback operation in favor of XRender's composition. That can help a bit with graphics performance.

**Comment by ThePierrezou** [comment]
I'm testing with the git version and i have same lags.

**Comment by i-rinat** [comment]
I tried to reproduce it, but it still works fine. On the other hand, there were changes in graphics subsystem, windowed mode was added. That should exclude browser from rendering pipeline, as drawing is now performed directly into plugin's own X window.

Are lags are still there? If yes, how much CPU is consumed by `plugin-container` process? How much CPU is consumed by `firefox`? You can use `top` command in terminal emulator.

**Comment by ThePierrezou** [comment]
I don't know why but now it work fine :D
Thank you very much and good luck for the future :)

**Comment by i-rinat** [comment]
Hope it will keep working fine. :-)
