### ISSUE TITLE
Can't start a video on Youtube

### ISSUE THREAD

**Issue by ThePierrezou** [i-rinat/freshplayerplugin#137]
When i start a video i see this :
<a href='http://pix.toile-libre.org/upload/original/1423331150.png'><img src='http://pix.toile-libre.org/upload/thumb/1423331150.png' /></a>
Firefox : 35.0.1
Flash : 16.0.0.305
freshplayerplugin-0.2.2-3.fc21.x86_64

**Comment by i-rinat** [comment]
Do you have any ad-blocking addons installed? If you do, try to turn them off temporarily.

**Comment by ThePierrezou** [comment]
Ohh you're right i have disabled µblock and now it work.
I don't understand but anyway i work now, bu ti think it would be good if peeper flash work with a adblocker on Firefox.

**Comment by i-rinat** [comment]
There was an issue about error handling #135, also about uBlock. It's already fixed in `master` branch. So if you build a recent version from source, it should work with uBlock enabled.

**Comment by ThePierrezou** [comment]
Thanks :)
