### ISSUE TITLE
Twitch.tv streams broken.

### ISSUE THREAD

**Issue by Ziemas** [i-rinat/freshplayerplugin#138]
As of https://github.com/i-rinat/freshplayerplugin/commit/47332559e0668b5ad1d8027410855b13a19057ff streams on twitch.tv no longer work.

**Comment by i-rinat** [comment]
Fixed in 9dd43f228eb5341e2906f63a1c89b1823c30e929

**Comment by Ziemas** [comment]
Twitch now works and https://github.com/i-rinat/freshplayerplugin/issues/135 remains fixed. Thank you.
