### ISSUE TITLE
Cannot  input any Chinese or other Asia languages through flash on Firefox.

### ISSUE THREAD

**Issue by LzyAWP-Fred** [i-rinat/freshplayerplugin#140]
I cannot  input any Chinese or other Asia languages through flash on Firefox. When I try to input Chinese by fcitx or ibus, there is no reponse at all. When I try to copy it from other side and paste it, the words become wired thing. For exmaple, 人 -> \u4eba.
Thanks, this plugin makes my firefox reborn. Donating is possible!

http://www.acfun.tv/v/ac1691461
You need play the video before inputing. Only english is acceptable due to the plugin... hope to fix

**Comment by i-rinat** [comment]
Input method support is one of the parts I'm currently working on. (Also there is related issue #15)

**Comment by i-rinat** [comment]
As for pasting (from clipboard) non-Latin characters, it should be fixed by 543fce72038b6064514450e7a70e96993d8be626

**Comment by LzyAWP-Fred** [comment]
Thank you for your replying. Good job tho!

**Comment by i-rinat** [comment]
Hi. I've just added IME support in c940797b33f39a5ab03bad8acc24c530eb42fe09. Could you check whenever it works on your machine?

**Comment by i-rinat** [comment]
Oops. While ibus works, fcitx still doesn't.

**Comment by i-rinat** [comment]
Depends on #72.

I discovered that Firefox calls `gtk_im_context_focus_in()` for all widgets on the page, including plugins. As fcitx installs key snooper, no key events are reaching plugin from that point, therefore it's impossible to use for windowless plugins. Windowed ones are getting events directly from X server, so they are not affected.

**Comment by i-rinat** [comment]
Windowed mode support was enabled again by default in bd52c83c3814c69cf04040bd109770aa96cfeaa2. With some previous fixes that should make IME work. I've tested both IBus and Fcitx with Anthy.
