### ISSUE TITLE
Missing drm.h 

### ISSUE THREAD

**Issue by Bevito** [i-rinat/freshplayerplugin#141]
Hi i-rinat,

I'm using Debian 64 bit (sometimes Wheezy, sometimes Jessie)
I try to build latest git version. It seems that I forgot a package because i failed to compile freshplayerplugin.

The file 'drm.h' seems to be in 'linux-headers-3.2.0-4-amd64' package, wich is install on my system.

Maybe you can help me ?

Thanks a lot.

$  cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ..

-- The C compiler identification is GNU 4.7.2
-- The CXX compiler identification is GNU 4.7.2
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.26") 
-- checking for modules 'alsa;glib-2.0;gio-2.0;x11;xrandr;xrender;gl;glesv2;libconfig;libevent;libevent_pthreads;cairo;pango;pangocairo;pangoft2;freetype2;gtk+-2.0;openssl'
--   found alsa, version 1.0.25
--   found glib-2.0, version 2.32.4
--   found gio-2.0, version 2.32.4
--   found x11, version 1.5.0
--   found xrandr, version 1.3.2
--   found xrender, version 0.9.7
--   found gl, version 8.0.5
--   found glesv2, version 8.0.5
--   found libconfig, version 1.4.8
--   found libevent, version 2.0.19-stable
--   found libevent_pthreads, version 2.0.19-stable
--   found cairo, version 1.12.2
--   found pango, version 1.30.0
--   found pangocairo, version 1.30.0
--   found pangoft2, version 1.30.0
--   found freetype2, version 14.1.8
--   found gtk+-2.0, version 2.24.10
--   found openssl, version 1.0.1e
-- checking for module 'libpulse'
--   package 'libpulse' not found
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/git/freshplayerplugin/build

$ make

[  1%] Building C object 3rdparty/CMakeFiles/parson-obj.dir/parson/parson.c.o
[  1%] Built target parson-obj
[  2%] Generating uri_parser_fsm.c
[  2%] Built target generate_fsm
[  4%] Building C object src/uri_parser/CMakeFiles/uri-parser-obj.dir/uri_parser.c.o
[  4%] Built target uri-parser-obj
[  5%] Building C object src/CMakeFiles/freshwrapper-obj.dir/async_network.c.o
[  7%] Building C object src/CMakeFiles/freshwrapper-obj.dir/audio_thread.c.o
[  8%] Building C object src/CMakeFiles/freshwrapper-obj.dir/audio_thread_alsa.c.o
[ 10%] Building C object src/CMakeFiles/freshwrapper-obj.dir/config.c.o
[ 11%] Building C object src/CMakeFiles/freshwrapper-obj.dir/compat.c.o
[ 12%] Building C object src/CMakeFiles/freshwrapper-obj.dir/header_parser.c.o
[ 14%] Building C object src/CMakeFiles/freshwrapper-obj.dir/keycodeconvert.c.o
[ 15%] Building C object src/CMakeFiles/freshwrapper-obj.dir/np_entry.c.o
[ 17%] Building C object src/CMakeFiles/freshwrapper-obj.dir/np_functions.c.o
[ 18%] Building C object src/CMakeFiles/freshwrapper-obj.dir/main_thread.c.o
[ 20%] Building C object src/CMakeFiles/freshwrapper-obj.dir/reverse_constant.c.o
[ 21%] Building C object src/CMakeFiles/freshwrapper-obj.dir/tables.c.o
In file included from /home/user/git/freshplayerplugin/src/tables.c:39:0:
/usr/include/xf86drm.h:40:17: fatal error: drm.h: Aucun fichier ou dossier de ce type
compilation terminated.
make[2]: *** [src/CMakeFiles/freshwrapper-obj.dir/tables.c.o] Erreur 1
make[1]: *** [src/CMakeFiles/freshwrapper-obj.dir/all] Erreur 2
make: *** [all] Erreur 2

**Comment by i-rinat** [comment]
Hi. That was include directive left from vsync experiments, I forgot to remove it.
Fixed in c9bd358a6000120b4db80864e014ae919636a838

**Comment by Bevito** [comment]
Thanks a lot ! 
Now it works.
