### ISSUE TITLE
Hi-DPI support

### ISSUE THREAD

**Issue by xdqi** [i-rinat/freshplayerplugin#142]
Hello,
I am using Ubuntu on a MacBook Pro retina machine using Firefox 35.0.1 with FreshPlayer plugin.
Here is a screen capture of FreshPlayer compared with Chrome (`google-chrome --force-device-scale-factor=2`) showing that FreshPlayer does not have a good HiDPI support.
![2015-02-27 03 13 27](https://cloud.githubusercontent.com/assets/3365420/6400041/5c65679c-be31-11e4-8da8-04de19434a9a.png)

**Comment by i-rinat** [comment]
Try version from [custom-scale](https://github.com/i-rinat/freshplayerplugin/tree/custom-scale) branch. How does it work? (There is hardcoded scale value of `2.0` in it.)

**Comment by xdqi** [comment]
It does not work, scale seems to be 1.0, the same as before.
Is there any debug message could I provide to you?

**Comment by i-rinat** [comment]
> Is there any debug message could I provide to you?

No, thanks. I think, I've reproduced it on my machine. I just need to figure out how to tell PepperFlash about scale. Apparently changing value to 2.0 in one place is not enough.

**Comment by i-rinat** [comment]
Ok, next attempt. :-)

I've updated code in [custom-scale](https://github.com/i-rinat/freshplayerplugin/tree/custom-scale) branch. But now you'll also need to add `device_scale = 2` line to `~/.config/freshwrapper.conf` file.

**Comment by xdqi** [comment]
Well, now only mouse position redirect works, but it does not work on actual graphics :(
(Sorry for my terrible English)
![1](https://cloud.githubusercontent.com/assets/3365420/6422898/079bfb84-bf19-11e4-8da0-04b6dd7262f6.png)

**Comment by i-rinat** [comment]
Quite strange. What value of `layout.css.devPixelsPerPx` do you have in Firefox? You can find value of that setting on about:config page. (And your English is fine.)

**Comment by xdqi** [comment]
Oh, I am sorry that I did not mention that for best view, I change that value to `2`, or everything will show with only 100% DPI.

**Comment by i-rinat** [comment]
There are another bit of changes about scaling in `custom-scale` branch, now about graphics2d. I've realized I forgot to fix ppb_graphics2d part. Now it should work.

Also, if it works on your machine, please try to add `enable_3d = 1` to `~/.config/freshwrapper.conf` and check again if that works too.

**Comment by xdqi** [comment]
Using the latest `custom-scale` branch, it works!
It works even I added `enable_3d = 1` option, add this option does improved graphics performance.

Thank you for your works.

**Comment by i-rinat** [comment]
OK, then I push fixes as 20082ef09cde9598e59e1bb6c1abb62dc944d7b5.
