### ISSUE TITLE
how to add multiple paths to pepperflash_path="" ? 

### ISSUE THREAD

**Issue by fastrizwaan** [i-rinat/freshplayerplugin#143]
chromium pepper flashplugin 16  can be installed without installing google chrome (40MB) vs pepperflash (5.1MB); saves around 35MB and an unneeded browser.

for example from here:
ftp://ftp.pbone.net/mirror/ftp.sourceforge.net/pub/sourceforge/p/po/postinstaller/fedora/releases/21/x86_64/updates/chromium-pepper-flash-16.0.0.257-1.fc21.x86_64.rpm

is it possible to add multiple paths to like this? I tried but it was not working:

     pepperflash_path=‘/opt/google/chrome/PepperFlash/libpepflashplayer.so:/usr/lib64/chromium/PepperFlash/libpepflashplayer.so'

chromium-pepper-flash-16.0.0.257-1.fc21.x86_64

    rpm -ql chromium-pepper-flash-16.0.0.257-1.fc21.x86_64/usr/lib64/chromium
    /usr/lib64/chromium/PepperFlash
    /usr/lib64/chromium/PepperFlash/libpepflashplayer.so
    /usr/lib64/chromium/PepperFlash/manifest.json
    /usr/share/licenses/chromium-pepper-flash/eula_text.html

I can get it working by either copying to /opt/chrome/... or set the chromium/PepperFlash/... in conf file.
But It would be great if we could have multiple paths, when chrome is not installed, chromium-pepperflash could be useful.

multiple paths
is it possible?

Thanks.

**Comment by i-rinat** [comment]
> is it possible?

Why not. Implemented in 3b8f3f4116545155a023f10640df4b63ae6ac5db.

By the way, if you don't create `pepperflash_path` option at all, freshwrapper will search for `libpepflashplayer.so` in a bunch of paths ([link](https://github.com/i-rinat/freshplayerplugin/blob/3b8f3f4116545155a023f10640df4b63ae6ac5db/src/config_pepperflash.c#L28)). Perhaps it's worth to add your path there too, to make it "just work".
