### ISSUE TITLE
There is the dotted line around the flash player on some web pages.

### ISSUE THREAD

**Issue by LzyAWP-Fred** [i-rinat/freshplayerplugin#144]
There is the dotted line around the flash player on some web pages when you click on the Flash. I think it is kind of annoying. Common browser with general flash plugin doesn't show the dotted line. 
![2015-03-02 00 46 36](https://cloud.githubusercontent.com/assets/3715588/6435982/1641af54-c076-11e4-8d8f-6c6978db8c5e.png)

**Comment by i-rinat** [comment]
Firefox shows dotted line outline around windowless plugins. Currently freshwrapper uses windowless mode for all `wmode` parameter values, while NPAPI Flash switches to windowed mode if `wmode` is `direct` and `window`. Once windowed mode gets implemented, dots won't appear.

(related to #72)

**Comment by i-rinat** [comment]
As a workaround, you can disable focus ring completely in Firefox by setting `browser.display.focus_ring_on_anything` to `true` and `browser.display.focus_ring_width` to `0` on `about:config` page.

**Comment by i-rinat** [comment]
With enabling windowed mode and XEmbed support by default in bd52c83c3814c69cf04040bd109770aa96cfeaa2 the behavior is now the same as for NPAPI plugin.

Firefox still shows dotted line if plugin is `transparent` or `opaque`, but that's how it's designed to behave.
