### ISSUE TITLE
Freshplayerplugin crashes on iqiyi.com

### ISSUE THREAD

**Issue by nopyhe** [i-rinat/freshplayerplugin#145]
1. Open a video  on  http://www.iqiyi.com
2. Close the tab before the video end.

And then the plugin crashed.

I tested other video sites ,like youku.com, and this phenomenon didn't appear.

I installed freshplayer(from git) today.
flash  version : 16.0.0.305

I'm using Arch Linux 64-bit.

Finally,sorry for my poor English.

**Comment by i-rinat** [comment]
Fixed in 7b0c829d9f0a055424ef07eccc65fb395ba4cb82.

Not actually fixed, udp sockets are essential for Flash, but currently there is no implementation in freshwrapper. But at least player on iqiyi.com doesn't hang anymore.
Created #147 to track ppb_udp_socket implementation status.
