### ISSUE TITLE
Input method doesn't work in flashplayer

### ISSUE THREAD

**Issue by nopcall** [i-rinat/freshplayerplugin#15]
I can only type English in a flashplayer, 
my input method (Fcitx) doesn't work, but it works well in Chrome.

**Comment by i-rinat** [comment]
Hi. I've just added IME support in c940797b33f39a5ab03bad8acc24c530eb42fe09. Could you check whenever it works on your machine?

**Comment by i-rinat** [comment]
Oops. While ibus works, fcitx still doesn't.

**Comment by i-rinat** [comment]
Windowed mode support was enabled again by default in bd52c83c3814c69cf04040bd109770aa96cfeaa2. With some previous fixes that should make IME work. I've tested ibus and fcitx with Anthy.
