### ISSUE TITLE
since last merge commit some errors appears

### ISSUE THREAD

**Issue by MALLER-LAGOON** [i-rinat/freshplayerplugin#151]
mostly on facebook, since the commit 4f06966, the scrolling on the windowing mode are disabled, when in the plays of facebook try to send some invitations, the flash app get frozen. and sometimes on youtube, the flash window shows those error that gave u when u try to enable_3D=1 time ago like issue #80.

so, i get back to the commit ae3816c, and everything was back to the normal.

and finally, the console doesn't shows any error related.

**Comment by i-rinat** [comment]
> so, i get back to the commit ae3816c, and everything was back to the normal.

That's very strange, because there was no rendering related changes between ae3816cb56ecaeb06011c50cea98e3d7269024c6 and 4f06966f26271f57f9c491dc58d023e496fac6b0.

Although in 12add65e77ee5c00a948126ab35de978b1d37a4d I changed `enable_3d` default value to 1 again. Previous issues was caused by reading pixmap back to texture. That technique is no longer used, XRender is used instead.

**Comment by MALLER-LAGOON** [comment]
yes, i know.
but the errors occurs indeed. i did notice when u activate the 3d render, but the error was like that, i'm not really sure if the error was a rendering error indeed.

:(

**Comment by i-rinat** [comment]
I think I get you wrong. Can you explain again what kind of error you have, please? Did it go away when you rewind state back to ae3816c? Does it return when you go to the current `master` state again?

**Comment by MALLER-LAGOON** [comment]
now updated to 1f838d5ace and everything works fine again.
maybe was another problem.

but, when i updated, didn't recognize my libpulse libraries.

**Comment by i-rinat** [comment]
> didn't recognize my libpulse libraries.

Try to remove all files from `build` directory, then run cmake and make again. Recent commits was related cmake, sometimes cache from previous versions interacts with newer configuration scripts.

**Comment by MALLER-LAGOON** [comment]
In the #154 i propose a fix to that.

in my case, since i have the freshplayer-installer script working, every compilation is a totally new compilation.
so, it always start from a clean build directory.
