### ISSUE TITLE
Fails to load movie with HTTPS Everywhere

### ISSUE THREAD

**Issue by i-rinat** [i-rinat/freshplayerplugin#153]
HTTPS Everywhere is a addon for Firefox which redirects connections to HTTPS, and blocks non-secure HTTP connections.

It can cause freshwrapper to fail on http pages with `//example.com` content. With HTTPS-e activated request to `//example.com` will be expanded to `https://example.com`, but freshwrapper expands it to `http://example.com`, which is blocked by HTTPS-e. Disabling internal expansion and passing `//example.com` to the browser have no effect, as browser still uses `http://` for the URL.

**Comment by i-rinat** [comment]
See for example http://kinokong.net/24488-chernoe-more-2014-bd3.html. Select tab with trailer.

**Comment by gaining** [comment]
I had the https everywhere add-on for a while, it works for me and never crashes when it's activated

**Comment by i-rinat** [comment]
Fixed in abe3d525c9bd858e8eb7aeb05fa5b53261ebcc46.
