### ISSUE TITLE
Crash while run ad

### ISSUE THREAD

**Issue by dacrhu** [i-rinat/freshplayerplugin#155]
Hi,

int this page:
http://www.szeretlekmagyarorszag.hu/az-5-legfurabb-m1-es-idojaras-jelentes/

crash FF 36.0 while the ad play in top of page. In Chrome working fine.
Flash version: 17.0.0.134

Thank you for your time!
David

**Comment by dacrhu** [comment]
FF Report:

Accessibility: Active
Add-ons: hypertranslate%40mdc.com:4.0.0,hupper%40ajnasz.hu:1.5,toggleproxy%40quirkyquipu.co.uk:1.8,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:36.0,feca4b87-3be4-43da-a1b1-137c24220968%40jetpack:0.4.3,langpack-hu%40firefox.mozilla.org:36.0
BuildID: 20150220131007
CrashTime: 1426789289
EMCheckCompatibility: true
FramePoisonBase: 7ffffffff0dea000
FramePoisonSize: 4096
InstallTime: 1425139418
IsGarbageCollecting: 1
Notes: OpenGL: NVIDIA Corporation -- GeForce 8400 GS/PCIe/SSE2 -- 3.3.0 NVIDIA 340.76 -- texture_from_pixmap

ProductID: {ec8030f7-c20a-464f-9b0e-13a3a9e97384}
ProductName: Firefox
ReleaseChannel: default
SecondsSinceLastCrash: 423
StartupTime: 1426789206
Theme: classic/1.0
Throttleable: 1
URL: http://www.szeretlekmagyarorszag.hu/az-5-legfurabb-m1-es-idojaras-jelentes/
Vendor: Mozilla
Version: 36.0
useragent_locale: chrome://global/locale/intl.properties

This report also contains technical information about the state of the application when it crashed.





Console out:
[berci@berci ~]$ firefox 
NOT SANDBOXED
WARNING: content window passed to PrivateBrowsingUtils.isWindowPrivate. Use isContentWindowPrivate instead (but only for frame scripts).
pbu_isWindowPrivate@resource://gre/modules/PrivateBrowsingUtils.jsm:25:14
nsBrowserAccess.prototype.openURI@chrome://browser/content/browser.js:13923:25
libva info: VA-API version 0.36.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib64/dri/nvidia_drv_video.so
libva info: Found init function __vaDriverInit_0_36
libva info: va_openDriver() returns 0

**Comment by i-rinat** [comment]
Hi. Does it still crash? I don't see the ad on the page (but it was there some day).

**Comment by dacrhu** [comment]
Hm.... Now working fine. Sorry :S

**Comment by i-rinat** [comment]
There were a number of changes fixing crashes. Perhaps one of those have fixed this particular one too.

If you are interested, you can ensure issue is fixed by bisecting changes to determine which patch did the work. Git doesn't like when one searches for a fixing patch, so "good" and "bad" should be interchanged. The procedure is tedious and can be omitted of course. :-)

**Comment by dacrhu** [comment]
I use stable release, v0.2.3.
Between Firefox upgraded to major version.

**Comment by i-rinat** [comment]
Ok, I'm closing this issue. Feel free create new issue (or reopen this one) if it starts to crash again.
