### ISSUE TITLE
Please, add JACK audio support

### ISSUE THREAD

**Issue by v-fox** [i-rinat/freshplayerplugin#157]
[JACK](http://jackaudio.org) is an audio system done properly. Personally, i'm using it globally on my system and the [livecd](https://github.com/v-fox/live_opensuse_hsf). For flash support i'm using a [compatibility plugin](https://github.com/pvint/libflashsupport-jack2) which NPAPI flash loads at runtime. This doesn't work with PPAPI+freshplayerplugin combination, unfortunately. So, please, add JACK audio output support for freshplayerplugin.

**Comment by i-rinat** [comment]
Added in d8f46953b2ea1c4838d8451c8598d04d881b709e. You need to add `audio_use_jack = 1` line to `~/.config/freshwrapper.conf` file to make freshwrapper output sound via JACK.

`libsoxr-dev` needs to be installed, as soxr is used for resampling.

**Comment by v-fox** [comment]
Daaamn, that was fast, thanks !
There are some kinks though, even while just watching Youtube in flash i get XRuns and micro-stuttering (very rarely, actually) of sound like this:
```
 ERROR: JackEngine::XRun: client = freshwrapper was not finished, state = Running
```
Not fatal but when that happens i pretty sure some frames get dropped. But if framedropping causing sound stuttering (more likely, i think) or sound stuttering causing framedrops (possible buffering issue. does it automatically account for JACK server's expected latency & buffering settings ?) i don't know. Firefox's cubeb library which is used for sound mixing in HTML5 A/V has almost identical issues while NPAPI flash + previously mentioned compatibility plugin works pretty much perfectly (with no issues detected by JACK server).

I will make my next public distro release with this JACK-enabled freshplayerplugin.

**Comment by i-rinat** [comment]
I didn't add any latency update code. It's a very simple implementation, where jack process callback asks Flash for the data, then resamples it, and fills buffers. If all those operation combined take too long, underrun occur. I'll try to experiment with separate filler thread approach (the one used in libflashsupport-jack2).

As for cubeb, try to decrease delay [here](https://github.com/kinetiknz/cubeb/blob/6de5d3e488d808dd925ae0885a7552fc0a25b449/src/cubeb_jack.cpp#L406).

**Comment by i-rinat** [comment]
I've added a separate thread for resampling in 31dc60e567d4c07d54a58c242bac02fc2cd1efa5. Could you check whenever it works better or worse?

From experiments I found that even if I just call `memset` in process callback and nothing more, underruns are happening anyway. Time measurement showed that they are not related to the time spent in process callback in a usual case, when it processes actual sound data. I must mention that I don't have realtime scheduling set up. Perhaps that is what really does matter.

**Comment by v-fox** [comment]
> As for cubeb, try to decrease delay here.

Damn ! I'll do it ASAP.

> I've added a separate thread for resampling in 31dc60e. Could you check whenever it works better or worse?

I will try but openSUSE Open Build Service is down for a moment and this is where i build my packages since setting up local compilation on binary distribution is a pain. It will probably soon go up though.

> I must mention that I don't have realtime scheduling set up. Perhaps that is what really does matter.

Maybe, it was quite a hassle to properly set up for me and i came to conclusion that HDA built-in soundchips should not have less than 1024 frames per period set up in JACK server in any case. Realtime probably is not very critical when without a noticeable CPU load on multi-core system but it just possible that kernel scheduler may decide to take JACK's time necessary even for basic needs when JACK processes are doing less if such is not forbidden by realtime requirement. In my case restrictions are more narrow because i route all sound to Jamin for compression, consequently i could not get any less reliable JACK server latency than 42.7ms even with max realtime & priority on supposedly 6-core system. But pretty much everything (video & audio players, even run via PulseAudio as JACK client) seems to be stable other than Firefox with its atrocious cubeb library, mpv (but only in "legacy mode", if ran by smplayer with some obsolete settings) and freshplayerplugin now. It not bad, it just i don't think i have ever seen libflashsupport giving xrun once even when video or network troubles occurred.

You can check out settings for realtime in build scripts of my distro that probably would work in pretty much everything else.
[.jackdrc generated by qjackctl](https://github.com/v-fox/live_opensuse_hsf/blob/master/data/common-userfiles/.jackdrc)
[qjackctl for heavy Jamin load](https://github.com/v-fox/live_opensuse_hsf/tree/master/data/common-userfiles/.config/rncbc.org)
[Jamin ultimate equalizer config](https://github.com/v-fox/live_opensuse_hsf/blob/master/data/common-userfiles/.jamin/global-output.jam)
[ALSA as JACK client](https://github.com/v-fox/live_opensuse_hsf/blob/master/data/common-userfiles/.asoundrc)
[PA as JACK client](https://github.com/v-fox/live_opensuse_hsf/tree/master/data/common-userfiles/.config/pulse)
[limits.conf with realtime](https://github.com/v-fox/live_opensuse_hsf/blob/master/source/root/etc/security/limits.conf)

**Comment by v-fox** [comment]
> I've added a separate thread for resampling in 31dc60e. Could you check whenever it works better or worse?

OK, i've tested for a day and haven't stumbled on xrun yet. Same goes for cubeb with 10 times lesser sleep delay. Damn fine !

However, to compile newest version I had to manually add libm for linking by
```
sed -i 's:img-resources:img-resources m:g' CMakeLists.txt
```
but it's maybe an OBS issue, because of recent updates. Previously probably something else pulled it on linking.

**Comment by i-rinat** [comment]
> add libm

Yep, you're right. I forgot to add it. Fixed in f2fd0902a7b9381d8c249cf2c3fbf9662fedd14f.

**Comment by i-rinat** [comment]
> I've tested for a day and haven't stumbled on xrun yet.

Sounds great! :-)

**Comment by i-rinat** [comment]
By the way, audio capture via JACK was added in 10a4add64270b401d2ca0aa4ef948a4c3fd6affb.

**Comment by v-fox** [comment]
> By the way, audio capture via JACK was added in 10a4add.

Awesome ! It does, however, makes only one port (with left channel only, it seems) while my microphone is stereo.

**Comment by i-rinat** [comment]
PPAPI have only single-channel capture support, so I've added connection from two capture ports into one input port in c7f1f3b540655e530d5f83cfd8ecc507f39b53a5.

**Comment by v-fox** [comment]
> PPAPI have only single-channel capture support, so I've added connection from two capture ports into one input port in c7f1f3b.

Ha, and Google said that PPAPI is the modernization of browser plugin API ! Fantastic job !
I guess [Flash is hardcoded for mono anyway](http://help.adobe.com/en_US/as3/dev/WS5b3ccc516d4fbf351e63e3d118a9b90204-7d1d.html)... Good thing that today web chats and SIP use opus in 48kHz mono or stereo with no Flash or any other proprietary software required.
