### ISSUE TITLE
No sound or squeaky voice in youtube

### ISSUE THREAD

**Issue by trappedinspacetime** [i-rinat/freshplayerplugin#16]
First of all congrats on your innovative work. I am on Ubuntu 13.10 32 bit platform. I tried it in firefox, it works ok but sometimes I get no sound while watching videos. I wanted to let you know.
Regards

**Comment by hardforkcoin** [comment]
Sorry for the late response. I didn't notice.

It works perfect now.

I'm using ALSA actually.

**Comment by i-rinat** [comment]
Nice to hear that.
