### ISSUE TITLE
Freshplayer continuously crashes tabs in Firefox nightly 40.0a1 (2015-04-09)

### ISSUE THREAD

**Issue by WizardGed** [i-rinat/freshplayerplugin#160]
I have flash disabled by default so it asks me to run flash applications every time a flash object on a page appears. when I click allow flash the tab crashes and asks me if I want to restart the tab. All forms of flash seem to do this. (I suspect this is an issue due to such a new version of Firefox). I will search the release notes for the transition from 39 to 40 as it seems to have been working until that update. if anyone can corroborate this it would be appreciated.

**Comment by i-rinat** [comment]
I think that's because I called `NPN_ReleaseObject()` and `NPN_RetainObject()` on the wrong thread. 411e24a9faf2851b4534db4c1c926d4f93958029 and 5dcefb77d6c81d5f37493892a1be5d0228d5cd2d makes it stop crashing on my machine.

Could you check again with recent version from `master` branch?

**Comment by WizardGed** [comment]
That was it! Thanks for catching that I was digging through my crash 
reports wondering what had screwed up. It didn't help there has been so 
much activity around plugins on the Mozilla side lately.
