### ISSUE TITLE
freshplayerplugin crash musescore 

### ISSUE THREAD

**Issue by rcspam** [i-rinat/freshplayerplugin#161]
Hi,
First, thank you for your freshplayerplugin.
On Ubuntu 14.04, musescore 2.0 crash due to freshplayerplugin when i launch the "start center" (shortcut F4):
$ musescore
.
.
.
qt.network.ssl: QSslSocket: cannot resolve SSLv2_client_method
qt.network.ssl: QSslSocket: cannot resolve SSLv2_server_method
NOT SANDBOXED
**[ERROR:flash/platform/pepper/common/pep_process.cpp(19)] CHECK(g_process_type == PROCESS_TYPE_UNKNOWN) failed** ../mscore-nightly/lancemscore : ligne 11 :  7777 Abandon    ../mscore-nightly/mscore "${@}"
$

**Comment by i-rinat** [comment]
Hello. It works fine in a newly installed (and updated Ubuntu 14.04.2), with musescore 2.0 from ppa:mscore-ubuntu/mscore-stable.

Can you get a backtrace?

**Comment by rcspam** [comment]
Indeed, it's ok, i purge all plugin (pepper, flash, fresh ) and after reinstall freshplayerplugin, musescore works well. But it does'nt work in firefox for me, video here are blank:
![flash-mozilla](https://cloud.githubusercontent.com/assets/10021906/7084274/ab3db198-df6b-11e4-90fc-ca850d1c6a27.png)

**Comment by rcspam** [comment]
I precise that's happened only on this page !!

**Comment by i-rinat** [comment]
> video here are blank

there was a bug, fixed in 1d2aa349e90e83563be9775e8d324259fabb3cec

**Comment by rcspam** [comment]
Cool,
Thanx

2015-04-10 19:30 GMT+02:00 Rinat Ibragimov <notifications@github.com>:

**Comment by i-rinat** [comment]
So, does it work?

**Comment by rcspam** [comment]
I can try it only when i come back home sunday !


2015-04-10 20:30 GMT+02:00 Rinat Ibragimov <notifications@github.com>:

**Comment by rcspam** [comment]
Sorry Rinat, I completly forget you,
Yes it works well now!
Sorry and thanks !
Regards
rcspam


2015-04-16 16:36 GMT+02:00 Rinat Ibragimov <notifications@github.com>:
