### ISSUE TITLE
Question: GTK3 support

### ISSUE THREAD

**Issue by kubrickfr** [i-rinat/freshplayerplugin#162]
Hi,

What are your plans/feasibility for FF GTK3 support? (to support Wayland).

F.

**Comment by i-rinat** [comment]
> What are your plans/feasibility for FF GTK3 support?

I try to keep code compilable against both GTK 2 and GTK 3. (Recent related changes were f2462fd1eb03294bd5438425fb11569a9666c39e and 4d9b4c6fab33b8442d8d802a7ea18143b14b1e6d). You can make GTK 3 version by changing `gtk+-2.0` to `gtk+-3.0` [here](https://github.com/i-rinat/freshplayerplugin/blob/31dc60e567d4c07d54a58c242bac02fc2cd1efa5/CMakeLists.txt#L42).

GTK 3 build of Firefox I tried, uses special trick to support GTK 2 plugins, so I removed `libmozgtk2.so` and made `libmozgtk.so -> libmozgtk2.so` symlink to force GTK 3 everywhere. And GTK 3 build of freshwrapper works in that setup. Most surprisingly, GTK 2 version works too. Don't know for sure why.

> to support Wayland

Plugins are inherently tied to X11, they require X Drawable to draw to; events have the same format too, and so on.

**Comment by MALLER-LAGOON** [comment]
is there any chance to add an cmake argument to select in that way the gtk+ libraries that the user want to use?, or if i do it and pull it, could you merge it, or just consider it unnecessary?

**Comment by i-rinat** [comment]
It's faster to add it (0bb050e6b20e6b1cefbbae80ef7a5a1532ecbc43) rather than to negotiate pull requests :-)
Parameter `WITH_GTK` is used to specify desired GTK+ version, for example:
```cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DWITH_GTK=3 ..```
or
```cmake -DWITH_GTK=2 ..```
Version 2 is selected by default.


But really, is it really useful  for anybody?

**Comment by MALLER-LAGOON** [comment]
at least for me, is very useful, and i guess @kubrickfr will appreciate it too.

thank u :3
