### ISSUE TITLE
Is /etc/adobe/mms.cfg useful for freshplayerplugin?

### ISSUE THREAD

**Issue by wzhy90** [i-rinat/freshplayerplugin#166]
Is this file still works with this project?

**Comment by i-rinat** [comment]
No, it doesn't.
PepperFlash is designed to run in sandboxed environment, so usually it have no direct access to the filesystem. All configuration is done though PPAPI, particularly through `PPB_Flash` interface, I think.

**Comment by azuwis** [comment]
When used with freshplayerplugin, PepperFlash will read

    ~/.config/freshwrapper-data/Shockwave\ Flash/System/mms.cfg

config file. I tried:

    RTMFPP2PDisable = 1

And it worked.

@i-rinat Should this be mentioned in README file?

**Comment by i-rinat** [comment]
@azuwis, thanks for the catch. Mentioned in https://github.com/i-rinat/freshplayerplugin/blob/master/doc/known-issues.md#where-is-mmscfg.
