### ISSUE TITLE
[Proposal] Add simple way to use flash player

### ISSUE THREAD

**Issue by JamesTheAwesomeDude** [i-rinat/freshplayerplugin#168]
Right now, to get an updated Adobe Flash Player on Linux, there are only 4 ways:

* Use **Google Chrome** (extremely easy to do, just install one package)
* Use **Chromium with `chromium-pepperflash`** (pretty easy to do, just add a PPA and a package)
* Use **Pipelight/Silverlight plugin** (rather easy to do, just add a PPA and a package and run one command. Updating takes a single command.)
* Use **`freshplayerplugin` with pepper flash** (add PPA, install package, download Google Chrome, extract a file from the package, put the file somewhere, edit freshplayer's configuration file, then rinse and repeat steps 3-6 every time there's an update)

One of these methods is not like the others.. :wink: Maybe there could be a simple way to include Pepper Flash with the installation? Something like the way the `chromium-pepperflash` package works, perhaps?

**Comment by i-rinat** [comment]
> Something like the way the chromium-pepperflash package works, perhaps?

Have you tried to omit "edit freshplayer's configuration file" step? :-)
If one doesn't create configuration file, or doesn't specify path to PepperFlash, freshwrapper will look into a number of places [[link](https://github.com/i-rinat/freshplayerplugin/blob/0bb050e6b20e6b1cefbbae80ef7a5a1532ecbc43/src/config_pepperflash.c#L28)]. It can load `libpepflashplayer.so` from installed Chrome (stable, beta, and unstable), pepperflashplugin-nonfree, and some others. Installed Chrome will get you updates via packaging system as soon as they are released.

If you are building freshwrapper from source, you can create symlink from `libfreshwrapper-pepperflash.so` in build directory to `~/.mozilla/plugins` to avoid copying resulting library every time.

**Comment by Electrocat** [comment]
mdeslauriers 7 points 6 days ago 

The adobe-flashplugin package now ships with both versions of Flash NPAPI (Firefox) and PPAPI (Chromium). It's a recent change on Canonical's part. This change is included in all currently supported releases.

See: http://www.reddit.com/r/Ubuntu/comments/32levk/adobeflashplugin_package_in_1504_development/

**Comment by i-rinat** [comment]
Added `adobe-flashplugin` path to the search list in bc68045b580dbccbdda7e1ddaa72ba9c5b318a54. 
Note, `adobe-flashplugin` package lacks `manifest.json`, which is used to determine version. Version will be displayed incorrectly on `about:plugins` page.

**Comment by JamesTheAwesomeDude** [comment]
Aha, it seems that `/usr/lib/adobe-flashplugin/libpepflashplayer.so` is provided by the normal `adobe-flashplugin` package.

Is that spot searched by default? It lacks proper version information, but it's still pretty useful for most users. (If that spot is already in default search location, close this bug.)

Is it possible to efficiently check the version of that file manually? (Instead of looking at `manifest.json`, look inside `libpepflashplayer.so` itself)

**Comment by JamesTheAwesomeDude** [comment]
Since with bc68045, now all it takes to use freshplayerplugin is:

* Install `freshplayerplugin` (from PPA)
* Install `adobe-flashplugin` (from official repos)
* Restart browser
* Updates come from system package manager forever

This is a very simple way to use this!
