### ISSUE TITLE
Detect flash version with adobe-flashplugin system package

### ISSUE THREAD

**Issue by JamesTheAwesomeDude** [i-rinat/freshplayerplugin#169]
Would it be possible to automatically detect the Adobe Flash Player version when using the `adobe-flashplugin` package which (regrettably) lacks `manifest.json`? (For version information on about:plugins page)

Or do we need to send this bug to the `adobe-flashplugin` maintainers and request a `manifest.json` to come along with `libpepflashplayer.so`?

**Comment by i-rinat** [comment]
> Would it be possible to automatically detect the Adobe Flash Player version

It could be done, by calling `strings libpepflashplayer.so | grep LNX` every time. But that involves grepping 17MB file each time.

> Or do we need to send this bug to the `adobe-flashplugin` maintainers and request a `manifest.json` to come along with `libpepflashplayer.so`?

I think this is the best solution possible. By the way, `adobe-flashplugin_20150414.1.orig.tar.gz` already have `manifest.json`, so it will be easy to fix (one additional line in `debian/adobe-flashplugin.install.in`).

**Comment by JamesTheAwesomeDude** [comment]
Ah, that's about what I expected the situation to be.

I've [reported it on launchpad](https://bugs.launchpad.net/adobe-flash-plugin-tools/+bug/1446888) so the `adobe-flashplugin` maintainers can take a look. I think I made a convincing argument for its inclusion; hopefully we'll see that file included by the next update.

Thanks for this wonderful project!

**Comment by JamesTheAwesomeDude** [comment]
Why was this closed? It doesn't look like the upstream `adobe-flashplugin` changes needed to close this bug have been implemented yet.

**Comment by i-rinat** [comment]
Is there any point of keeping the issue open? I can't do anything in this project to solve the issue the right way.

**Comment by JamesTheAwesomeDude** [comment]
Is there an "on-hold" status or "upstream bug" label that can be applied?

**Comment by i-rinat** [comment]
Open issues where I have nothing to do are just visual noise. That's why I tend to close them.

**Comment by JamesTheAwesomeDude** [comment]
Hmm, that makes sense.

Sadly, there's no "can't fix yet" status that hides them while still awaiting future action.. :disappointed:

**Comment by i-rinat** [comment]
reported upstream: https://bugs.launchpad.net/ubuntu/+source/adobe-flashplugin/+bug/1520782

**Comment by i-rinat** [comment]
Looks like `manifest.json` is included in upstream package since version `1:20160712.1-0ubuntu1`.
