### ISSUE TITLE
"lefigaro" site , no video

### ISSUE THREAD

**Issue by promeneur** [i-rinat/freshplayerplugin#174]
go to www.lefigaro.fr

not any video is played with this site

we get a blank screen instead of a video screen

the error message is "animation non chargée" . in english "the application is not loaded" .

no pb with chromium

i join a FF capture
![lefigaro_ff](https://cloud.githubusercontent.com/assets/240424/7343485/51e193ee-ecc2-11e4-8bcb-9080783fbb90.png)

 and a chromium capture
![lefigaro_chromium](https://cloud.githubusercontent.com/assets/240424/7343501/6c939cfa-ecc2-11e4-8e74-62ed1c3a8b0f.png)

**Comment by promeneur** [comment]
i join the link of the example

http://www.lefigaro.fr/societes/2015/04/27/20005-20150427ARTFIG00007-airbus-fete-les-10-ans-de-l-a380-et-envisage-de-nouveaux-developpements.php

**Comment by i-rinat** [comment]
Hello. There is similar issue #153 which is caused by interference with HTTPS Everywhere browser addon.

Due to differences in PPAPI and NPAPI, freshwrapper code ignores stream from browser and asks for plugin content separately. HTTPS Everywhere successfully redirects initial plugin content from http to https, but block all further http requests, and thus video doesn't load.

As far as I know, HTTPS Everywhere have an exclusion list where particular site can be added, as a workaround.

**Comment by i-rinat** [comment]
I've submitted fix for #153 in abe3d525c9bd858e8eb7aeb05fa5b53261ebcc46. I believe it's related to the issue with www.lefigaro.fr and HTTPS Everywhere addon.

Could you check again with recent version?

**Comment by promeneur** [comment]
i get the 0.2.4 version .
i wait for the 0.3.0 one (perhaps 1 or more) for my opensuse 13.1 x86_64 then will test .

thanks

**Comment by i-rinat** [comment]
> I wait for the 0.3.0 one (perhaps 1 or more week)

I like your optimism. :smiley: 

I don't have regular release schedule, but they tend to happen once per one or two months. v0.2.4 was only four days ago, so it would be long wait. And long ago I thought development would be faster and decided to make v0.3.0 release after certain features implementation, with hardware video decoding acceleration amongst them. That one looks particularly hard, so most probably next release would be v0.2.5 instead.

Good luck waiting! :smiley:

**Comment by promeneur** [comment]
Opensuse 13.1 x86_64
Freshplayerplugin 0.3.0-1.1
no more pb with video and HTTPS Everywhere

thanks

**Comment by i-rinat** [comment]
OK, great.
