### ISSUE TITLE
No fullscreen

### ISSUE THREAD

**Issue by thierryOrdissimo** [i-rinat/freshplayerplugin#176]
On E17 the plugin does not pass in fullscreen, the bar of the stain stays below. I commented in the file ' ppb_flash_fullscreen.c ' on the code which follows:
```
//////////////////////////// ppb_flash_fullscreen.c /////////////////
/*
    // set window transient for browser window
    if (tp->browser_window != None)
        XSetTransientForHint(dpy, pp_i->fs_wnd, tp->browser_window);
    else
        trace_error("%s, can't get tp->browser_window\n", __func__);
*/
/////////////////////////////////////////////////////////////////////////////
```
It corrects problem, in my case.

**Comment by i-rinat** [comment]
I can partially reproduce it in E17 installed in Debian testing. Initial switching to fullscreen goes fine, but if you switch windows by Alt-Tab, fullscreen window acquires title and acts like a normal window. That is not exactly what you have. By the way, if one removes code that sets fs window transient to browser window, it becomes very hard to recover after Alt-Tab.

Which distribution do you use? Are you using E17 from your distro, or it's some custom version?

**Comment by thierryOrdissimo** [comment]
I use Ordissimo, a distribution linux used by about 60000 users. The probeme settles on ' V2 ' using ' Squeeze ' and ' V3 ' using ' Wheezy '. The version of used ' E17 ' and '0.17.3 ' changed to correspond needs. The navigator Web is a navigator using ' Firefox ' for ' Squeeze ' and ' Iceweasel ' for ' Wheezy ', it is written with XUL. Problem is present on two environements. It is a distribution simplified for the old persons, there is not ALT-TAB of shortened. The bar of menu always stays in front of, what is not case with the plugin adobeflash old, video is not fluid.
https://drive.google.com/file/d/0B6OSoPS_QARRWUFtbUpyX3hyOUE/view?usp=sharing

The addition of WM_WINDOW_ROLE corrects problem partly, the video window does not pass under the bar of menu, it is not any more the full-screen and it is fluid.
https://drive.google.com/file/d/0B6OSoPS_QARRaTFReGFhS0JGX00/view?usp=sharing


Finally I opted for the resolution represented in the ticket '*176 ', without subjecting of patch.

**Comment by i-rinat** [comment]
Sorry, I don't understand well what you say.

I guess bar on the bottom of the screen should be shown all the time, is it right? And I guess video gets resized to full height of the screen, then menu bar is drawn over it, effectively hiding part of the video.

I didn't find download link on the distribution website. Can it be downloaded?

By the way, in patch 1033647de12ad3f37f4856e0ae0682e811b188c0 some changes were made to fullscreen handling. Could you check it?

**Comment by thierryOrdissimo** [comment]
Desolate my English is poor.
I used the video in full-screen makes it '1033647de12ad3f37f4856e0ae0682e811b188c0 ', is drawn on 0.5 cm in the top-left corner.

**Comment by i-rinat** [comment]
What about 8ae0a228b07390ed8aebdc1fbae059e128778b26?

**Comment by thierryOrdissimo** [comment]
8ae0a228b07390ed8aebdc1fbae059e128778b26 correct the size of video in full-screen.
My taskbar stays by top.
https://drive.google.com/file/d/0B6OSoPS_QARRSy1RVy1XRnZjVkE/view?usp=sharing
https://drive.google.com/file/d/0B6OSoPS_QARRVGdPcExxZWNtcFU/view?usp=sharing

**Comment by i-rinat** [comment]
Is that expected behavior? Part of the video is hidden by the taskbar.

**Comment by i-rinat** [comment]
There are two cases possible:
![combined](https://cloud.githubusercontent.com/assets/923956/7471473/36b60112-f330-11e4-96b8-901fabc6e8b8.png)
Here blue rectangle is a video window, and green is the taskbar. As I can see from your screenshots, now it's acting more like pic on the right. But how is it supposed to act?

**Comment by thierryOrdissimo** [comment]
I am in left case, normal case being that to the right.

![screen](https://cloud.githubusercontent.com/assets/10682892/7472511/8c931d74-f333-11e4-807c-0beb5b45f570.png)

I am in left case, normal case is to the right.
By commenting on code below I am in the case of right.
/*
    // set window transient for browser window
    if (tp->browser_window != None)
        XSetTransientForHint(dpy, pp_i->fs_wnd, tp->browser_window);
    else
        trace_error("%s, can't get tp->browser_window\n", __func__);
*/

**Comment by i-rinat** [comment]
Oh, now I see. Is there any way to get that distro into VM, so I can test it?

**Comment by i-rinat** [comment]
Calling `XSetTransientForHint` is a required call. It makes fullscreen window act like "open file" dialog. I set that hint, then set hints that tell window manager to hide window from Alt-Tab sequence, and from taskbar. So it looks like browser window itself went fullscreen.

I can either find a way to solve the issue uniformly, without breaking behavior in other window managers, or can add explicit workaround. An option in configuration file, for example.

**Comment by thierryOrdissimo** [comment]
Hi,
I put a little time to generate a virtual system.
In /etc/apt/source.list.d/sr2010-devmod.list erase all lines with '192.168.1.13' and add the line:
 deb http: //substantielwww.dyndns.org/ordissimo sr2010 main

Connection ssh:
=========
user = root
password = toto

VM:
==
https://drive.google.com/file/d/0B6OSoPS_QARRckh2MW5hZGxPdEk/view?usp=sharing

**Comment by i-rinat** [comment]
Thanks for the VM.

From my tests I can say, it's window manager decision to make fullscreen window of size 800x520 instead of full 800x600. The most right way to solve the issue is to change window manager's code.

But anyway, I've added option `tie_fullscreen_window_to_browser` to the config file. Setting it to `0` will disable setting "transient" hint.

**Comment by thierryOrdissimo** [comment]
Thank you for the option, it is ! Perfect for me,

**Comment by i-rinat** [comment]
Oh, one more thing. I found that one should use `tie_fullscreen_window_to_browser = 0L;` to make option work. Older libconfig versions have strict type requirements.
