### ISSUE TITLE
Webcam and microphone are not recognised

### ISSUE THREAD

**Issue by MirkoCe** [i-rinat/freshplayerplugin#18]
Sites where flash is used for webcam chat seem not to be supported. An easy example could be Omegle, where it says "webcam required".

**Comment by maferv** [comment]
This still persists to date

**Comment by i-rinat** [comment]
Yep, these are still not implemented at all.
One can determine whenever there is implementation for a feature by examining standard output. Function stubs are usually marked by `{zilch}`. Those messages are printed even if you do not request verbose tracing by compiling with `TRACE_ALL` enabled. You may need to launch browser in terminal emulator to see output.

**Comment by i-rinat** [comment]
Audio capture via PulseAudio (9628fb125286ca49933d2c15e5d4bea421153a09), and default ALSA sound card (eea44555f172c1a9877df01b684fdb0bbedc20c1) is now working.

**Comment by Vdragon** [comment]
:+1:

**Comment by i-rinat** [comment]
Audio capture via JACK was added in 10a4add64270b401d2ca0aa4ef948a4c3fd6affb.

**Comment by i-rinat** [comment]
Other capture devices could be selected if ALSA is used (2e880a75019961309d7f9762cafdbaac8346ddb3).

**Comment by i-rinat** [comment]
Video capture from `/dev/video0` implemented in 0d0834263f18cc77202fed888599f1fba4733b30.

**Comment by i-rinat** [comment]
Multiple webcams support implemented in 36b0932206c5e5f5b201ec48b98a616890bd49ca.

Code relies on udev to fill entries in `/dev/v4l/by-path`.

**Comment by i-rinat** [comment]
It took less than a year! Yeah! :smiley:

**Comment by Vdragon** [comment]
:100:
