### ISSUE TITLE
crunchyroll - firefox zoom - performance?

### ISSUE THREAD

**Issue by toddfraser88** [i-rinat/freshplayerplugin#180]
I've noticed recently with crunchyroll, if I use the zoom in firefox to scale up a few steps, that the plugin starts performing very poorly, almost crashing.

is it just me?

**Comment by i-rinat** [comment]
More details could give a hint.
* Are you have any custom options in config file?
* Are you using latest version of freshplayerplugin?
* How much CPU time is consumed by `plugin-container` process?
* What about `firefox` process, how much is consumed by it?
* Are CPU % numbers going up when you scale page up in Firefox?
* Does "performing very poorly" mean video frames are dropped?
* Or there are noticable lags?

**Comment by toddfraser88** [comment]
Are you have any custom options in config file?

audio_buffer_min_ms = 20
audio_buffer_max_ms = 500
audio_use_jack = 0
#pepperflash_path = "/opt/google/chrome/PepperFlash/libpepflashplayer.so"
pepperflash_path = "/usr/lib/pepperflashplugin-nonfree/libpepflashplayer.so"
flash_command_line = "enable_hw_video_decode=1,enable_stagevideo_auto=1"
enable_3d = 1
quiet = 0
fullscreen_width = 0
fullscreen_height = 0
randomize_dns_case = 0
device_scale = 1
quirk_plasma5_screensaver = 0
enable_windowed_mode = 0
enable_xembed = 1

Are you using latest version of freshplayerplugin?

latest commit, still happens

How much CPU time is consumed by plugin-container process?

about 9-15%

What about firefox process, how much is consumed by it?

firefox is blank

Are CPU % numbers going up when you scale page up in Firefox?

CPU % goes down actually, to 9-15%, when working normally it uses around 22-25%

Does "performing very poorly" mean video frames are dropped?

Firefox itself starts running very slowly, clicking on links and trying to switch tabs takes forever.

**Comment by i-rinat** [comment]
There has to be some interlocking issue where browser asks something from plugin, plugin takes too long to respond, and for that time whole browser waits for plugin to respond. That scenario would lead to what you are seeing.

Unfortunately I'm neither able to reproduce issue yet, nor have any idea how to solve it remotely. I'm still thinking about it.

**Comment by MALLER-LAGOON** [comment]
those % where watched with minimized windows or with the app windows open?
because, if u watch it with the windows minimized, the process goes down with the cpu consumption.

**Comment by toddfraser88** [comment]
I always have firefox maximized.

If you have VMware Workstation, see if you can recreate the problem in a Kubuntu 14.10 VM.

I've since created a Debian 8.x VM - It no longer slows down, but now I can't get 3d acceleration working.

**Comment by i-rinat** [comment]
Time tracing revealed delay between calling `NPN_InvalidateRect` and getting actual redraw request of about 100 ms. Usually it's about 2-3 ms or less. I think some of functions called by browser blocks, and that's related to pixmap content copying. If I remove copying at all, those delays gone.

**Comment by i-rinat** [comment]
Hard to admit it, but I can't fix it.
From timing various parts of freshwrapper I can say delays are from graphics stack itself. I was hoping to fix it whenever it's in drivers/Mesa/X.org, but it's too large for me.
