### ISSUE TITLE
is possible you have 3rd party cookies disabled..(was working just fine before)

### ISSUE THREAD

**Issue by ChrisFernandez** [i-rinat/freshplayerplugin#181]
ok is been working again just fine for weeks.. prob months now.. today I went to watch something and I got the "is possible you have 3rd party cookies disabled..." I research how to enable this on firefox and it was enable already... so not sure what happen... any ideas? only thing I did was install externsions to chrome but not firefox.

**Comment by i-rinat** [comment]
Sorry, I don't get it.
What exactly are you trying to do? What happens? What should happen?

Websites are dynamic. They are often updated at server side, so something could stop working even if you didn't change anything.

**Comment by ChrisFernandez** [comment]
well let me take a screenshot.. I just try to play one of my movies from google play..
give me 10m and i will post screenshot

**Comment by ChrisFernandez** [comment]
![flash_error](https://cloud.githubusercontent.com/assets/5316229/7464978/a9f5c18e-f296-11e4-8ce0-598eb78874b7.png)
![flash-installed](https://cloud.githubusercontent.com/assets/5316229/7464977/a9f41136-f296-11e4-8e03-24b83e86ffa8.png)

**Comment by ChrisFernandez** [comment]
This is what I get from the Debug option in flash.

cl=92492083&ts=1430429106&c=WEB&tpmt=0&el=embedded&framer=https%253A%252F%252Fplay%2Egoogle%2Ecom%252Fstore&debug%5FplaybackQuality=small&droppedFrames=0&debug%5FsourceData=&cfps=0&videoFps=0&vq=large&screenw=1920&h=480&debug%5FflashVersion=LNX%2015%2C0%2C0%2C189&screenh=1080&cplayer=AS3&ps=play&pixel%5Fratio=1&cver=as3&w=640&eurl=https%253A%252F%252Fplay%2Egoogle%2Ecom%252Fstore&fexp=900720%2C907263%2C924638%2C933112%2C934954%2C938028%2C9406985%2C9408142%2C948124%2C952612%2C952637%2C952642%2C957201&playerw=853&iframe=1&ei=OShIVY3aCNbqqQXdk4CYDA&cr=US&playerh=480&autoplay=1&idpj=0&scoville=1&lact=%2D1&cpn=PBlcNy78aUFjKY%5FU&stageFps=24&pd=0&ldpj=%2D22&erc=1&mos=0&hl=es%5FES&debug%5Fdate=Mon%20May%204%2022%3A17%3A38%20GMT%2D0400%202015&vis=0&next%5Fid=zseq5bLhaa8&volume=11%2E560000000000002&debug%5FvideoId=zseq5bLhaa8&debug%5Ferror=%5BErrorEvent%20type%3D%22error%22%20bubbles%3Dfalse%20cancelable%3Dfalse%20eventPhase%3D2%20text%3D%22GetVideoInfoError%3AEs%20posible%20que%20tengas%20que%20habilitar%20las%20cookies%20de%20terceros%20si%20las%20tienes%20bloqueadas%2E%22%5D

**Comment by i-rinat** [comment]
Now I get it, but still don't understand what's caused that. Did you changed version of freshwrapper? If yes, does downgrading solves it? Can you bisect to a commit that caused malfunctioning?

**Comment by ChrisFernandez** [comment]
No I did not changed version, but after this happen then I did.. when I took this screenshot it was already with new version but was happening in the older one too.
only thing I remember doing is adding chromium plugins but not to firefox...

**Comment by i-rinat** [comment]
You can try to remove `~/.config/freshwrapper-data` directory contents. Flash player stores data there, including keys for protected content. Probably it's worth to backup it before you delete that directory. If Flash cookies were used, directory removal will reset them.

**Comment by ChrisFernandez** [comment]
good idea, I'll try that when I get home from work and let you know.. *cruses fingers!*

**Comment by ChrisFernandez** [comment]
unfurtunatelly  that did not work

**Comment by i-rinat** [comment]
Indeed. I've finally got a movie in Play store. It plays for couple of seconds, then stops with an error.

**Comment by ChrisFernandez** [comment]
hello, did you figure out the problem? just wondering. :)

**Comment by i-rinat** [comment]
Nope.

I've tried to decompile player swf. There is one place there where that particular error is displayed, but that function could be called from couple of another places, which in turn could be called from a number of places. Probably that way leads nowhere, but I think key is somewhere inside player swf. From network timeline in Firefox I can tell player decides to stop requesting stream by itself, there is no failed requests near that time.

**Comment by ChrisFernandez** [comment]
hmm.. this also only started to happen like one week a go..a couple days before i posted this.

**Comment by i-rinat** [comment]
I had no testcase before recently, so can't tell whenever it worked at all in my case. Now I see it doesn't. As for recent changes in freshwrapper itself, I tested old versions, they still don't work, so it's more likely external reason.

There can be bugs in freshwrapper, which was hidden before, and exposed now, when something changed in Play's player. I don't know. The only way to figure that out is to try to guess what was wrong, and then fix it. Trial-and-error approach. Hard part is that I don't have experience in ActionScript, especially in decompiled sources

**Comment by i-rinat** [comment]
Found that player on Play makes requests to `https://s.youtube.com/api/stats/qoe` with status parameters encoded in URL. One of such messages have `ec=drm.auth`, `eid=3315` and `seid=1000058`. From player code, `eid` is error id, and `seid` is supplementary error id.

There is a description can be found on http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/runtimeErrors.html:
> 	3315	The current security context does not allow this operation. 
>This error can occur when the remote SWF loaded by AIR isn't allowed access to Flash Access functionality. This error can also occur if a security error occurs during network access. Other possible security errors include errors due to a crossdomain.xml file, which restricts client access based on domain, or if crossdomain.xml is not accessible.  

So there is something related to `crossdomain.xml`. Flash uses that file to enforce request restrictions.

From comparing behavior in Linux and Windows versions, I've found that Windows version requests `https://www.youtube.com/crossdomain.xml`, `http://www.youtube.com/crossdomain.xml`, and `https://i.ytimg.com/crossdomain.xml`, while Linux versions requests `https://www.youtube.com/crossdomain.xml` and `https://s.youtube.com/crossdomain.xml`.

So the difference is request to `https://s.youtube.com/crossdomain.xml`. Immediately after that request, `drm.auth` error is signaled, and playback stops.

Can't say why is that so. Content of `crossdomain.xml` from both `www.youtube.com` and `s.youtube.com` is essentially the same.

**Comment by i-rinat** [comment]
Noticed request to `http://www.youtube.com/crossdomain.xml`. That request is present in Chrome on Windows, but absent in Firefox on Linux. However, tracing shows that player does request, which is aborted by browser (most probably due to forbidden http requests on https pages). Blocking that exact URL in Chrome on Windows gives similar error.

Need to find a way to change http/https request policy in Firefox.

**Comment by i-rinat** [comment]
www.youtube.com uses HSTS (HTTP Strict Transport Security) to redirect all http requests to https. And something bad happens inside Firefox when plugin requests http link — plugin just receives an error instead of redirection.

**Comment by i-rinat** [comment]
Found temporary workaround:
Using [Enforce Encryption](https://addons.mozilla.org/en-US/firefox/addon/enforce-encryption/) Firefox addon it's possible to control whenever redirects happen. To do so, install addon, then open https://www.youtube.com, click on icon in address bar, find and click on "more information" button. In showed dialog, on "Security" under "Privacy & History" label there is a line named "Encrypted connections enforced?" with a button "Stop enforcing". One needs to click that button so the value becomes "No". Then player on https://play.google.com/movies should work.

**Comment by i-rinat** [comment]
So I conclude, freshplayerplugin does nothing wrong, but Firefox refuses to download requested URL. Although it's possible to bypass browser and do networking directly, I'd like to avoid that.

**Comment by i-rinat** [comment]
(reported upstream: https://bugzilla.mozilla.org/show_bug.cgi?id=1223114)

**Comment by ChrisFernandez** [comment]
what this fix? I am going to close this, feel free to re-open

**Comment by i-rinat** [comment]
> what this fix?

No, it doesn't look fixed. I personally did nothing since reporting bug to Firefox's bug tracker. And there were no any activity on the other side aside checking the test plugin.
