### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by MALLER-LAGOON** [i-rinat/freshplayerplugin#184]
Since 92fa70c the freshplayerplugin turns very heavy and slow, the performance goes down very notoriously. i guess it has something to do with the new plugin weight, from 4.7MB in a16f3bf to a 18.xMB in the 2415749.

**Comment by i-rinat** [comment]
Size increased because ANGLE source was added. I use shader translator to convert shaders from OpenGL ES 2.0 to desktop OpenGL 2.0. Maybe that's overkill, but rather than inventing own translator, it's better to take ANGLE, which was certified for OpenGL ES 2.0 support.

First commit you mentioned (92fa70c7ce8db21b2d4a11910e205585c9ee6d77) is source code itself, it's not yet linked at that point. But later patches do add changes to 3d-related code.

Does it really slows down? As far as I know, Flash doesn't use too many shaders, so overhead should be negligible. What video adapter do you have, again? (I need to write it down; always forget to do it).

**Comment by MALLER-LAGOON** [comment]
i have an ATI 5670.
and the performance issue i notice it mostly in flash games, and HD videos too.

**Comment by i-rinat** [comment]
I've disabled ANGLE in 6d347a40e7f464ee889c0fa513b42de3bc0c8dc4. It doesn't solve issue with nVidia cards, so there's no reason to keep it enabled. (It still can be enabled by configuring with `-DWITH_GLES2=0`)

**Comment by MALLER-LAGOON** [comment]
thank u (Y)

**Comment by i-rinat** [comment]
After I tried fgrlx, I need to ask. Do you have working 3d acceleration in freshplayerplugin on fglrx? Looks like my setup is missing GLX_ARB_create_context, GLX_ARB_create_context_profile, and GLX_EXT_create_context_es2_profile. If native GLES2 is used, all those GLX extensions are essential, 3d context won't be created if any of them is missing.

**Comment by MALLER-LAGOON** [comment]
how can i test that?

**Comment by i-rinat** [comment]
> how can i test that?

Launch browser from terminal. You'll see warning about missing `GLX_EXT_create_context_es2_profile` if it's really missing. Also running `glxinfo` will print all available GLX extensions.

**Comment by MALLER-LAGOON** [comment]
i'd launch the firefox from terminal, i run some facebook games, videos on youtube normal and HD, and the only message that i get from the beggining was this:

![i-rinat](https://cloud.githubusercontent.com/assets/7074901/7569659/a097430c-f7e0-11e4-9b7c-9a05a160182b.png)

and im not sure if this is related to freshplayer or to my gtk theme.

**Comment by MALLER-LAGOON** [comment]
>console.warn: Ignoring preferences-branch (not a valid branch name)
&#62;&#62;&#62; installPolicy shouldProcess() ...
NOT SANDBOXED
[fresh  4484] not implemented: PPB_OpenGLES2DrawBuffers(Dev);1.0
&#62;&#62;&#62; installPolicy shouldProcess() ...
&#62;&#62;&#62; installPolicy shouldProcess() ...
[fresh] [warning] ppb_var_var_to_utf8, 'var' is not a string, (0)
&#62;&#62;&#62; installPolicy shouldProcess() ...
&#62;&#62;&#62; installPolicy shouldProcess() ...
&#62;&#62;&#62; installPolicy shouldProcess() ...
[fresh] [warning] ppb_var_var_to_utf8, 'var' is not a string, (0)
&#62;&#62;&#62; installPolicy shouldProcess() ...
&#62;&#62;&#62; installPolicy shouldProcess() ...
[fresh] [warning] ppb_graphics3d_create, some of GLX_ARB_create_context, GLX_ARB_create_context_profile, GLX_EXT_create_context_es2_profile missing

that is what i get from console.

**Comment by i-rinat** [comment]
> ppb_graphics3d_create, some of GLX_ARB_create_context, GLX_ARB_create_context_profile, GLX_EXT_create_context_es2_profile missing

That line in output means, no 3d context is created, so all drawing including scaling, is done in software mode.

**Comment by i-rinat** [comment]
As long as shader translator is used, those extensions are not required. I tried to do so, and surprisingly, performance become worser than with software rendering (Radeon HD 7730M). Of course, CPU load is lower, about 60-80% versus 300-400% for software rendering, but it noticeably lags. I think it's about 10-15 fps. And 60-80% is still twice higher than with integrated intel videoadapter, which easily gives 60 fps.

I wish I know what's going on.
