### ISSUE TITLE
enable 3d not working in debian 8.x

### ISSUE THREAD

**Issue by toddfraser88** [i-rinat/freshplayerplugin#185]
could anyone else try this plugin on Debian 8.x in a VMWare VM? 

Enable 3D doesn't seem to work for me.

**Comment by MALLER-LAGOON** [comment]
i have Debian 8 on my PC, but i'd remember that the 3D is enabled by default in the freshplayerplugin, since 12add65.

**Comment by toddfraser88** [comment]
I get a black screen with audio when the 3D is turned on - which is default.

I've had to turn 3D off to get any picture.

**Comment by MALLER-LAGOON** [comment]
thats rare.
which graphic adapter do you have?

**Comment by toddfraser88** [comment]
r9 290x

VMware has it's own Virtualized Graphics

oddly though, it works just fine in a Kubuntu VM.

**Comment by MALLER-LAGOON** [comment]
that's rare.

i'll try to VM a jessie latter, and i tell u how it works for me.

**Comment by i-rinat** [comment]
Reproduced with Debian 8 in VmWare Player. Black screen indeed. I'll take a look.

**Comment by toddfraser88** [comment]
any progress made regarding this?

**Comment by i-rinat** [comment]
Nope, not yet. I've been busy recently.

**Comment by wyatt8740** [comment]
I have a physical copy of debian 8 on my laptop. I can check it out if someone can send me a flash you're having trouble with.

**Comment by toddfraser88** [comment]
try any flash video with 3d turned on, you should get a black box where the video is.

This is observed in a VMWare VM though, it might be different on real hardware.

**Comment by i-rinat** [comment]
OK, I tried again, with a test app. And it looks like offscreen rendering doesn't work for some reason. I actually already had a test app, in `tests/util_glx_pixmap` which can be built by calling `make util_glx_pixmap`.

That app does essentially the same freshwrapper does for rendering. Creates an (offscreen) X Pixmap, GLX Pixmap, acquires GL context, calls glClear() twice, first time with red color, then with green color. Then copies that pixmap content to a visible window.

In ideal case you should see a window with green a box. If you have glClear() bug, box will be red. And if you don't have offscreen rendering working, box will be either black or there will be no box at all, only window background, which is a tint of blue.

With such simple app failing to render correctly, it's hardly possible to make anything about that in freshwrapper.

**Comment by toddfraser88** [comment]
So there is no possible fix for this?

**Comment by i-rinat** [comment]
Maybe downgrading Mesa version will help. I've tried to install Mesa packages from Debian testing, but that had no effect.

**Comment by toddfraser88** [comment]
I'm not entirely sure how to downgrade mesa.

**Comment by i-rinat** [comment]
One way is to install corresponding packages from Debian Wheezy, which is previous stable. Another option is to checkout Mesa git repository and try to build different versions.

**Comment by toddfraser88** [comment]
I tried out debian 7 wheezy, I can get a picture, but hardware accelerated decoding won't work, even when enabled in the config.

maybe i should switch back to ubuntu.

**Comment by i-rinat** [comment]
> but hardware accelerated decoding won't work

Try newest version; configure with
```
cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DWITH_GLES2=0 ..
```

**Comment by toddfraser88** [comment]
that made no difference for debian 8, i will try 7

**Comment by toddfraser88** [comment]
I tried on debian 7, it seems to work, it said accelerated video decoding in stats for nerds, but the FPS was worse than software rendering, could not get above 10 FPS.

maybe I configured mine wrong?

**Comment by i-rinat** [comment]
> maybe I configured mine wrong?

Maybe something wrong with driver. Or maybe something wrong with my code, but that only reveals on your hardware.

By the way, are you still using VMware virtual machine? If so, it's hardly possible VA-API to be available under VMware.

**Comment by toddfraser88** [comment]
yes, I'm still using a VMWare VM.

**Comment by i-rinat** [comment]
I think there is no easy solution. I'll need to investigate it further.

**Comment by toddfraser88** [comment]
It's probably easier if I just leave debian and switch to another distro

**Comment by i-rinat** [comment]
This is another issue which I can't fix. I still have similar issue on my own machine, plugin content is all black with using discrete adapter via `DRI_PRIME=1`. Perhaps reasons are also similar. I've tracked mine to DRI2 subsystem in X.Org server. It could be X server itself, or radeon driver, or maybe even something somewhere else.
