### ISSUE TITLE
Current git does not link

### ISSUE THREAD

**Issue by fakbill** [i-rinat/freshplayerplugin#186]
Linking C executable dep_check
../libfreshwrapper-pepperflash.so: undefined reference to `v4l2_open'
../libfreshwrapper-pepperflash.so: undefined reference to `v4l2_read'
../libfreshwrapper-pepperflash.so: undefined reference to `v4l2_close'
../libfreshwrapper-pepperflash.so: undefined reference to `v4l2_ioctl'
collect2: error: ld returned 1 exit status
src/CMakeFiles/dep_check.dir/build.make:87: recipe for target 'src/dep_check' failed
make[2]: *** [src/dep_check] Error 1
CMakeFiles/Makefile2:267: recipe for target 'src/CMakeFiles/dep_check.dir/all' failed
make[1]: *** [src/CMakeFiles/dep_check.dir/all] Error 2
Makefile:76: recipe for target 'all' failed
make: *** [all] Error 2
root@nano:/usr/local/src/freshplayerplugin/build# cd ..
root@nano:/usr/local/src/freshplayerplugin# git pull
Already up-to-date.

**Comment by fakbill** [comment]
Sorry for the noise. My fault.

**Comment by i-rinat** [comment]
New dependency was added: `libv4l2.pc`, can be found in Debian package `libv4l-dev`. Sometimes one need to delete `build` directory and configure again, in case of adding new libraries.

I'm not sure whenever it's something inherent to CMake, or I need to change `CMakeLists.txt` somehow to prevent that. Anyway, building from scratch works all the time.
