### ISSUE TITLE
Viber crash on launch

### ISSUE THREAD

**Issue by loki1368** [i-rinat/freshplayerplugin#187]
Viber start crashing on launch after i sent photos in the message

NOT SANDBOXED
[ERROR:flash/platform/pepper/common/pep_process.cpp(19)] CHECK(g_process_type == PROCESS_TYPE_UNKNOWN) failed

**Comment by i-rinat** [comment]
(related to #173)

Could you collect a backtrace?

**Comment by i-rinat** [comment]
I tried to reproduce, but Viber works on my machine with image sent. I see `NOT SANDBOXED` message in stdout, which means Viber uses browser, which loads `libfreshwrapper-pepperflash.so`.

**Comment by loki1368** [comment]
http://pastebin.com/u8Y2n3UJ

when i uninstall freshplayer plugin and use linux flash plugin from repos crash disappeared

**Comment by i-rinat** [comment]
I've moved calling of `PPP_InitializeModule` to the plugin thread in cbaa3d62d1657cdad58fd948b6a4e8053ea8fdbe. It's definitely related. Could you try again?

**Comment by loki1368** [comment]
Now works fine. Thank you.

**Comment by i-rinat** [comment]
Great.
