### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by redhatlinux10** [i-rinat/freshplayerplugin#189]
i am using openSUSE 13.2 64bit. i have installed dev lib `libv4l-devel-1.2.1-2.1.4`, and this package's content follows:
~~~
> rpm -ql libv4l-devel
/usr/include/libv4l-plugin.h
/usr/include/libv4l1-videodev.h
/usr/include/libv4l1.h
/usr/include/libv4l2.h
/usr/include/libv4l2rds.h
/usr/include/libv4lconvert.h
/usr/lib64/libv4l1.so
/usr/lib64/libv4l2.so
/usr/lib64/libv4l2rds.so
/usr/lib64/libv4lconvert.so
/usr/lib64/pkgconfig/libv4l1.pc
/usr/lib64/pkgconfig/libv4l2.pc
/usr/lib64/pkgconfig/libv4l2rds.pc
/usr/lib64/pkgconfig/libv4lconvert.pc
/usr/share/doc/packages/libv4l-devel
/usr/share/doc/packages/libv4l-devel/README.lib-multi-threading
~~~

but when i compile freshplayerplugin ( commit 155cab21502e7c54150e9b5737d3d3edba8f8391 ), i got the following error:
~~~
Linking C executable dep_check
../libfreshwrapper-pepperflash.so: undefined reference to `v4l2_open'
../libfreshwrapper-pepperflash.so: undefined reference to `v4l2_read'
../libfreshwrapper-pepperflash.so: undefined reference to `v4l2_close'
../libfreshwrapper-pepperflash.so: undefined reference to `v4l2_ioctl'
collect2: error: ld returned 1 exit status
src/CMakeFiles/dep_check.dir/build.make:87: recipe for target 'src/dep_check' failed
make[2]: *** [src/dep_check] Error 1
CMakeFiles/Makefile2:267: recipe for target 'src/CMakeFiles/dep_check.dir/all' failed
make[1]: *** [src/CMakeFiles/dep_check.dir/all] Error 2
Makefile:76: recipe for target 'all' failed
make: *** [all] Error 2
~~~

please help me out, thanks advance.

**Comment by i-rinat** [comment]
Try to remove `build` directory and configure again from scratch. CMake caches a lot and doesn't notice adding another library to the list.

**Comment by redhatlinux10** [comment]
where is it this `build` directory? i can't find it in freshplayerplugin directory and its subdirs.

**Comment by i-rinat** [comment]
> where is it this build directory?

CMake pollutes source directories with generated files, if in-place configuration is used. That's why a separate directory is used. I generally create directory named `build` in source root, go there and run `cmake ..`. `..` here is a parent directory, i.e. path to where sources are.

If you use `cmake .` and compile in-place, it should be enough to delete just `CMakeCache.txt` file.

**Comment by redhatlinux10** [comment]
i removed `CMakeCache.txt` and my problem is gone. thanks.
