### ISSUE TITLE
Cannot use ChromeOS's Flash Plugin

### ISSUE THREAD

**Issue by wzhy90** [i-rinat/freshplayerplugin#190]
I downloaded the zako's chromeos recovery image and extract the libpepflashplayer.so to my patch.
but I cannot use at all
![20150520112629](https://cloud.githubusercontent.com/assets/2318890/7718468/4c9c9f36-fee3-11e4-8977-a0594d3bd079.png)

**Comment by MALLER-LAGOON** [comment]
did u try to redirect the location with freshwrapper.conf with
>pepperflash_path = "/opt/google/chrome/PepperFlash/libpepflashplayer.so"

or your current libpepflashplayer.so path?

**Comment by wzhy90** [comment]
My path is setting right.
I use the same path with the chrome browser's one fine

**Comment by i-rinat** [comment]
You are using Mint, if I recall correctly. Mint have older libstdc++ version than PepperFlash from ChromeOS was linked against. Thus it can't be loaded — some crucial symbols are missing in libstdc++. You can verify that by calling
```
ldd /usr/local/lib/PepperFlash/libpepflashplayer.so
```
Command will output all dependencies, with warnings if they are present.

In https://github.com/i-rinat/freshplayerplugin/issues/13#issuecomment-77615538 I've listed packages which needs to be upgraded. Note, that in https://github.com/i-rinat/freshplayerplugin/issues/13#issuecomment-100046610 was mentioned some packages are missing from that list.

**Comment by i-rinat** [comment]
@wzhy90, any success?

**Comment by helpdeskdan** [comment]
FYI - I use 14.04 - apt-add-repository ppa:ubuntu-toolchain-r/test gave me all the deps I needed to make ldd good.

**Comment by sandys** [comment]
@helpdeskdan - I also used 14.04. can you outline the steps you took to get this to work ? it'd be a big favor if you could go as detailed as possible.

**Comment by i-rinat** [comment]
I strongly believe the only way to solve the issue is to use newer libstdc++6, as closed-source component, PepperFlash requires it.
