### ISSUE TITLE
Some website don't detect flash

### ISSUE THREAD

**Issue by ThePierrezou** [i-rinat/freshplayerplugin#191]
Hello,
When i try to look a dailymotion live it say Device not supported.
You an try with one here ( http://games.dailymotion.com )
You can see this here too http://twitcam.livestream.com (it's not a dailymotion live)
The flash website detect well my flash ( http://www.adobe.com/fr/software/flash/about/ )
But here it don't https://www.whatismybrowser.com/is-flash-installed
I use freshplayerplugin-git on arch 64 bits with firefox.
Thanks
ThePierrezou

**Comment by MALLER-LAGOON** [comment]
i use debian 8, and don't have any of those issues.
¿did u try to use the latest commit of freshplayerplugin?

**Comment by ThePierrezou** [comment]
Something on my firefox profile was doing something bad.
After creating a new one it work.
Sorry and Thanks :)
