### ISSUE TITLE
Lower required libav version

### ISSUE THREAD

**Issue by hotice** [i-rinat/freshplayerplugin#194]
WIth the latest freshplayerplugin from Git, I can no longer built the package in my PPA for Ubuntu 14.04 LTS and 12.04 LTS, due to the libav dependency not being met (libavcodec>=54.39.0). Ubuntu 12.04 has libavcodec 53.35 while Ubuntu 14.04 has version 54.35.

 Because of this, Ubuntu 14.04 and 12.04 will no longer receive updates...

**Comment by i-rinat** [comment]
Cutting off older versions is bad for users, but good for me as developer. In recent changes (around January 2013) ffmpeg API for hardware accelerated decoders became easier to use.

So I'm going to add configure time bypass soon, and maybe lower required version later.

**Comment by hotice** [comment]
Thanks!

**Comment by i-rinat** [comment]
After all hardware accelerated decoding turned out to be no big deal. For some unknown reason with hwaccel enabled, 30fps videos on Youtube are rendered at 20fps, and 60fps are at 40fps. 40 instead of 60 is not great but OK, while 20 instead of 30 looks bad.

It really looks like forced limit — Chrome have 40 fps limit too.

**Comment by i-rinat** [comment]
After 84f251653da666642b3c7d2d9eed4b53934be3e4, it should be possible to omit hwdec code by configuring like:
```
cmake -DWITH_HWDEC=0 -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
```

**Comment by hotice** [comment]
Seems to work, thank you!

**Comment by i-rinat** [comment]
Added `enable_hwdec` configuration file option which controls use of hardware-accelerated video decoding. By default, hwdec is disabled.

**Comment by i-rinat** [comment]
Added compatibility tricks in c7d6e178330fe7b4daf33854bab12ea4dd18737f. They are enough to make code compile on Debian 7 (and probably on Ubuntu 12.04 — they use the same libav version). I haven't checked intermediate versions, but they should be fine.

Please let me know if it fails to build on some distribution.

**Comment by yxmline** [comment]
https://github.com/i-rinat/freshplayerplugin/commit/c7d6e178330fe7b4daf33854bab12ea4dd18737f,
https://github.com/i-rinat/freshplayerplugin/commit/fdbe711e86c10346d6e28a31bbe8abfc96375d08
~/Development/freshplayerplugin$ sh Build.sh
Already up-to-date.
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.26") 
-- checking for modules 'alsa;glib-2.0;gio-2.0;x11;xrandr;xrender;xcursor;gl;libconfig;libevent;libevent_pthreads;cairo;pango;pangocairo;pangoft2;freetype2;openssl;libv4l2'
--   found alsa, version 1.0.27.2
--   found glib-2.0, version 2.40.2
--   found gio-2.0, version 2.40.2
--   found x11, version 1.6.2
--   found xrandr, version 1.4.2
--   found xrender, version 0.9.8
--   found xcursor, version 1.1.14
--   found gl, version 10.6.0-rc2
--   found libconfig, version 1.4.9
--   found libevent, version 2.0.21-stable
--   found libevent_pthreads, version 2.0.21-stable
--   found cairo, version 1.13.1
--   found pango, version 1.36.3
--   found pangocairo, version 1.36.3
--   found pangoft2, version 1.36.3
--   found freetype2, version 17.1.11
--   found openssl, version 1.0.1f
--   found libv4l2, version 1.0.1
-- checking for module 'gtk+-2.0'
--   found gtk+-2.0, version 2.24.23
-- checking for module 'glesv2'
--   found glesv2, version 10.6.0-rc2
-- checking for optional dependencies
--   found libpulse, version 4.0 (optional)
--   found jack, version 1.9.10 (optional)
--   found soxr, version 0.1.1
-- checking for modules 'libavcodec;libavutil;libva;libva-x11'
--   found libavcodec, version 54.35.0
--   found libavutil, version 52.3.0
--   found libva, version 0.37.0
--   found libva-x11, version 0.37.0
-- Configuring done
-- Generating done

/home/linsertlon/Development/freshplayerplugin/src/ppb_video_decoder.c: In function ‘avcodec_free_context’:
/home/linsertlon/Development/freshplayerplugin/src/ppb_video_decoder.c:81:5: error: implicit declaration of function ‘av_freep’ [-Werror=implicit-function-declaration]
     av_freep(pavctx);
     ^
/home/linsertlon/Development/freshplayerplugin/src/ppb_video_decoder.c: In function ‘get_format’:
/home/linsertlon/Development/freshplayerplugin/src/ppb_video_decoder.c:202:23: error: ‘AV_PIX_FMT_VDPAU’ undeclared (first use in this function)
         if (fmt[k] == AV_PIX_FMT_VDPAU)
                       ^
/home/linsertlon/Development/freshplayerplugin/src/ppb_video_decoder.c:202:23: note: each undeclared identifier is reported only once for each function it appears in
cc1: some warnings being treated as errors
make[2]: *** [src/CMakeFiles/freshwrapper-obj.dir/ppb_video_decoder.c.o]
- - with ffmpeg build error on ubuntu 14.04 x64

**Comment by i-rinat** [comment]
I've changed FFmpeg API detection in 1870403d82af286189347deb2eae2d5eeb409ade, so if you still issues with compiling, it's worth to try recent version.

**Comment by i-rinat** [comment]
Compilation with older ffmpeg versions was broken after I tried to add VDPAU support. It should be compilable again after efa056dc9d61ca445acc0016e0eb3eefb1bef2f0.
