### ISSUE TITLE
FTBFS: Build failed at ppb_video_decoder.c with ffmpeg 2.6.3.

### ISSUE THREAD

**Issue by Artanejp** [i-rinat/freshplayerplugin#195]
When building with 84f251653da666642b3c7d2d9eed4b53934be3e4 , failed at ppb_video_decoder.c .
Build log is below:
--- START ---
/home/foo/src/freshplayerplugin/src/ppb_video_decoder.c:44:1: error: return type is an incomplete type
 get_format(struct AVCodecContext *s, const enum AVPixelFormat *fmt)
 ^
/home/foo/src/freshplayerplugin/src/ppb_video_decoder.c: In function 'get_format':
/home/foo/src/freshplayerplugin/src/ppb_video_decoder.c:50:5: error: invalid use of undefined type 'enum AVPixelFormat'
     for (int k = 0; fmt[k] != AV_PIX_FMT_NONE; k ++) {
     ^
/home/foo/src/freshplayerplugin/src/ppb_video_decoder.c:50:24: error: dereferencing pointer to incomplete type
     for (int k = 0; fmt[k] != AV_PIX_FMT_NONE; k ++) {
                        ^
/home/foo/src/freshplayerplugin/src/ppb_video_decoder.c:50:31: error: 'AV_PIX_FMT_NONE' undeclared (first use in this function)
     for (int k = 0; fmt[k] != AV_PIX_FMT_NONE; k ++) {
                               ^
/home/foo/src/freshplayerplugin/src/ppb_video_decoder.c:50:31: note: each undeclared identifier is reported only once for each function it appears in
/home/foo/src/freshplayerplugin/src/ppb_video_decoder.c:51:9: error: invalid use of undefined type 'enum AVPixelFormat'
         if (fmt[k] == AV_PIX_FMT_VAAPI_VLD)
         ^
/home/foo/src/freshplayerplugin/src/ppb_video_decoder.c:51:16: error: dereferencing pointer to incomplete type
         if (fmt[k] == AV_PIX_FMT_VAAPI_VLD)
                ^
/home/foo/src/freshplayerplugin/src/ppb_video_decoder.c:51:23: error: 'AV_PIX_FMT_VAAPI_VLD' undeclared (first use in this function)
         if (fmt[k] == AV_PIX_FMT_VAAPI_VLD)
                       ^
/home/foo/src/freshplayerplugin/src/ppb_video_decoder.c:53:9: error: invalid use of undefined type 'enum AVPixelFormat'
         if (fmt[k] == AV_PIX_FMT_VDPAU)
         ^
/home/foo/src/freshplayerplugin/src/ppb_video_decoder.c:53:16: error: dereferencing pointer to incomplete type
         if (fmt[k] == AV_PIX_FMT_VDPAU)
                ^
/home/foo/src/freshplayerplugin/src/ppb_video_decoder.c:53:23: error: 'AV_PIX_FMT_VDPAU' undeclared (first use in this function)
         if (fmt[k] == AV_PIX_FMT_VDPAU)
                       ^
/home/foo/src/freshplayerplugin/src/ppb_video_decoder.c:90:9: warning: 'return' with a value, in function returning void
         return AV_PIX_FMT_VAAPI_VLD;
         ^
/home/foo/src/freshplayerplugin/src/ppb_video_decoder.c:96:5: error: invalid use of undefined type 'enum AVPixelFormat'
     return fmt[0];
     ^
/home/foo/src/freshplayerplugin/src/ppb_video_decoder.c:96:15: error: dereferencing pointer to incomplete type
     return fmt[0];
               ^
/home/foo/src/freshplayerplugin/src/ppb_video_decoder.c:96:5: warning: 'return' with a value, in function returning void
     return fmt[0];
     ^
/home/foo/src/freshplayerplugin/src/ppb_video_decoder.c: In function 'get_buffer2':
/home/foo/src/freshplayerplugin/src/ppb_video_decoder.c:136:5: error: unknown type name 'AVBufferRef'
     AVBufferRef *buf = av_buffer_create(pic->data[3], 0, release_buffer, vd, 0);
     ^
/home/foo/src/freshplayerplugin/src/ppb_video_decoder.c:136:5: error: implicit declaration of function 'av_buffer_create' [-Werror=implicit-function-declaration]
/home/foo/src/freshplayerplugin/src/ppb_video_decoder.c:136:24: warning: initialization makes pointer from integer without a cast
     AVBufferRef *buf = av_buffer_create(pic->data[3], 0, release_buffer, vd, 0);
                        ^
/home/foo/src/freshplayerplugin/src/ppb_video_decoder.c:139:8: error: 'AVFrame' has no member named 'buf'
     pic->buf[0] = buf;
        ^
/home/foo/src/freshplayerplugin/src/ppb_video_decoder.c: In function 'ppb_video_decoder_create':
/home/foo/src/freshplayerplugin/src/ppb_video_decoder.c:229:20: error: 'AV_CODEC_ID_H264' undeclared (first use in this function)
     vd->codec_id = AV_CODEC_ID_H264;        // TODO: other codecs
                    ^
/home/foo/src/freshplayerplugin/src/ppb_video_decoder.c:242:5: error: implicit declaration of function 'avcodec_alloc_context3' [-Werror=implicit-function-declaration]
     vd->avctx = avcodec_alloc_context3(vd->avcodec);
     ^
/home/foo/src/freshplayerplugin/src/ppb_video_decoder.c:242:15: warning: assignment makes pointer from integer without a cast
     vd->avctx = avcodec_alloc_context3(vd->avcodec);
               ^
/home/foo/src/freshplayerplugin/src/ppb_video_decoder.c:254:14: error: 'AVCodecContext' has no member named 'refcounted_frames'
     vd->avctx->refcounted_frames = 1;
              ^
/home/foo/src/freshplayerplugin/src/ppb_video_decoder.c:256:27: warning: assignment from incompatible pointer type
     vd->avctx->get_format = get_format;
                           ^
/home/foo/src/freshplayerplugin/src/ppb_video_decoder.c:257:14: error: 'AVCodecContext' has no member named 'get_buffer2'
     vd->avctx->get_buffer2 = get_buffer2;
              ^
/home/foo/src/freshplayerplugin/src/ppb_video_decoder.c:259:5: error: implicit declaration of function 'avcodec_open2' [-Werror=implicit-function-declaration]
     if (avcodec_open2(vd->avctx, vd->avcodec, NULL) < 0) {
     ^
/home/foo/src/freshplayerplugin/src/ppb_video_decoder.c:264:5: error: implicit declaration of function 'av_frame_alloc' [-Werror=implicit-function-declaration]
     vd->avframe = av_frame_alloc();
     ^
/home/foo/src/freshplayerplugin/src/ppb_video_decoder.c:264:17: warning: assignment makes pointer from integer without a cast
     vd->avframe = av_frame_alloc();
                 ^
/home/foo/src/freshplayerplugin/src/ppb_video_decoder.c: In function 'ppb_video_decoder_destroy_priv':
/home/foo/src/freshplayerplugin/src/ppb_video_decoder.c:303:9: error: implicit declaration of function 'avcodec_free_context' [-Werror=implicit-function-declaration]
         avcodec_free_context(&vd->avctx);
         ^
/home/foo/src/freshplayerplugin/src/ppb_video_decoder.c:306:9: error: implicit declaration of function 'av_frame_free' [-Werror=implicit-function-declaration]
         av_frame_free(&vd->avframe);
         ^
/home/foo/src/freshplayerplugin/src/ppb_video_decoder.c: In function 'issue_frame':
/home/foo/src/freshplayerplugin/src/ppb_video_decoder.c:400:29: error: 'AVFrame' has no member named 'width'
                  0, 0, frame->width, frame->height,
                             ^
/home/foo/src/freshplayerplugin/src/ppb_video_decoder.c:400:43: error: 'AVFrame' has no member named 'height'
                  0, 0, frame->width, frame->height,
                                           ^
/home/foo/src/freshplayerplugin/src/ppb_video_decoder.c:401:29: error: 'AVFrame' has no member named 'width'
                  0, 0, frame->width, frame->height,
                             ^
/home/foo/src/freshplayerplugin/src/ppb_video_decoder.c:401:43: error: 'AVFrame' has no member named 'height'
                  0, 0, frame->width, frame->height,
                                           ^
cc1: some warnings being treated as errors
make[2]: *** [src/CMakeFiles/freshwrapper-obj.dir/ppb_video_decoder.c.o] Error 1
make[1]: *** [src/CMakeFiles/freshwrapper-obj.dir/all] Error 2
make: *** [all] Error 2
--- END ---
I'm using Debian/GNU Linux sid amd64 and deb-multimedia.org's libavcodec/ffmpeg 2.6.3.

--- START ---
ii  libavcodec-dev:amd64            10:2.6.3-dmo2        amd64                Library to encode decode multimedia streams - devel files
ii  libavdevice-dev:amd64           10:2.6.3-dmo2        amd64                Development files for libavdevice
ii  libavfilter-dev:amd64           10:2.6.3-dmo2        amd64                Development files for libavfilter
ii  libavformat-dev:amd64           10:2.6.3-dmo2        amd64                Development files for libavformat
ii  libavresample-dev:amd64         10:2.6.3-dmo2        amd64                Development files for libswresample
ii  libavutil-dev:amd64             10:2.6.3-dmo2        amd64                FFmpeg avutil devel files - devel files
--- END ---
Best regards,
Ohta.

**Comment by i-rinat** [comment]
Hi. First of all, have you tried to build from scratch? Recent commits were about cmake scripts, which could lead to errors if you first ran cmake on previous state, then updated source, and try to compile newer version after that.

**Comment by i-rinat** [comment]
Hello?

**Comment by Artanejp** [comment]
Sorry for later by my accident.

Still stopping compilation with same messages 
even latest commit.

Setting "WITH_HWDEC" to "TRUE" for cmake , error is happend.
Setting "WITH_HWDEC" to "FALSE" for cmake, error is not happened.

Cheers,
Ohta.

**Comment by i-rinat** [comment]
I'm trying to make it compile without `WITH_HWDEC=0` on as many ffmpeg/libav versions as possible, and I think there is way to do it. That will take time. I'll notify you then.

**Comment by Artanejp** [comment]
Sorry.
I reserved older libavcodec headers within /usr/local/include.
So, I failed compilation.
Now deleted them, I succeeded to build with "WITH_HWDEC=TRUE".

Sorry for miss reporting.

Ohta

**Comment by i-rinat** [comment]
I knew it. :smile:

Still, compatibility with older ffmpeg versions is a tedious task. Which still needs to be done.

**Comment by i-rinat** [comment]
I've changed FFmpeg API detection in 1870403d82af286189347deb2eae2d5eeb409ade, so if you still issues with compiling, it's worth to try recent version.

**Comment by evgeniy-fitsner** [comment]
I'm trying to build today and faced with the same error: https://gist.github.com/evgeniy-fitsner/db48115f3b7f4b021034

**Comment by i-rinat** [comment]
Yep, I was found existing compatibility macros' are still not enough for some versions, and added another couple in 445aab695d6b544968c68b19ea8a9fe4fb61811e dozen of minutes ago. Could you try again with the most recent version?

**Comment by evgeniy-fitsner** [comment]
Thank you , now master branch is building w/o issues
