### ISSUE TITLE
Crash many video site (0.3.0)

### ISSUE THREAD

**Issue by dacrhu** [i-rinat/freshplayerplugin#201]
Fedora 22
FF 38.0.5
freshplayerplugin 0.3.0

New dependency is ffmpeg. In the repo is ffmpeg 2.6.3.
I build with it.

The plugin crash in many site (eg: youtube.com, indavideo.hu, ultrasounds.com)
I tried with and without hw acceleration, same result.

This test working fine:
https://www.adobe.com/software/flash/about/

Thank you,
David

**Comment by beew** [comment]
I can confirm that, on many sites I get blackscreen
Same setup as dacrhu. Fedora 22 64 bit, Intel gpu

**Comment by dacrhu** [comment]
My video card is:
NVIDIA Corporation G98 [GeForce 8400 GS Rev. 2]

Driver: 
akmod-nvidia-340xx

Kernel:
4.0.4-303.fc22.x86_64

**Comment by i-rinat** [comment]
> I downgraded to previous version, 0.2.4, and working fine with.

That's interesting. Could you find which commit broke it? (`git bisect` will help to do it in a relative small number of steps).

**Comment by dacrhu** [comment]
Done (the last step):

$ git bisect bad
2cd794ee1ef11740c6afa7c39bfdbdf0b45c6fdc is the first bad commit
commit 2cd794ee1ef11740c6afa7c39bfdbdf0b45c6fdc
Author: Rinat Ibragimov <ibragimovrinat@mail.ru>
Date:   Fri May 1 13:14:46 2015 +0300

    x11et: request backing store for created window

:040000 040000 3f324cc6be6418bf0da6812f1555422aa9e15ffb 2ee6a74e7c1cf39f864d8bb063d4072ea988e701 M	src

**Comment by i-rinat** [comment]
@dacrhu, look into /var/log/Xorg.0.log. Is there anything about "Backing store"?

**Comment by i-rinat** [comment]
I've also effectively reverted changes by that patch in [disable-backing-store](https://github.com/i-rinat/freshplayerplugin/tree/disable-backing-store) branch, so you could try it.

**Comment by dacrhu** [comment]
[    51.634] (==) NVIDIA(0): Backing store enabled
I will try your patch.

**Comment by dacrhu** [comment]
Sorry, I get blank area in flash content. Don't work. :(

**Comment by hansvqp** [comment]
Same for me, I get this in xsession-errors:

libva info: VA-API version 0.37.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib64/dri/nvidia_drv_video.so
libva info: Found init function __vaDriverInit_0_36
libva info: va_openDriver() returns 0
[fresh] [error] [NP] caught Xlib error 8
[fresh] [error] [NP] caught Xlib error 3
[fresh] [error] [NP] caught Xlib error 3
[fresh] [error] [NP] caught Xlib error 3

**Comment by i-rinat** [comment]
Now branch [disable-backing-store](https://github.com/i-rinat/freshplayerplugin/tree/disable-backing-store) have backing store removal patch inserted just after backing store was requested (alternative history :smile:). Could you try again with bisection? There is something else that causes the bug, it would be nice to find it.

**Comment by dacrhu** [comment]
Ok, tomorrow I will try.

**Comment by dacrhu** [comment]
I tried many variation and the result same:

2cd794ee1ef11740c6afa7c39bfdbdf0b45c6fdc is the first bad commit
commit 2cd794ee1ef11740c6afa7c39bfdbdf0b45c6fdc
Author: Rinat Ibragimov <ibragimovrinat@mail.ru>
Date:   Fri May 1 13:14:46 2015 +0300

    x11et: request backing store for created window

:040000 040000 3f324cc6be6418bf0da6812f1555422aa9e15ffb 2ee6a74e7c1cf39f864d8bb063d4072ea988e701 M	src

**Comment by dacrhu** [comment]
Wow!!
I set enable_windowed_mode = 0 and working fine!!! :D

**Comment by dacrhu** [comment]
Info, my cmake out (version of libs, if you would like test it):

-- The C compiler identification is GNU 5.1.1
-- The CXX compiler identification is GNU 5.1.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.28") 
-- checking for modules 'alsa;glib-2.0;gio-2.0;x11;xrandr;xrender;xcursor;gl;libconfig;libevent;libevent_pthreads;cairo;pango;pangocairo;pangoft2;freetype2;openssl;libv4l2'
--   found alsa, version 1.0.29
--   found glib-2.0, version 2.44.1
--   found gio-2.0, version 2.44.1
--   found x11, version 1.6.3
--   found xrandr, version 1.4.2
--   found xrender, version 0.9.9
--   found xcursor, version 1.1.14
--   found gl, version 10.5.4
--   found libconfig, version 1.4.9
--   found libevent, version 2.0.21-stable
--   found libevent_pthreads, version 2.0.21-stable
--   found cairo, version 1.14.2
--   found pango, version 1.36.8
--   found pangocairo, version 1.36.8
--   found pangoft2, version 1.36.8
--   found freetype2, version 17.4.11
--   found openssl, version 1.0.1k
--   found libv4l2, version 1.6.2
-- checking for module 'gtk+-2.0'
--   found gtk+-2.0, version 2.24.28
-- checking for module 'glesv2'
--   found glesv2, version 10.5.4
-- checking for optional dependencies
--   found libpulse, version 6.0 (optional)
--   found jack, version 1.9.10 (optional)
--   found soxr, version 0.1.1
-- checking for modules 'libavcodec;libavutil;libva;libva-x11'
--   found libavcodec, version 56.26.100
--   found libavutil, version 54.20.100
--   found libva, version 0.37.0
--   found libva-x11, version 0.37.0
-- Configuring done
-- Generating done
-- Build files have been written to: /home/dacr/freshplayerplugin/build

Fedora 22 64bit
FF 38.0.5
Kernel: 4.0.4-303.fc22.x86_64

**Comment by i-rinat** [comment]
> I set enable_windowed_mode = 0 and working fine!!!

Oops. That was expected, but I totally forgot about it. With windowed mode disabled, plugin uses only pixmaps that browser provide, so changes about backing store of X11 windows have no effect. I guess fullscreen is still broken, since it creates window regardless of `enable_windowed_mode` value.

**Comment by dacrhu** [comment]
No working fine in all of screen size. The error situation is same like this:
https://github.com/i-rinat/freshplayerplugin/blob/master/doc/known-issues.md#black-screen-with-sound-only

I think you add this solution for this "Known issue".

**Comment by i-rinat** [comment]
I missed "22" part in "Fedora 22". With testing in virtual machine with Fedora 21 I saw no visual error (beside missing 3d acceleration due to VM), but now I installed Fedora 22 and it indeed have a black screen.

By the way, by disabling windowed mode you cut mouse wheel event and IME support. They wouldn't work in windowless mode. If you need one of those, it's worth to disable just XEmbed ( `enable_xembed = 0` )

**Comment by dacrhu** [comment]
Thank you, so I make a new package in Fedora copr repo with new parameters.

**Comment by i-rinat** [comment]
Patch d57ebb5b868606545159b0e71f63f619135d6a4d fixes black box effect for windowed instances in my installation of Fedora 22 (in VM).

**Comment by i-rinat** [comment]
Transparent plugins are still garbled.

By the way, [here](https://i-rinat.github.io/flash-test-cases/PartialTransparency/index.html) is a test page with plugins in transparent, opaque and direct modes. Last one is windowed, first two are windowless.

**Comment by dacrhu** [comment]
Thank you! Will be contain next release this patch?

**Comment by i-rinat** [comment]
I've pushed it into master branch already.

**Comment by i-rinat** [comment]
Argh! I've tried to figure out why transparent plugin is garbled for hours. And then decided to test how Flash 11.2 is working. The same visual garbage.

I guess there's something wrong with pixmap readback code. Since I had unusual error with X Visual of child window, there could be same issues in Firefox.

**Comment by dacrhu** [comment]
Accordingly it is not Fedora bug?

**Comment by i-rinat** [comment]
> Accordingly is not Fedora bug?

It could be unusual configuration, but wouldn't call it a distro bug.

**Comment by i-rinat** [comment]
Hi. It was found that F22 have Firefox built with GTK3 support. There are differences in code, that's why there were issues with rendering. There also an about:config parameter which changes rendering. It's not listed by default, so you need to add it manually.

Open `about:config` page, right click, select "New", "Boolean". Enter name "layers.use-image-offscreen-surfaces" with value "true". Then restart the browser.

Whenever it helped, could be checked on previously mentioned [page](https://i-rinat.github.io/flash-test-cases/PartialTransparency/index.html).
