### ISSUE TITLE
0.3.0 build error

### ISSUE THREAD

**Issue by rezso** [i-rinat/freshplayerplugin#203]
I tried to compile v 0.3.0 with ffmpeg 2.2.4
(-- checking for modules 'libavcodec;libavutil;libva;libva-x11'
--   found libavcodec, version 55.52.102
--   found libavutil, version 52.66.100
--   found libva, version 0.35.1
--   found libva-x11, version 0.35.1)
but I get this error:
[ 98%] Building C object src/CMakeFiles/freshwrapper-obj.dir/ppb_video_decoder.c.o
/var/uhubuild/work/compile/src/ppb_video_decoder.c: In function 'ppb_video_decoder_destroy_priv':
/var/uhubuild/work/compile/src/ppb_video_decoder.c:108:9: error: implicit declaration of function 'avcodec_free_context' [-Werror=implicit-function-declaration]
         avcodec_free_context(&vd->avctx);
         ^
cc1: some warnings being treated as errors
make[2]: *** [src/CMakeFiles/freshwrapper-obj.dir/ppb_video_decoder.c.o] Error 1
make[1]: *** [src/CMakeFiles/freshwrapper-obj.dir/all] Error 2

**Comment by i-rinat** [comment]
Could you try to build version from `master` branch? I was adding compatibility macros, they could help.

**Comment by rezso** [comment]
With the compatibility macros from the master the build was successful, thank you.
