### ISSUE TITLE
Only getting around 25 FPS with Acellerated Decoding in 0.3.0

### ISSUE THREAD

**Issue by Zombie-Ryushu** [i-rinat/freshplayerplugin#206]
I am only getting around 25 FPS, Max 28 FPS with FreshPlayerPlugin 0.3.0 and Flash 17.0.0.188. The number of Dropped Frames in Youtube gradually increases persistently.

**Comment by i-rinat** [comment]
I've just added VDPAU code a few hours ago. Did you try that? You need to delete `vdpau-va-driver` or add `enable_vaapi=0` to `~/.config/freshwrapper.conf` to use VDPAU directly.

**Comment by i-rinat** [comment]
Hello? Is behavior still the same with current version?

**Comment by Zombie-Ryushu** [comment]
It has been and changes to freshwrapper.conf make no difference. (the file doesn't even exist on most of my systems.)

**Comment by i-rinat** [comment]
Just to be sure. If you don't have a freshwrapper.conf, hardware accelerated decoding is disabled (as `enable_hwdec` defaults to `0`).

I think I did already ask, but how much CPU consumed by plugin-wrapper process?
What `perf top` displays while playing video?
Are there any messages with `[error]` or `[warning]` tags in the output if you run browser from terminal?
Does CPU consumption goes up when you switch to full screen?

**Comment by Zombie-Ryushu** [comment]
libva info: VA-API version 0.35.1
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib64/dri/nvidia_drv_video.so
libva info: va_openDriver() returns -1
NOT SANDBOXED
[fresh 12017] not implemented: PPB_OpenGLES2DrawBuffers(Dev);1.0
[fresh 12017] [PPB] {zilch} ppb_network_monitor_update_network_list
[fresh] [error] [NP] caught Xlib error 8
[fresh] [error] [NP] caught Xlib error 8
[fresh] [error] [NP] caught Xlib error 171
[fresh] [error] [NP] caught Xlib error 171
[fresh] [error] ppb_graphics3d_create, glXMakeCurrent failed
[fresh] [error] ppb_graphics3d_create, glXMakeCurrent failed

**Comment by i-rinat** [comment]
Could you check again with the recent version? A few hwdec fixes were added in bf84892e0eb753604b9a2f517966ca92fbc3329b and some previous commits.

**Comment by Zombie-Ryushu** [comment]
The FPS now hovers between 29 and 31 FPS on Youtube. I do still notice slight Tearing at the top of the screen, but its no where near as severe as before.

**Comment by i-rinat** [comment]
Good to know. I guess vdpau-va-driver was introducing another delay frame.
Tearing is another big issue which I don't know how to handle yet.
