### ISSUE TITLE
Conflict with Eclipse

### ISSUE THREAD

**Issue by m45t3r** [i-rinat/freshplayerplugin#207]
I was having some strange crashes using Eclipse. Tried to change OpenJDK versions (from 8 to 7) and it didn't solved it. After running Eclipse from the terminal I got some strange things from stdout/stderr:

    ~ » eclipse -clean
    NOT SANDBOXED
    libva info: VA-API version 0.37.0
    libva info: va_getDriverName() returns 0
    libva info: Trying to open /usr/lib/dri/i965_drv_video.so
    libva info: Found init function __vaDriverInit_0_37
    libva info: va_openDriver() returns 0
    [ERROR:flash/platform/pepper/common/pep_process.cpp(19)] CHECK(g_process_type == PROCESS_TYPE_UNKNOWN) failed

Wait, flash? I removed the freshplayerplugin and tried to run again:

    ~ » eclipse -clean
    java version "1.7.0_79"
    OpenJDK Runtime Environment (IcedTea 2.5.5) (Arch Linux build 7.u79_2.5.5-1-x86_64)
    OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)

And sure, this solved the problem. It is strange that I don't get any message from Java when freshplugin is installed too.

This seems similar to #26 and #187 but I am running the lastest version of freshplugin (commit f47d369f1e75c). Any ideas?

**Comment by m45t3r** [comment]
This problem was probably implemented in one of the most recent commits, since I don't remover having this issue before updating freshplugin.

**Comment by i-rinat** [comment]
Could you configure freshwrapper with `cmake -DTRACE_ALL=1 ..`, then compile with `make`, and then run Eclipse again? I'd like to to see which thread IDs are used for calls.

Do you have any special web page which opens when you start Eclipse?

> Wait, flash?

Just to clarify. Eclipse uses WebKit engine for internal browser. That engine have NPAPI plugins support, so it tries to load all available plugins (freshplayerplugin amongst them) when started.

**Comment by m45t3r** [comment]
> Could you configure freshwrapper with cmake -DTRACE_ALL=1 .., then compile with make, and then run Eclipse again? I'd like to to see which thread IDs are used for calls.

@i-rinat, sure, here you go:
```
NOT SANDBOXED
[fresh  3334] [NP] NP_Initialize aNPNFuncs=0x7f5d0b67fb28, aNPPFuncs=0x7f5d0b67fa88, browser API version = 19
[fresh  3334] GLX version 1.4
[fresh  3334] screensavers found: fd.o-screensaver gnome-screensaver
[fresh  3491]    calling callback={.func=0x7f5c98a4cf90, .user_data=0x7f5d69f5c918, .flags=0}, result=0, origin=ppb_message_loop_post_work
[fresh  3491]    returning from callback={.func=0x7f5c98a4cf90, .user_data=0x7f5d69f5c918, .flags=0}, result=0, origin=ppb_message_loop_post_work
[fresh  3334]    calling callback={.func=0x7f5c98a482e0, .user_data=0x7f5d69f73100, .flags=0}, result=0, origin=call_plugin_init_module
[fresh  3491]    calling callback={.func=0x7f5c98a48340, .user_data=0x7f5d69f73100, .flags=0}, result=0, origin=call_plugin_init_module_prepare_comt
[fresh  3491] [PPB] {full} ppb_get_interface interface_name=PPB_Core;1.0
[fresh  3334]    returning from callback={.func=0x7f5c98a482e0, .user_data=0x7f5d69f73100, .flags=0}, result=0, origin=call_plugin_init_module
[fresh  3491] [PPB] {full} ppb_get_interface interface_name=PPB_AudioConfig;1.1
[fresh  3491] [PPB] {full} ppb_get_interface interface_name=PPB_AudioInput(Dev);0.4
[fresh  3491] [PPB] {full} ppb_get_interface interface_name=PPB_Audio;1.0
[fresh  3491] [PPB] {full} ppb_get_interface interface_name=PPB_BrowserFont_Trusted;1.0
[fresh  3491] [PPB] {full} ppb_get_interface interface_name=PPB_Buffer(Dev);0.4
[fresh  3491] [PPB] {full} ppb_get_interface interface_name=PPB_CharSet(Dev);0.4
[fresh  3491] [PPB] {full} ppb_get_interface interface_name=PPB_Core;1.0
[fresh  3491] [PPB] {full} ppb_get_interface interface_name=PPB_Crypto(Dev);0.1
[fresh  3491] [PPB] {full} ppb_get_interface interface_name=PPB_CursorControl(Dev);0.4
[fresh  3491] [PPB] {full} ppb_get_interface interface_name=PPB_FileChooser(Dev);0.6
[fresh  3491] [PPB] {full} ppb_get_interface interface_name=PPB_FileChooserTrusted;0.6
[fresh  3491] [PPB] {full} ppb_get_interface interface_name=PPB_FileRef;1.0
[fresh  3491] [PPB] {full} ppb_get_interface interface_name=PPB_Flash_Clipboard;5.0
[fresh  3491] [PPB] {full} ppb_get_interface interface_name=PPB_Flash_File_FileRef;2
[fresh  3491] [PPB] {full} ppb_get_interface interface_name=PPB_Flash_File_ModuleLocal;3
[fresh  3491] [PPB] {full} ppb_get_interface interface_name=PPB_Flash_FontFile;0.1
[fresh  3491] [PPB] {full} ppb_get_interface interface_name=PPB_FlashFullscreen;1.0
[fresh  3491] [PPB] {full} ppb_get_interface interface_name=PPB_Flash;13.0
[fresh  3491] [PPB] {full} ppb_get_interface interface_name=PPB_Flash_Menu;0.2
[fresh  3491] [PPB] {full} ppb_get_interface interface_name=PPB_Graphics2D;1.0
[fresh  3491] [PPB] {full} ppb_get_interface interface_name=PPB_Graphics3D;1.0
[fresh  3491] [PPB] {full} ppb_get_interface interface_name=PPB_ImageData;1.0
[fresh  3491] [PPB] {full} ppb_get_interface interface_name=PPB_IMEInputEvent(Dev);0.2
[fresh  3491] [PPB] {full} ppb_get_interface interface_name=PPB_InputEvent;1.0
[fresh  3491] [PPB] {full} ppb_get_interface interface_name=PPB_Instance;1.0
[fresh  3491] [PPB] {full} ppb_get_interface interface_name=PPB_Memory(Dev);0.1
[fresh  3491] [PPB] {full} ppb_get_interface interface_name=PPB_NetAddress_Private;1.1
[fresh  3491] [PPB] {full} ppb_get_interface interface_name=PPB_OpenGLES2ChromiumMapSub;1.0
[fresh  3491] [PPB] {full} ppb_get_interface interface_name=PPB_OpenGLES2;1.0
[fresh  3491] [PPB] {full} ppb_get_interface interface_name=PPB_TCPSocket_Private;0.4
[fresh  3491] [PPB] {full} ppb_get_interface interface_name=PPB_TextInput(Dev);0.2
[fresh  3491] [PPB] {full} ppb_get_interface interface_name=PPB_UDPSocket_Private;0.4
[fresh  3491] [PPB] {full} ppb_get_interface interface_name=PPB_URLLoader;1.0
[fresh  3491] [PPB] {full} ppb_get_interface interface_name=PPB_URLLoaderTrusted;0.3
[fresh  3491] [PPB] {full} ppb_get_interface interface_name=PPB_URLRequestInfo;1.0
[fresh  3491] [PPB] {full} ppb_get_interface interface_name=PPB_URLResponseInfo;1.0
[fresh  3491] [PPB] {full} ppb_get_interface interface_name=PPB_URLUtil(Dev);0.7
[fresh  3491] [PPB] {full} ppb_get_interface interface_name=PPB_Vlibva info: VA-API version 0.37.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_37
libva info: va_openDriver() returns 0
[ERROR:flash/platform/pepper/common/pep_process.cpp(19)] CHECK(g_process_type == PROCESS_TYPE_UNKNOWN) failed
ar;1.1
[fresh  3491] [PPB] {full} ppb_get_interface interface_name=PPB_VideoCapture(Dev);0.3
[fresh  3491] [PPB] {full} ppb_get_interface interface_name=PPB_View;1.0
[fresh  3491] [PPB] {full} ppb_get_interface interface_name=PPB_URLLoaderTrusted;0.3
[fresh  3491]    returning from callback={.func=0x7f5c98a48340, .user_data=0x7f5d69f73100, .flags=0}, result=0, origin=call_plugin_init_module_prepare_comt
[fresh  3334] [NP] NP_GetValue instance=(nil), variable=NPPVpluginNameString, value=0x7f5d71d23cb8
[fresh  3334] [NP] NP_GetValue instance=(nil), variable=NPPVpluginDescriptionString, value=0x7f5d71d23cb8
[fresh  3334] [NP] NP_GetMIMEDescription
[fresh  3334] [NP] NP_Initialize aNPNFuncs=0x7f5d0b67f7e8, aNPPFuncs=0x7f5d0b67f748, browser API version = 19
[fresh  3334] libva version 0.37
[fresh  3334] libva driver vendor: Intel i965 driver for Intel(R) Ivybridge Mobile - 1.5.1
[fresh  3334] GLX version 1.4
[fresh  3334] screensavers found: fd.o-screensaver gnome-screensaver
[fresh  3334]    calling callback={.func=0x7f5c98a482e0, .user_data=0x7f5d6a043260, .flags=0}, result=0, origin=call_plugin_init_module
[fresh  3334]    returning from callback={.func=0x7f5c98a482e0, .user_data=0x7f5d6a043260, .flags=0}, result=0, origin=call_plugin_init_module
[fresh  3491]    calling callback={.func=0x7f5c98a48340, .user_data=0x7f5d6a043260, .flags=0}, result=0, origin=call_plugin_init_module_prepare_comt
```
> Do you have any special web page which opens when you start Eclipse?

Nope. I even deleted my old Eclipse profile, thinking it was a bug with Eclipse. So you can assume a 100% clean Eclipse setup.

> Just to clarify. Eclipse uses WebKit engine for internal browser. That engine have NPAPI plugins support, so it tries to load all available plugins (freshplayerplugin amongst them) when started.

I did understand this from the other thread, what I do think it's bizarre is the fact that when I installed freshplayer Eclipse stopped giving me it's own prints and the only output that I get is from the freshplayer plugin.

**Comment by i-rinat** [comment]
I can't see anything wrong in the log. But still it fails.

Perhaps, running under gdb to get backtrace would give more pointers?

**Comment by m45t3r** [comment]
How can I run gdb to help? I tried to connect to the Java process, it did not work really well (it seems Arch Linux is not a good distro to debug this kind of problems since the libraries are generally compiled without debugging symbols).

Anyway, now I discovered one easy way to trigger this bug: just try to auto-complete (pressing Ctrl+Spacebar) or anything that calls the internal helper from Eclipse. It seems this helper uses HTML, so it calls the internal browser, that triggers this bug.

**Comment by i-rinat** [comment]
You can try to run Eclipse from terminal, but before that, call `ulimit -c unlimited`. That will enable creation of `core` files at crash. Then you trigger the bug, close Eclipse (if still running), call `file core` to determine which executable crashed, then run `gdb /path/to/executable core`. In gdb prompt, call command `bt` and then `thread apply all bt`. Those will print backtrace of current thread and backtraces of all threads respectively.

I think, executable name will be either `/usr/lib/eclipse/eclipse` or `/usr/bin/java`. But it may be different on your machine.

**Comment by m45t3r** [comment]
Well, since I use systemd it seems that coredumpctl get all output from coredumps. So I did a ``coredumpt ctl`` and ``set logging on; thread apply all bt full``. Hope it is what you need.

https://gist.github.com/m45t3r/c867bd07f9f1615ed2d1

**Comment by i-rinat** [comment]
According to backtrace, PepperFlash calls its `PPP_InitializeModule` itself, which it very odd. But there is another wrong thing I didn't notice before: `NP_Initialize` was called twice, while it shouldn't be.

I've added a guard in 7243809dcbe8b2dac9695ee095367cc1ac2b40d4. Could you try again?

**Comment by m45t3r** [comment]
@i-rinat Yep, this seems to fix it. Tried to auto-complete and using Eclipse's help browser, no crashes this time.

**Comment by i-rinat** [comment]
OK, that's good.
