### ISSUE TITLE
does quirk_plasma5_screensaver work in KDE 4 Desktop Environment ?

### ISSUE THREAD

**Issue by redhatlinux10** [i-rinat/freshplayerplugin#212]
```
# method org.freedesktop.ScreenSaver.SimulateUserActivity() in KDE 5 seems
# to have no effect unless GetSessionIdleTime() called afterwards. Set
# parameter to 1 to call latter
quirk_plasma5_screensaver = 0
```
this configuration option is named with a keyword `plasma5` . i am wondering if this option works only for KDE5 ?

**Comment by i-rinat** [comment]
It was tested under Plasma 5. I don't know whenever it works in KDE 4.

Isn't usual `SimulateUserActivity` alone enough in KDE 4?

**Comment by redhatlinux10** [comment]
>Isn't usual SimulateUserActivity alone enough in KDE 4?

yes it is. i am using KDE4 and i wrote a script using `SimulateUserActivity` to block screensaver.
do you mean blocking screensaver function has been already built in `freshpluginplayer` in KDE 4 ?

**Comment by i-rinat** [comment]
[There is](https://github.com/i-rinat/freshplayerplugin/blob/master/src/screensaver_control.c) support for different screen saver inhibition interfaces. KDE 4 is amongst them.

You can test it by setting screen saver timeout to one minute. First, wait for a minute to ensure screen saver starts after a minute of inactivity. Then try to launch video from Youtube, and wait for another could of minutes. Screen saver shouldn't start while video is playing.

**Comment by redhatlinux10** [comment]
i wanna try, but there seems to be no any related configurations with *screensaver timeout*  in `freshwrapper.conf` file.  file [screensaver_control.c](https://github.com/i-rinat/freshplayerplugin/blob/master/src/screensaver_control.c) also don't read any `config.XXX` configurations except `config.quirks.plasma5_screensaver`

please tell me how to set *screensaver timeout* ,thanks.

**Comment by i-rinat** [comment]
> screensaver timeout

I meant KDE 4 setting.

**Comment by redhatlinux10** [comment]
yes, it works. thanks again.
