### ISSUE TITLE
[distro-related] HW Decoding in older Ubuntu version

### ISSUE THREAD

**Issue by ItachiSan** [i-rinat/freshplayerplugin#215]
As hardware accelleration works (see issue #24), I want to make it avaible on my Ubuntu Precise 12.04 LTS.
I still use this distro for cooking Android ROMs and I usually watch Youtube video while waiting, so I need hardware accelleration to make Ubuntu survive all of this! :P

So, this issue is **distro-related** and about **packagin**, in order to find out which packages are needed to make everything work fine.

**Comment by ItachiSan** [comment]
I already backported some packages, as you can see here: https://launchpad.net/~itachi-san/+archive/ubuntu/ffmpeg
Now, I am on *libav* **11.2**.
While trying to open a Youtube video, I have back as reply:
```
itachisan@android-builder-ubuntu:~$ firefox 
libva: VA-API version 0.32.0
libva: va_getDriverName() returns 0
libva: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva: va_openDriver() returns 0
Failed to open VDPAU backend libvdpau_i965.so: impossibile aprire il file oggetto condiviso: File o directory non esistente
NOT SANDBOXED
[fresh  2864] not implemented: PPB_OpenGLES2VertexArrayObject;1.0
[fresh  2864] not implemented: PPB_OpenGLES2DrawBuffers(Dev);1.0
[fresh  2864] [PPB] {zilch} ppb_network_monitor_update_network_list
[fresh  2864] [PPB] {zilch} ppb_flash_set_instance_always_on_top instance=11, on_top=1
[fresh  2864] [PPB] {zilch} ppb_network_monitor_update_network_list
[fresh  2864] [PPB] {zilch} ppb_network_monitor_update_network_list
[fresh  2864] [PPB] {zilch} ppb_network_monitor_update_network_list
```

**Comment by i-rinat** [comment]
> I have back as reply

Looks fine. `libva` lines are printed by libva.so. They tell us driver was loaded.
"Failed to open VDPAU backend" is printed by libvdpau.so, and tells that it tried to load `libvdpau_i965.so` driver, but there is no such driver, so VDPAU won't be available.

What matters is whenever hwdec is actually working. I guess when it doesn't work, you'll get some error messages in output.

Other thing you can try is to configure with `cmake -DTRACE_ALL=1 ..` and build again. Freshwrapper then print a lot of tracing information, which you can collect into a file, and then search there "ppb_video_decoder" string. If hwdec is working, there will be a lot of `ppb_video_decoder_decode` calls.

**Comment by ItachiSan** [comment]
I recompiled the deb package using the TRACE_ALL flag and I noticed something strange...
```
...
[fresh 29440]    calling callback={.func=0x7fae0f370a10, .user_data=0x7fae06787f40, .flags=0}, result=0, origin=ppb_core_call_on_main_thread
[fresh 29440] [PPB] {full} ppb_get_interface interface_name=PPB_VideoDecoder(Dev);0.16
[fresh 29440] [PPB] {full} ppb_video_decoder_create instance=11, context=13, profile=PP_VIDEODECODER_H264PROFILE_MAIN
[fresh 29440]       hardware-accelerated decoding was disabled in config file
[fresh 29440]    returning from callback={.func=0x7fae0f370a10, .user_data=0x7fae06787f40, .flags=0}, result=0, origin=ppb_core_call_on_main_thread
...
``` 

My actual configurazion file is: http://paste.ubuntu.com/11762222/
The full log: http://paste.ubuntu.com/11762240/

**Comment by i-rinat** [comment]
Oh, I see.
Ubuntu 12 have old version of libconfig. Then it was required for every statement to have semicolon at the end. And type requirements were strict. To make code compile against both libconfig8 and libconfig9, I'm using 64-bit integers for boolean flags. Thus numbers should also have `L` postfix, like in C language. So you need to make config look like:
```
enable_hwdec = 1L;
enable_vaapi = 1L;
```

**Comment by ItachiSan** [comment]
I still have
```
[fresh  4667] [PPB] {full} ppb_get_interface interface_name=PPB_VideoDecoder(Dev);0.16
[fresh  4667] [PPB] {full} ppb_video_decoder_create instance=11, context=13, profile=PP_VIDEODECODER_H264PROFILE_MAIN
[fresh  4667]       hardware-accelerated decoding was disabled in config file
```
Now my configuration is: http://paste.ubuntu.com/11762467/
Actually, I setted also `enable_3d = 1L;` but that made video loading stucks, so I resetted the value to 1

**Comment by i-rinat** [comment]
I'm not sure how older libconfig will handle other settings — they don't have trailing `;`.
I would be better to leave in config file only one line:
```
enable_hwdec = 1L;
```

**Comment by ItachiSan** [comment]
I couldn't remove the other lines, as I need them... I just had to add trailing to all of them :P
So, with this configuration: http://paste.ubuntu.com/11762652/
Hardware decoding works fine:
![schermata del 2015-06-23 17 08 47](https://cloud.githubusercontent.com/assets/1223421/8309401/bc131d52-19ca-11e5-9f59-d1573df980d9.png)
Maybe trailing colons could be added to the default configuration file. ;)

**Comment by i-rinat** [comment]
> I couldn't remove the other lines, as I need them

Almost all of the settings (except `enable_hwdec`) have default values. Path "/usr/lib/pepflashplugin-installer/libpepflashplayer.so" is tested if you remove `pepperflash_path` key from the file. And I don't know whenever `flash_command_line` have any effect at all.

**Comment by i-rinat** [comment]
> Maybe trailing colons could be added to the default configuration file. ;)

They add noise.

**Comment by ItachiSan** [comment]
Really? Times ago it didn't work... :/
So, final configuration (working) with comments here: http://paste.ubuntu.com/11762963/
Sorry, I just had to add all the comments, I hate writing things with no informations ^^"
I'm closing this issue, thanks for the support!

**Comment by i-rinat** [comment]
> Times ago it didn't work

That path was added recently, in 49224050fd1812321373ff27ec3dd0bebcffb8b7.

> Sorry, I just had to add all the comments

Why are you sorry? It's you configuration file, on your machine. You can do with it  anything you want. :smile:

**Comment by ItachiSan** [comment]
That's right ahahah :D
Probably I'll write a post somewhere so people won't have problems ;)
