### ISSUE TITLE
[Suggestion - Proposal] Make a daily/weekly build PPA

### ISSUE THREAD

**Issue by ItachiSan** [i-rinat/freshplayerplugin#218]
I'm opening this issue as I would be interested in trying to create a daily/weekly build PPA of the package.
This does not mean I'll be able to do it (it would be my first try) but I would like to do it, so I'm opening this issue for the following reason:
* Asking permission for doing it (even if this is licensed under MIT, I am used to ask :P)
* Asking permission for making an automatic code clone on Launchpad, needed for building from Git repo (see above why I'm asking :D)
* Keeping track of this issue, obviously ;)

**Comment by i-rinat** [comment]
> Asking permission for doing it (even if this is licensed under MIT, I am used to ask :P)

Yep, sure you can do it. That's the whole idea of sharing code under open license, isn't it?

By the way, Github Terms of Service have a line "By setting your repositories to be viewed publicly, you agree to allow others to view and fork your repositories" which enables you to fork or clone any public repository regardless of its license.

> Asking permission for making an automatic code clone on Launchpad, needed for building from Git repo

If that was requiring permission (but it is not), it's Github one should ask from. I have nothing against cloning the repository.

**Comment by ItachiSan** [comment]
> We claim no intellectual property rights over the material you provide to the Service. Your profile and materials uploaded remain yours. However, by setting your pages to be viewed publicly, you agree to allow others to view your Content. By setting your repositories to be viewed publicly, you agree to allow  others to view and fork your repositories.

They don't say *limited to Github*, so I suppose it is fine. :smile: 
And, I told you, I (almost) always ask :wink:

**Comment by ItachiSan** [comment]
Project created on Launchpad: https://launchpad.net/fresh-player-plugin
I couldn't use *https://launchpad.net/freshplayerplugin* as it was already taken... nevermind.
Later I will try some packaging.

**Comment by ItachiSan** [comment]
Let's give this a try:
https://code.launchpad.net/~itachi-san/+recipe/fresh-player-plugin-daily
Actually, building on my laptop worked, so I expect it will work on Launchpad builders too.

Still, I'm asking myself which is the minimum libav/ffmpeg version for VA-API support; so I know if I've to rebuild *libav* for **trusty**

**Comment by ItachiSan** [comment]
Actually, builds works fine.
@i-rinat I would like to know which is the minimum *libav* version needed for **VA-API**, so I can backport it to ***trusty*** if needed :smile:

**Comment by i-rinat** [comment]
> the minimum libav version needed for VA-API

I honestly don't know, and it's hard to find exact version. VA-API support was added to ffmpeg long ago, and not even mentioned in `doc/APIchanges`.  Somewhere about 2009, I think.

I tested VA-API decode successfully on Debian Wheezy, which have libav 0.8.17.  As far as I know, Ubuntu Precise have the same libav version. So it should work there too.
