### ISSUE TITLE
Firefox suddenly fails to detect libfreshwrapper-pepperflash.so

### ISSUE THREAD

**Issue by Rewarp** [i-rinat/freshplayerplugin#220]
I installed freshplayer via the openSUSE repositories, and without doing anythign else, all the plugins were loaded automatically, without hassle.

For some reason, Firefox suddenly fails to detect libfreshwrapper-pepperflash.so. I checked the folder in

>/usr/lib64/browser-plugins

And the following plugins are in here:

>javaplugin.so      libfreshwrapper-libpdf.so  libfreshwrapper-pepperflash.so  skypebuttons.so
libflashplayer.so  libfreshwrapper-nacl.so    packagekit-plugin.so

The "normal" Flash is the one being loaded now. How do I get Firefox to enable Pepper Flash again?

**Comment by i-rinat** [comment]
Firefox caches plugin information in `pluginreg.dat` file. Sometimes it decides that plugin doesn't work, marks it as non-working, and then doesn't even try to load.

You can either remove `pluginreg.dat` file, or update `libfreshwrapper-pepperflash.so` file timestamp. First file is located in profile directory somewhere in `~/.mozilla` — Firefox supports multiple profiles, so exact path could vary. Latter could be done by calling `touch libfreshwrapper-pepperflash.so` in the directory where `libfreshwrapper-pepperflash.so` is.

**Comment by i-rinat** [comment]
It's also worth to examine output of `ldd -r libpepflashplayer.so` and `ldd -r libfreshwrapper-pepperflash.so`. Those commands try to check all libraries dependencies. Some recent versions of PepperFlash from ChromeOS require libstdc++ from GCC 4.9, while many distributions are using 4.8 or older. So that may be the case.

(Commands require full path, so one need either call them at the very directory or use a full path.)

**Comment by Rewarp** [comment]
Thanks. It worked as soon as I ran ````touch libfreshwrapper-pepperflash.so````

Here's my output from the ldd commands, just in case you can help me make sense of them. I don't know what's wrong from reading my output.

**libfreshwrapper-pepperflash.so**
>io:/usr/lib64/browser-plugins # ldd -r libfreshwrapper-pepperflash.so 
        linux-vdso.so.1 (0x00007ffce9dcc000)
        libasound.so.2 => /usr/lib64/libasound.so.2 (0x00007f813fe80000)
        libgio-2.0.so.0 => /usr/lib64/libgio-2.0.so.0 (0x00007f813fb09000)
        libXrandr.so.2 => /usr/lib64/libXrandr.so.2 (0x00007f813f8fe000)
        libXrender.so.1 => /usr/lib64/libXrender.so.1 (0x00007f813f6f4000)
        libX11.so.6 => /usr/lib64/libX11.so.6 (0x00007f813f3b6000)
        libXcursor.so.1 => /usr/lib64/libXcursor.so.1 (0x00007f813f1aa000)
        libGL.so.1 => /usr/lib64/libGL.so.1 (0x00007f813ef1a000)
        libconfig.so.9 => /usr/lib64/libconfig.so.9 (0x00007f813ed0e000)
        libevent_pthreads-2.0.so.5 => /usr/lib64/libevent_pthreads-2.0.so.5 (0x00007f813eb0a000)
        libevent-2.0.so.5 => /usr/lib64/libevent-2.0.so.5 (0x00007f813e8c1000)
        libpangocairo-1.0.so.0 => /usr/lib64/libpangocairo-1.0.so.0 (0x00007f813e6b4000)
        libcairo.so.2 => /usr/lib64/libcairo.so.2 (0x00007f813e391000)
        libpangoft2-1.0.so.0 => /usr/lib64/libpangoft2-1.0.so.0 (0x00007f813e17d000)
        libpango-1.0.so.0 => /usr/lib64/libpango-1.0.so.0 (0x00007f813df32000)
        libgobject-2.0.so.0 => /usr/lib64/libgobject-2.0.so.0 (0x00007f813dce0000)
        libglib-2.0.so.0 => /usr/lib64/libglib-2.0.so.0 (0x00007f813d9d2000)
        libfreetype.so.6 => /usr/lib64/libfreetype.so.6 (0x00007f813d73b000)
        libcrypto.so.1.0.0 => /lib64/libcrypto.so.1.0.0 (0x00007f813d317000)
        libv4l2.so.0 => /usr/lib64/libv4l2.so.0 (0x00007f813d109000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f813cf05000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f813ccfc000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f813c9fb000)
        libgtk-3.so.0 => /usr/lib64/libgtk-3.so.0 (0x00007f813c148000)
        libgdk-3.so.0 => /usr/lib64/libgdk-3.so.0 (0x00007f813be8e000)
        libpulse.so.0 => /usr/lib64/libpulse.so.0 (0x00007f813bc42000)
        libjack.so.0 => /usr/lib64/libjack.so.0 (0x00007f813b9fa000)
        libsoxr.so.0 => /usr/lib64/libsoxr.so.0 (0x00007f813b7be000)
        libavcodec.so.56 => /usr/lib64/libavcodec.so.56 (0x00007f813a6ce000)
        libavutil.so.54 => /usr/lib64/libavutil.so.54 (0x00007f813a46f000)
        libva-x11.so.1 => /usr/lib64/libva-x11.so.1 (0x00007f813a268000)
        libva.so.1 => /usr/lib64/libva.so.1 (0x00007f813a051000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f8139e34000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f8139a8c000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f8140440000)
        libgmodule-2.0.so.0 => /usr/lib64/libgmodule-2.0.so.0 (0x00007f8139888000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f8139672000)
        libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f813944d000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f8139236000)
        libXext.so.6 => /usr/lib64/libXext.so.6 (0x00007f8139024000)
        libxcb.so.1 => /usr/lib64/libxcb.so.1 (0x00007f8138e03000)
        libXfixes.so.3 => /usr/lib64/libXfixes.so.3 (0x00007f8138bfd000)
        libexpat.so.1 => /usr/lib64/libexpat.so.1 (0x00007f81389d3000)
        libglapi.so.0 => /usr/lib64/libglapi.so.0 (0x00007f81387a8000)
        libXdamage.so.1 => /usr/lib64/libXdamage.so.1 (0x00007f81385a5000)
        libX11-xcb.so.1 => /usr/lib64/libX11-xcb.so.1 (0x00007f81383a3000)
        libxcb-glx.so.0 => /usr/lib64/libxcb-glx.so.0 (0x00007f813818a000)
        libxcb-dri2.so.0 => /usr/lib64/libxcb-dri2.so.0 (0x00007f8137f85000)
        libxcb-dri3.so.0 => /usr/lib64/libxcb-dri3.so.0 (0x00007f8137d82000)
        libxcb-present.so.0 => /usr/lib64/libxcb-present.so.0 (0x00007f8137b7e000)
        libxcb-sync.so.1 => /usr/lib64/libxcb-sync.so.1 (0x00007f8137978000)
        libxshmfence.so.1 => /usr/lib64/libxshmfence.so.1 (0x00007f8137775000)
        libXxf86vm.so.1 => /usr/lib64/libXxf86vm.so.1 (0x00007f813756e000)
        libdrm.so.2 => /usr/lib64/libdrm.so.2 (0x00007f8137362000)
        libfontconfig.so.1 => /usr/lib64/libfontconfig.so.1 (0x00007f8137123000)
        libpixman-1.so.0 => /usr/lib64/libpixman-1.so.0 (0x00007f8136e78000)
        libEGL.so.1 => /usr/lib64/libEGL.so.1 (0x00007f8136c50000)
        libpng16.so.16 => /usr/lib64/libpng16.so.16 (0x00007f8136a12000)
        libxcb-shm.so.0 => /usr/lib64/libxcb-shm.so.0 (0x00007f813680f000)
        libxcb-render.so.0 => /usr/lib64/libxcb-render.so.0 (0x00007f8136605000)
        libharfbuzz.so.0 => /usr/lib64/libharfbuzz.so.0 (0x00007f81363ab000)
        libffi.so.4 => /usr/lib64/libffi.so.4 (0x00007f81361a3000)
        libpcre.so.1 => /usr/lib64/libpcre.so.1 (0x00007f8135f37000)
        libv4lconvert.so.0 => /usr/lib64/libv4lconvert.so.0 (0x00007f8135cbd000)
        libXi.so.6 => /usr/lib64/libXi.so.6 (0x00007f8135aad000)
        libcairo-gobject.so.2 => /usr/lib64/libcairo-gobject.so.2 (0x00007f81358a3000)
        libgdk_pixbuf-2.0.so.0 => /usr/lib64/libgdk_pixbuf-2.0.so.0 (0x00007f8135681000)
        libatk-1.0.so.0 => /usr/lib64/libatk-1.0.so.0 (0x00007f813545b000)
        libatk-bridge-2.0.so.0 => /usr/lib64/libatk-bridge-2.0.so.0 (0x00007f813522c000)
        libXinerama.so.1 => /usr/lib64/libXinerama.so.1 (0x00007f8135029000)
        libXcomposite.so.1 => /usr/lib64/libXcomposite.so.1 (0x00007f8134e26000)
        libwayland-client.so.0 => /usr/lib64/libwayland-client.so.0 (0x00007f8134c17000)
        libxkbcommon-0.4.3.so => /usr/lib64/libxkbcommon-0.4.3.so (0x00007f81349db000)
        libwayland-cursor.so.0 => /usr/lib64/libwayland-cursor.so.0 (0x00007f81347d3000)
        libpulsecommon-5.0.so => /usr/lib64/pulseaudio/libpulsecommon-5.0.so (0x00007f813455d000)
        libjson-c.so.2 => /usr/lib64/libjson-c.so.2 (0x00007f8134352000)
        libdbus-1.so.3 => /lib64/libdbus-1.so.3 (0x00007f813410a000)
        libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007f8133e02000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f8133beb000)
        libgomp.so.1 => /usr/lib64/libgomp.so.1 (0x00007f81339db000)
        libswresample.so.1 => /usr/lib64/libswresample.so.1 (0x00007f81337c1000)
        libvpx.so.1 => /usr/lib64/libvpx.so.1 (0x00007f81333e0000)
        libvorbisenc.so.2 => /usr/lib64/libvorbisenc.so.2 (0x00007f8133136000)
        libvorbis.so.0 => /usr/lib64/libvorbis.so.0 (0x00007f8132f08000)
        libtheoraenc.so.1 => /usr/lib64/libtheoraenc.so.1 (0x00007f8132cc8000)
        libtheoradec.so.1 => /usr/lib64/libtheoradec.so.1 (0x00007f8132aae000)
        libspeex.so.1 => /usr/lib64/libspeex.so.1 (0x00007f8132895000)
        libschroedinger-1.0.so.0 => /usr/lib64/libschroedinger-1.0.so.0 (0x00007f81325cb000)
        libopus.so.0 => /usr/lib64/libopus.so.0 (0x00007f813237f000)
        libopenjpeg.so.1 => /usr/lib64/libopenjpeg.so.1 (0x00007f8132156000)
        libgsm.so.1 => /usr/lib64/libgsm.so.1 (0x00007f8131f4a000)
        libXau.so.6 => /usr/lib64/libXau.so.6 (0x00007f8131d45000)
        libxcb-xfixes.so.0 => /usr/lib64/libxcb-xfixes.so.0 (0x00007f8131b3e000)
        libgbm.so.1 => /usr/lib64/libgbm.so.1 (0x00007f813192f000)
        libwayland-server.so.0 => /usr/lib64/libwayland-server.so.0 (0x00007f813171d000)
        libgraphite2.so.3 => /usr/lib64/libgraphite2.so.3 (0x00007f81314ff000)
        libjpeg.so.8 => /usr/lib64/libjpeg.so.8 (0x00007f81312aa000)
        libatspi.so.0 => /usr/lib64/libatspi.so.0 (0x00007f8131079000)
        libsystemd.so.0 => /usr/lib64/libsystemd.so.0 (0x00007f813104c000)
        libsndfile.so.1 => /usr/lib64/libsndfile.so.1 (0x00007f8130de0000)
        libogg.so.0 => /usr/lib64/libogg.so.0 (0x00007f8130bd9000)
        liborc-0.4.so.0 => /usr/lib64/liborc-0.4.so.0 (0x00007f8130956000)
        liblzma.so.5 => /usr/lib64/liblzma.so.5 (0x00007f8130730000)
        libgcrypt.so.20 => /usr/lib64/libgcrypt.so.20 (0x00007f813044b000)
        libgpg-error.so.0 => /usr/lib64/libgpg-error.so.0 (0x00007f813023a000)
        libFLAC.so.8 => /usr/lib64/libFLAC.so.8 (0x00007f812fffb000)

**Chromium's libpepflashplayer.so**
>io:/usr/lib64/browser-plugins # ldd -r /usr/lib64/chromium/PepperFlash/libpepflashplayer.so
        linux-vdso.so.1 (0x00007ffd9c3a8000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007fe85c920000)
        librt.so.1 => /lib64/librt.so.1 (0x00007fe85c718000)
        libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007fe85c40f000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fe85c10e000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fe85bef7000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fe85bcd9000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fe85b932000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fe85dee1000)

**Chrome's libpepflashplayer.so**
>io:/usr/lib64/browser-plugins # ldd -r /opt/google/chrome/PepperFlash/libpepflashplayer.so 
        linux-vdso.so.1 (0x00007fffefff6000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007fe99418f000)
        librt.so.1 => /lib64/librt.so.1 (0x00007fe993f87000)
        libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007fe993c7e000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fe99397d000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fe993766000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fe993548000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fe9931a1000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fe995750000)

**Comment by i-rinat** [comment]
There is nothing wrong in `ldd` output. As long as you see nothing like "=> not found", every dependency is on its place.

I don't know the reason, but sometimes Firefox just decides it doesn't want to deal with a particular plugin anymore and caches negative result in `pluginreg.dat`. Exact algorithm is unknown to me, but I assume browser could blacklist a plugin if it took too long to load.

**Comment by Rewarp** [comment]
Great. Thanks for your help on the matter. :+1:
