### ISSUE TITLE
video garbbled up with VAAPI on some sites

### ISSUE THREAD

**Issue by beew** [i-rinat/freshplayerplugin#221]
Hi,

OS is Ubuntu 15.04 64 bit. Intel graphic card (ironlake mobile) freshplayer compiled with cmake DCMAKE_BUILD_TYPE=RelWithDebInfo -DWITH_HWDEC=1 -DWITH_GLES2=0 .. 

In my config file
enable_hwdec = 1, enable_ vaapi = 1, enable_windowed_mode =0, enable_vdpau=0

Videos on some sites (most are fine)  would run normally for a few seconds in fullscreen, then freezes, after exiting fullscreen it unfreezes and then become garbled, the image just completely breaks up into horizontal flashing strips, this will persist even loading the video. 

For examples  http://www.cp24.com/ http://toronto.ctvnews.ca/video. Running Firefox from terminal and visit the first one produces the following

(process:14029): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
console.error: hola_firefox_ext: 
  load reason startup
console.error: hola_firefox_ext: 
  DEPRECATED: Both `sdk/content/content` and `sdk/deprecated/symbiont` are deprecated. `sdk/core/heritage` supersedes Symbiont for inheritance.
Traceback (most recent call last):
  File "resource://jid1-4p0kohsjxu1qgg-at-jetpack/hola_firefox_ext/lib/api.js", line 1242, in E.create_background
    new Worker('bg', symbiont.Symbiont(opt), {hidden_frame: hf});
  File "resource://gre/modules/commonjs/sdk/content/content.js", line 21, in .get
    deprecateUsage('Both `sdk/content/content` and `sdk/deprecated/symbiont` are deprecated. ' +
  File "resource://gre/modules/commonjs/sdk/util/deprecate.js", line 18, in deprecateUsage
    let stack = get().slice(2);
console.error: hola_firefox_ext: 
  DEPRECATED: The widget module is deprecated.  Please consider using the sdk/ui module instead.
Traceback (most recent call last):
  File "resource://jid1-4p0kohsjxu1qgg-at-jetpack/hola_firefox_ext/lib/api.js", line 1299, in E.create_popup
    E.browserAction.init({default_icon: 'img/icon19_gray.png',
  File "resource://jid1-4p0kohsjxu1qgg-at-jetpack/hola_firefox_ext/lib/api.js", line 553, in E.browserAction.init
    ba = baction(opt);
  File "resource://jid1-4p0kohsjxu1qgg-at-jetpack/browser-action/lib/browserAction.js", line 334, in Badge
    let tbw = createBadge(browserAction, badgeState);
  File "resource://jid1-4p0kohsjxu1qgg-at-jetpack/browser-action/lib/browserAction.js", line 210, in createBadge
    var tbw = require('toolbarwidget').ToolbarWidget({
  File "resource://jid1-4p0kohsjxu1qgg-at-jetpack/toolbarwidget/lib/toolbarwidget.js", line 343, in exports.ToolbarWidget
    let sdkWidget = require('sdk/widget').Widget(options);
  File "resource://gre/modules/commonjs/toolkit/loader.js", line 604, in require
    freeze(load(loader, module));
  File "resource://gre/modules/commonjs/sdk/loader/cuddlefish.js", line 79, in CuddlefishLoader/options<.load
    result = load(loader, module);
  File "resource://gre/modules/commonjs/toolkit/loader.js", line 323, in load
    evaluate(sandbox, module.uri);
  File "resource://gre/modules/commonjs/toolkit/loader.js", line 271, in evaluate
    : loadSubScript(uri, sandbox, encoding);
  File "resource://gre/modules/commonjs/sdk/widget.js", line 59, in null
    require("./util/deprecate").deprecateUsage(
  File "resource://gre/modules/commonjs/sdk/util/deprecate.js", line 18, in deprecateUsage
    let stack = get().slice(2);
console.error: hola_firefox_ext: 
  2015-06-30 04:36:17.967 ERROR: perr be_mode_change info: {"new_mode":"ext"}
console.error: hola_firefox_ext: 
  2015-06-30 04:36:17.997 ERROR: rmt_init %s
  9975ms r 8376ms
libva info: VA-API version 0.38.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_38
libva info: va_openDriver() returns 0
NOT SANDBOXED
[fresh 14107] not implemented: PPB_OpenGLES2VertexArrayObject;1.0
[fresh 14107] not implemented: PPB_OpenGLES2DrawBuffers(Dev);1.0
[fresh 14107] [PPB] {zilch} ppb_network_monitor_update_network_list

(plugin-container:14103): GLib-CRITICAL **: g_variant_get_boolean: assertion 'g_variant_is_of_type (value, G_VARIANT_TYPE_BOOLEAN)' failed

(plugin-container:14103): GLib-CRITICAL **: g_variant_get_boolean: assertion 'g_variant_is_of_type (value, G_VARIANT_TYPE_BOOLEAN)' failed

(plugin-container:14103): GLib-CRITICAL **: g_variant_get_boolean: assertion 'g_variant_is_of_type (value, G_VARIANT_TYPE_BOOLEAN)' failed
[fresh] [error] execute_script_ptac, NPN_Evaluate failed
[fresh] [error] execute_script_ptac, NPN_Evaluate failed
[fresh] [error] execute_script_ptac, NPN_Evaluate failed
[fresh] [error] execute_script_ptac, NPN_Evaluate failed
[fresh] [error] execute_script_ptac, NPN_Evaluate failed
[fresh] [error] execute_script_ptac, NPN_Evaluate failed
[fresh] [error] execute_script_ptac, NPN_Evaluate failed

Also, for all sites, when  switching from fullscreen to regular screen the video freezes for a long duration with only audio and then unfreezes.

**Comment by beew** [comment]
P.S Once this happened subsequent videos on other sites break up as well even when they were working before.

For example. www.ted.com works. Then visit www.cp24.com, video freezes and breakup. Then close tab and go to www.ted.com again and now the videos breaks up into flashing strips too. Restart firefox then it works for www.ted.com again.

**Comment by i-rinat** [comment]
Hardware decoders are very fragile.

I saw what you described during libvdpau-va-gl development. Any wrong parameter could cause whole system freeze. But in this project I use ffmpeg for all low-level management, it works fine on my machine (with occasional glitches during video seeking), so I guess the issue is hardware/driver-related.

Ubuntu Vivid have i965-va-driver 1.5.0, while 1.5.1 (and 1.6.0.pre2) already available. Try to update driver, perhaps that would help.

**Comment by beew** [comment]
Actually I was using 1.6.0 pre1. Now downgraded back to 1.5.0 and same problem persists.

**Comment by i-rinat** [comment]
Looks like it either hardware- or driver-related issue. I can't fix it; don't have enough skills for that.

**Comment by i-rinat** [comment]
There was a bug with task reordering which could result in broken bitstream passed to a video decoder, which in turn resulted in broken video (#307). Fix was pushed in 7ba5f2de0e7a8b6f6bbb1e66abab86300dcc4db9.
