### ISSUE TITLE
Crashes when trying creating album on Facebook

### ISSUE THREAD

**Issue by lashkevi** [i-rinat/freshplayerplugin#222]
Version 0.3.0 hangs and after a minute or so crashes, when I press the button "Create photoalbum" on Facebook. I use freshplayerplugin-0.3.0-3.1.x86_64 and chromium-pepper-flash-18.0.0.160-1.1.x86_64 from Packman repository on OpenSUSE-13.1. I tried other versions and repositories, but all of them invariably crash after I upgraded to these versions (I cannot simply downgrade to previous versions since my filesystem is not btrfs, and older versions are not available on repositories).

**Comment by i-rinat** [comment]
Hi. I've tried to repeat the steps several time, and also the same under Valgrind. Works fine, so we have something different on our machines.

Have you tried recent version from git repository? Does it hang too? If yes, increase value of `dom.ipc.plugins.timeoutSecs` parameter (in Firefox, on `about:config` page) to larger value. Default 45 seconds is not enough to make backtrace with gdb, but 3600 seconds, one hour, would be enough.

Then try the same steps, so plugin hangs. Launch in terminal emulator:
```
gdb --pid `pidof plugin-container`
```
and in gdb prompt, type command `thread apply all bt`. That will print backtraces of all threads. Output will be multiple screens long, you need to press Enter when it asks for. After than you can quit gdb either by entering command `quit` or by pressing Ctrl-D. I need that printout to figure out where interlock occurs.

**Comment by lashkevi** [comment]
I did not try to compile the latest version, but here is the debugging output for the binary package I have installed (together with the debuginfo package):

Thread 12 (Thread 0x7f8727c2c700 (LWP 21269)):
#0  0x00007f8733ca1bf9 in syscall () from /lib64/libc.so.6
#1  0x00007f873548b644 in epoll_wait () from /usr/lib64/firefox/libxul.so
#2  0x00007f873548b4ac in ?? () from /usr/lib64/firefox/libxul.so
#3  0x00007f873548ca92 in ?? () from /usr/lib64/firefox/libxul.so
#4  0x00007f8735490833 in ?? () from /usr/lib64/firefox/libxul.so
#5  0x00007f8735496791 in ?? () from /usr/lib64/firefox/libxul.so
#6  0x00007f873549ce82 in ?? () from /usr/lib64/firefox/libxul.so
#7  0x00007f8735490cb3 in ?? () from /usr/lib64/firefox/libxul.so
#8  0x00007f87391750db in start_thread () from /lib64/libpthread.so.0
#9  0x00007f8733ca5ddd in clone () from /lib64/libc.so.6

Thread 11 (Thread 0x7f8725c3b700 (LWP 21272)):
#0  0x00007f8733c9d00d in poll () from /lib64/libc.so.6
#1  0x00007f87309f4604 in ?? () from /usr/lib64/libglib-2.0.so.0
#2  0x00007f87309f4a6a in g_main_loop_run () from /usr/lib64/libglib-2.0.so.0
#3  0x00007f872feafc16 in ?? () from /usr/lib64/libgio-2.0.so.0
#4  0x00007f8730a19035 in ?? () from /usr/lib64/libglib-2.0.so.0
#5  0x00007f87391750db in start_thread () from /lib64/libpthread.so.0
#6  0x00007f8733ca5ddd in clone () from /lib64/libc.so.6

Thread 10 (Thread 0x7f872543a700 (LWP 21273)):
#0  0x00007f8733c9d00d in poll () from /lib64/libc.so.6
#1  0x00007f87309f4604 in ?? () from /usr/lib64/libglib-2.0.so.0
#2  0x00007f87309f470c in g_main_context_iteration () from /usr/lib64/libglib-2.0.so.0
#3  0x00007f87309f4759 in ?? () from /usr/lib64/libglib-2.0.so.0
#4  0x00007f8730a19035 in ?? () from /usr/lib64/libglib-2.0.so.0
#5  0x00007f87391750db in start_thread () from /lib64/libpthread.so.0
#6  0x00007f8733ca5ddd in clone () from /lib64/libc.so.6

Thread 9 (Thread 0x7f871efdf700 (LWP 21274)):
#0  0x00007f8739179458 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00007f8730a345f5 in g_cond_wait_until () from /usr/lib64/libglib-2.0.so.0
#2  0x00007f87309caa71 in ?? () from /usr/lib64/libglib-2.0.so.0
#3  0x00007f87309caffb in g_async_queue_timeout_pop () from /usr/lib64/libglib-2.0.so.0
#4  0x00007f87248946d8 in ppb_message_loop_run_int () from /usr/lib64/browser-plugins/libfreshwrapper-pepperflash.so
#5  0x00007f8724894278 in ppb_message_loop_run_nested () from /usr/lib64/browser-plugins/libfreshwrapper-pepperflash.so
#6  0x00007f87248a5385 in ppb_url_loader_open_target () from /usr/lib64/browser-plugins/libfreshwrapper-pepperflash.so
#7  0x00007f87248a4e25 in ppb_url_loader_open () from /usr/lib64/browser-plugins/libfreshwrapper-pepperflash.so
#8  0x00007f871e0b12fa in ?? () from /usr/lib64/chromium/PepperFlash/libpepflashplayer.so
#9  0x00007f871d66f06b in ?? () from /usr/lib64/chromium/PepperFlash/libpepflashplayer.so
#10 0x00007f871d65b26e in ?? () from /usr/lib64/chromium/PepperFlash/libpepflashplayer.so
#11 0x00007f871d9d0507 in ?? () from /usr/lib64/chromium/PepperFlash/libpepflashplayer.so
#12 0x00007f871da55bad in ?? () from /usr/lib64/chromium/PepperFlash/libpepflashplayer.so
#13 0x00007f871db67a8e in ?? () from /usr/lib64/chromium/PepperFlash/libpepflashplayer.so
#14 0x00007f871da3f6d1 in ?? () from /usr/lib64/chromium/PepperFlash/libpepflashplayer.so
#15 0x00007f871da6e4d6 in ?? () from /usr/lib64/chromium/PepperFlash/libpepflashplayer.so
#16 0x00007f871da6e795 in ?? () from /usr/lib64/chromium/PepperFlash/libpepflashplayer.so
#17 0x00007f871d64b669 in ?? () from /usr/lib64/chromium/PepperFlash/libpepflashplayer.so
#18 0x00007f871d66e2a3 in ?? () from /usr/lib64/chromium/PepperFlash/libpepflashplayer.so
#19 0x00007f871d66e59b in ?? () from /usr/lib64/chromium/PepperFlash/libpepflashplayer.so
#20 0x00007f8724894697 in ppb_message_loop_run_int () from /usr/lib64/browser-plugins/libfreshwrapper-pepperflash.so
#21 0x00007f872489425c in ppb_message_loop_run () from /usr/lib64/browser-plugins/libfreshwrapper-pepperflash.so
#22 0x00007f87248773a3 in fresh_wrapper_main_thread () from /usr/lib64/browser-plugins/libfreshwrapper-pepperflash.so
#23 0x00007f87391750db in start_thread () from /lib64/libpthread.so.0
#24 0x00007f8733ca5ddd in clone () from /lib64/libc.so.6

Thread 8 (Thread 0x7f8729567700 (LWP 21277)):
#0  0x00007f87391790af in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00007f871d65e59b in ?? () from /usr/lib64/chromium/PepperFlash/libpepflashplayer.so
#2  0x00007f871d65e825 in ?? () from /usr/lib64/chromium/PepperFlash/libpepflashplayer.so
#3  0x00007f871d8ba06c in ?? () from /usr/lib64/chromium/PepperFlash/libpepflashplayer.so
#4  0x00007f871d65e19c in ?? () from /usr/lib64/chromium/PepperFlash/libpepflashplayer.so
#5  0x00007f871d65e208 in ?? () from /usr/lib64/chromium/PepperFlash/libpepflashplayer.so
#6  0x00007f871d65e401 in ?? () from /usr/lib64/chromium/PepperFlash/libpepflashplayer.so
#7  0x00007f87391750db in start_thread () from /lib64/libpthread.so.0
#8  0x00007f8733ca5ddd in clone () from /lib64/libc.so.6

Thread 7 (Thread 0x7f8726549700 (LWP 21278)):
#0  0x00007f87391790af in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00007f871d65e59b in ?? () from /usr/lib64/chromium/PepperFlash/libpepflashplayer.so
#2  0x00007f871d65e825 in ?? () from /usr/lib64/chromium/PepperFlash/libpepflashplayer.so
#3  0x00007f871d8ba06c in ?? () from /usr/lib64/chromium/PepperFlash/libpepflashplayer.so
#4  0x00007f871d65e19c in ?? () from /usr/lib64/chromium/PepperFlash/libpepflashplayer.so
#5  0x00007f871d65e208 in ?? () from /usr/lib64/chromium/PepperFlash/libpepflashplayer.so
#6  0x00007f871d65e401 in ?? () from /usr/lib64/chromium/PepperFlash/libpepflashplayer.so
#7  0x00007f87391750db in start_thread () from /lib64/libpthread.so.0
#8  0x00007f8733ca5ddd in clone () from /lib64/libc.so.6

Thread 6 (Thread 0x7f8716c17700 (LWP 21280)):
#0  0x00007f8733c9d00d in poll () from /lib64/libc.so.6
#1  0x00007f87230208c1 in ?? () from /usr/lib64/libpulse.so.0
#2  0x00007f87230120ec in pa_mainloop_poll () from /usr/lib64/libpulse.so.0
#3  0x00007f872301275e in pa_mainloop_iterate () from /usr/lib64/libpulse.so.0
#4  0x00007f8723012810 in pa_mainloop_run () from /usr/lib64/libpulse.so.0
#5  0x00007f8723020873 in ?? () from /usr/lib64/libpulse.so.0
#6  0x00007f8720cf2f98 in ?? () from /usr/lib64/pulseaudio/libpulsecommon-4.0.so
#7  0x00007f87391750db in start_thread () from /lib64/libpthread.so.0
#8  0x00007f8733ca5ddd in clone () from /lib64/libc.so.6

Thread 5 (Thread 0x7f8716416700 (LWP 21281)):
#0  0x00007f8739179458 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00007f871d65e520 in ?? () from /usr/lib64/chromium/PepperFlash/libpepflashplayer.so
#2  0x00007f871d65e825 in ?? () from /usr/lib64/chromium/PepperFlash/libpepflashplayer.so
#3  0x00007f871d84ffbd in ?? () from /usr/lib64/chromium/PepperFlash/libpepflashplayer.so
#4  0x00007f871d65e19c in ?? () from /usr/lib64/chromium/PepperFlash/libpepflashplayer.so
#5  0x00007f871d65e208 in ?? () from /usr/lib64/chromium/PepperFlash/libpepflashplayer.so
#6  0x00007f871d65e401 in ?? () from /usr/lib64/chromium/PepperFlash/libpepflashplayer.so
#7  0x00007f87391750db in start_thread () from /lib64/libpthread.so.0
#8  0x00007f8733ca5ddd in clone () from /lib64/libc.so.6

Thread 4 (Thread 0x7f87163d5700 (LWP 21282)):
#0  0x00007f8739179458 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00007f871d65e520 in ?? () from /usr/lib64/chromium/PepperFlash/libpepflashplayer.so
#2  0x00007f871d65e825 in ?? () from /usr/lib64/chromium/PepperFlash/libpepflashplayer.so
#3  0x00007f871da41482 in ?? () from /usr/lib64/chromium/PepperFlash/libpepflashplayer.so
#4  0x00007f871d65e19c in ?? () from /usr/lib64/chromium/PepperFlash/libpepflashplayer.so
#5  0x00007f871d65e208 in ?? () from /usr/lib64/chromium/PepperFlash/libpepflashplayer.so
#6  0x00007f871d65e401 in ?? () from /usr/lib64/chromium/PepperFlash/libpepflashplayer.so
#7  0x00007f87391750db in start_thread () from /lib64/libpthread.so.0
#8  0x00007f8733ca5ddd in clone () from /lib64/libc.so.6

Thread 3 (Thread 0x7f8716314700 (LWP 21336)):
#0  0x00007f87391790af in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00007f871d65e59b in ?? () from /usr/lib64/chromium/PepperFlash/libpepflashplayer.so
#2  0x00007f871d65e825 in ?? () from /usr/lib64/chromium/PepperFlash/libpepflashplayer.so
#3  0x00007f871d67171f in ?? () from /usr/lib64/chromium/PepperFlash/libpepflashplayer.so
#4  0x00007f871d922fb1 in ?? () from /usr/lib64/chromium/PepperFlash/libpepflashplayer.so
#5  0x00007f871d9239ea in ?? () from /usr/lib64/chromium/PepperFlash/libpepflashplayer.so
#6  0x00007f871d65e19c in ?? () from /usr/lib64/chromium/PepperFlash/libpepflashplayer.so
#7  0x00007f871d65e208 in ?? () from /usr/lib64/chromium/PepperFlash/libpepflashplayer.so
#8  0x00007f871d65e401 in ?? () from /usr/lib64/chromium/PepperFlash/libpepflashplayer.so
#9  0x00007f87391750db in start_thread () from /lib64/libpthread.so.0
#10 0x00007f8733ca5ddd in clone () from /lib64/libc.so.6

Thread 2 (Thread 0x7f871c419700 (LWP 21338)):
#0  0x00007f8739179458 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00007f8730a345f5 in g_cond_wait_until () from /usr/lib64/libglib-2.0.so.0
#2  0x00007f87309caa71 in ?? () from /usr/lib64/libglib-2.0.so.0
#3  0x00007f87309caffb in g_async_queue_timeout_pop () from /usr/lib64/libglib-2.0.so.0
#4  0x00007f8730a19ac6 in ?? () from /usr/lib64/libglib-2.0.so.0
#5  0x00007f8730a19035 in ?? () from /usr/lib64/libglib-2.0.so.0
#6  0x00007f87391750db in start_thread () from /lib64/libpthread.so.0
#7  0x00007f8733ca5ddd in clone () from /lib64/libc.so.6

Thread 1 (Thread 0x7f8739553a40 (LWP 21268)):
#0  0x00007f87391790af in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00007f8730a34507 in g_cond_wait () from /usr/lib64/libglib-2.0.so.0
#2  0x00007f8730a1918b in g_once_init_enter () from /usr/lib64/libglib-2.0.so.0
#3  0x00007f872326e420 in gdk_window_get_type () from /usr/lib64/libgdk-3.so.0
#4  0x00007f872326ebd9 in gdk_window_get_display () from /usr/lib64/libgdk-3.so.0
#5  0x00007f872329b210 in gdk_x11_window_get_xid () from /usr/lib64/libgdk-3.so.0
#6  0x00007f872488610f in show_without_user_guesture_ptac () from /usr/lib64/browser-plugins/libfreshwrapper-pepperflash.so
#7  0x00007f8724882840 in call_on_browser_thread_comt () from /usr/lib64/browser-plugins/libfreshwrapper-pepperflash.so
#8  0x00007f8724894697 in ppb_message_loop_run_int () from /usr/lib64/browser-plugins/libfreshwrapper-pepperflash.so
#9  0x00007f8724894278 in ppb_message_loop_run_nested () from /usr/lib64/browser-plugins/libfreshwrapper-pepperflash.so
#10 0x00007f8724881360 in p2n_has_property () from /usr/lib64/browser-plugins/libfreshwrapper-pepperflash.so
#11 0x00007f873603e464 in ?? () from /usr/lib64/firefox/libxul.so
#12 0x00007f873550baea in ?? () from /usr/lib64/firefox/libxul.so
#13 0x00007f873550f279 in ?? () from /usr/lib64/firefox/libxul.so
#14 0x00007f87354a7801 in ?? () from /usr/lib64/firefox/libxul.so
#15 0x00007f87354a794e in ?? () from /usr/lib64/firefox/libxul.so
#16 0x00007f87354a9908 in ?? () from /usr/lib64/firefox/libxul.so
#17 0x00007f8735496730 in ?? () from /usr/lib64/firefox/libxul.so
#18 0x00007f873549aebb in ?? () from /usr/lib64/firefox/libxul.so
#19 0x00007f873549afc6 in ?? () from /usr/lib64/firefox/libxul.so
#20 0x00007f873549043d in ?? () from /usr/lib64/firefox/libxul.so
#21 0x00007f8735490471 in ?? () from /usr/lib64/firefox/libxul.so
#0  0x00007f87391790af in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00007f871d65e59b in ?? () from /usr/lib64/chromium/PepperFlash/libpepflashplayer.so
#2  0x00007f871d65e825 in ?? () from /usr/lib64/chromium/PepperFlash/libpepflashplayer.so
#3  0x00007f871d67171f in ?? () from /usr/lib64/chromium/PepperFlash/libpepflashplayer.so
#4  0x00007f871d922fb1 in ?? () from /usr/lib64/chromium/PepperFlash/libpepflashplayer.so
#5  0x00007f871d9239ea in ?? () from /usr/lib64/chromium/PepperFlash/libpepflashplayer.so
#6  0x00007f871d65e19c in ?? () from /usr/lib64/chromium/PepperFlash/libpepflashplayer.so
#7  0x00007f871d65e208 in ?? () from /usr/lib64/chromium/PepperFlash/libpepflashplayer.so
#8  0x00007f871d65e401 in ?? () from /usr/lib64/chromium/PepperFlash/libpepflashplayer.so
#9  0x00007f87391750db in start_thread () from /lib64/libpthread.so.0
#10 0x00007f8733ca5ddd in clone () from /lib64/libc.so.6

Thread 2 (Thread 0x7f871c419700 (LWP 21338)):
#0  0x00007f8739179458 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00007f8730a345f5 in g_cond_wait_until () from /usr/lib64/libglib-2.0.so.0
#2  0x00007f87309caa71 in ?? () from /usr/lib64/libglib-2.0.so.0
#3  0x00007f87309caffb in g_async_queue_timeout_pop () from /usr/lib64/libglib-2.0.so.0
#4  0x00007f8730a19ac6 in ?? () from /usr/lib64/libglib-2.0.so.0
#5  0x00007f8730a19035 in ?? () from /usr/lib64/libglib-2.0.so.0
#6  0x00007f87391750db in start_thread () from /lib64/libpthread.so.0
#7  0x00007f8733ca5ddd in clone () from /lib64/libc.so.6

Thread 1 (Thread 0x7f8739553a40 (LWP 21268)):
#0  0x00007f87391790af in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00007f8730a34507 in g_cond_wait () from /usr/lib64/libglib-2.0.so.0
#2  0x00007f8730a1918b in g_once_init_enter () from /usr/lib64/libglib-2.0.so.0
#3  0x00007f872326e420 in gdk_window_get_type () from /usr/lib64/libgdk-3.so.0
#4  0x00007f872326ebd9 in gdk_window_get_display () from /usr/lib64/libgdk-3.so.0
#5  0x00007f872329b210 in gdk_x11_window_get_xid () from /usr/lib64/libgdk-3.so.0
#6  0x00007f872488610f in show_without_user_guesture_ptac () from /usr/lib64/browser-plugins/libfreshwrapper-pepperflash.so
#7  0x00007f8724882840 in call_on_browser_thread_comt () from /usr/lib64/browser-plugins/libfreshwrapper-pepperflash.so
#8  0x00007f8724894697 in ppb_message_loop_run_int () from /usr/lib64/browser-plugins/libfreshwrapper-pepperflash.so
#9  0x00007f8724894278 in ppb_message_loop_run_nested () from /usr/lib64/browser-plugins/libfreshwrapper-pepperflash.so
#10 0x00007f8724881360 in p2n_has_property () from /usr/lib64/browser-plugins/libfreshwrapper-pepperflash.so
#11 0x00007f873603e464 in ?? () from /usr/lib64/firefox/libxul.so
#12 0x00007f873550baea in ?? () from /usr/lib64/firefox/libxul.so
#13 0x00007f873550f279 in ?? () from /usr/lib64/firefox/libxul.so
#14 0x00007f87354a7801 in ?? () from /usr/lib64/firefox/libxul.so
#15 0x00007f87354a794e in ?? () from /usr/lib64/firefox/libxul.so
#16 0x00007f87354a9908 in ?? () from /usr/lib64/firefox/libxul.so
#17 0x00007f8735496730 in ?? () from /usr/lib64/firefox/libxul.so
#18 0x00007f873549aebb in ?? () from /usr/lib64/firefox/libxul.so
#19 0x00007f873549afc6 in ?? () from /usr/lib64/firefox/libxul.so
#20 0x00007f873549043d in ?? () from /usr/lib64/firefox/libxul.so
#21 0x00007f8735490471 in ?? () from /usr/lib64/firefox/libxul.so
---Type <return> to continue, or q <return> to quit---
#22 0x00007f87309f4316 in g_main_context_dispatch () from /usr/lib64/libglib-2.0.so.0
#23 0x00007f87309f4668 in ?? () from /usr/lib64/libglib-2.0.so.0
#24 0x00007f87309f470c in g_main_context_iteration () from /usr/lib64/libglib-2.0.so.0
#25 0x00007f873548fff2 in ?? () from /usr/lib64/firefox/libxul.so
#26 0x00007f8735496791 in ?? () from /usr/lib64/firefox/libxul.so
#27 0x00007f87366a66a5 in XRE_InitChildProcess () from /usr/lib64/firefox/libxul.so
#28 0x000000000040912b in _start ()

**Comment by i-rinat** [comment]
Looks like it hangs inside libgdk-3.so.0, while it shouldn't.
Another question is why GTK+ 3?

I do have an option to select which GTK+ version freshwrapper is linked with, but actually there is no choice. One should always use GTK+2. Even GTK+ 3 version of Firefox uses a special trick, and its plugin-container process loads version 2, because Flash plugin (I mean, NPAPI, 11.2) expects it. So when GTK+3 version of freshwrapper is loaded, both 2 and 3 libraries are dragged in simultaneously, which can give unexpected results.

Try to build freshwrapper from source from git repository, not from src.rpm.

**Comment by i-rinat** [comment]
I see src.rpm from Packman repo build NaCl and libpdf wrappers too. They are completely useless now, that's why their compilation is disabled by default.

**Comment by lashkevi** [comment]
It works! I have built it on OpenSUSE build service by branching from the multimedia:apps build project and suppressing GTK-3, NaCl and libpdf. No crash! I published the resulting binaries on http://download.opensuse.org/repositories/home:/lashkevi:/branches:/multimedia:/apps/.

Maybe you could contact the Packman and OpenSUSE multimedia teams and ask to solve the problem in this way?

**Comment by i-rinat** [comment]
(Sent a letter to the mailing list.)

**Comment by i-rinat** [comment]
Recent version of freshplayerplugin-0.3.0-4.1.src.rpm in Packman repository is compiled with gtk2 for all distributive versions.
