### ISSUE TITLE
Flash 18.0.0.195

### ISSUE THREAD

**Issue by helpdeskdan** [i-rinat/freshplayerplugin#223]
DRM no longer appears to work in this version, extracted from chrome os.  Works fine in 17.0.0.188.  Perhaps adobe/google are watching.  

Not that I personally tried this, of course!  That might be illegal, I watched somebody else do it on the internet - please don't sue me adobe/google!

**Comment by i-rinat** [comment]
Recovery images are still at 6812.88.0, which  have 17.0.0.188.

**Comment by helpdeskdan** [comment]
Hypothetically, if somebody HAS a chromebox, they could extract a much newer version.

**Comment by helpdeskdan** [comment]
After searching the internet, I see somebody put it here.  If you own a chromebox/book, perhaps it would not be illegal for you to download it.
 
http://www.megafileupload.com/d7bJ/libpepflashplayer.so

**Comment by i-rinat** [comment]
Works on Adobe drm test page.

Try to wipe contents of `~/.config/freshwrapper-data/Shockwave Flash`. That will remove all local data saved by Flash player, including acquired license files. On next run it will acquire them again, so it should be fine. (Make a backup if you're concerned about Flash cookie loss).

**Comment by helpdeskdan** [comment]
Didn't work the first time I tried it, second delete seemed to work.  (Strange)  Thanks for this project!

**Comment by i-rinat** [comment]
By the way, is any Flash content works with that plugin?
