### ISSUE TITLE
Fullscreen video does not span the whole screen

### ISSUE THREAD

**Issue by Lastique** [i-rinat/freshplayerplugin#227]
When I make video fullscreen it doesn't fill the whole screen but just a portion at the top left corner. The rest of the screen is garbage or some filled color.

I have two displays attached. The main one is 2560x1440, it's the one that I'm viewing the video on. The other one is a TV 1920x1080. The two displays are configured to extend the desktop (i.e. not mirror). Incidentally, the fullscreen video occupies the top left 1920x1080 area of the main screen, so I thought this could be related.

Ubuntu 15.10 x86_64 with XFCE, freshplayerplugin 0.3.1+git20150706~webupd8~vivid, Nvidia drivers 346.59. This started to happen just recently, after freshplayerplugin and xfwm4 were updated (Nvidia drivers were not updated). Fullscreen videos worked fine before the update.

![flash_fullscreen](https://cloud.githubusercontent.com/assets/1589747/8616503/797a5388-2704-11e5-99c3-4f1fe9f6a0ee.png)

**Comment by i-rinat** [comment]
Hi. Could you run code from [tmp-show-window-geometry](https://github.com/i-rinat/freshplayerplugin/tree/tmp-show-window-geometry) branch? It will print geometry of fullscreen window to standard output, so browser should be run from terminal emulator prompt.

**Comment by SammysHP** [comment]
Similar setup, same issue. Started after the update from 0.3.0 to 0.3.1.

**Comment by Lastique** [comment]
@i-rinat I tried the code from the branch, the console output is as follows:

```
(process:27056): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
libva info: VA-API version 0.37.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/nvidia_drv_video.so
libva info: Found init function __vaDriverInit_0_35
libva info: va_openDriver() returns 0
NOT SANDBOXED
[fresh 27143] not implemented: PPB_OpenGLES2VertexArrayObject;1.0
[fresh 27143] not implemented: PPB_OpenGLES2DrawBuffers(Dev);1.0
[fresh] [error] [NP] caught Xlib error 8
[fresh] [error] [fresh] [error] [NP] caught Xlib error 171
[fresh] [error] [NP] caught Xlib error 8
[fresh] [error] [NP] caught Xlib error 171
ppb_graphics3d_create, glXMakeCurrent failed
[fresh] [error] ppb_graphics3d_create, glXMakeCurrent failed
ConfigureNofity, 10x10+0+0
ConfigureNofity, 2560x1440+0+0
ConfigureNofity, 2560x1440+0+0
Expose, 2560x1440+0+0
```

One interesting effect that I also noticed is that Flash options menu seems small when in fullscreen, but it doesn't react to mouse pointer when hovered over or clicked on. It does react when the mouse is near the center of the screen, where the menu is usually at. It's as if the whole video area with the menu are scaled down to 1920x1080.

**Comment by i-rinat** [comment]
PepperFlash started to query screen size more often since I wrote the code. So I've changed `ppb_flash_fullscreen_get_screen_size()` to return actual sizes, which are obtained from window manager in b100b9ccbc4cf0361b759f6918d563cc6c2666ec.

Could you test again? Now from `master` branch.

**Comment by Lastique** [comment]
Yes, the code from master fixes the problem. Thanks!

**Comment by i-rinat** [comment]
That's good.
