### ISSUE TITLE
Implement AudioControl

### ISSUE THREAD

**Issue by evilpie** [i-rinat/freshplayerplugin#228]
See [Mozilla Bug 1167690](https://bugzilla.mozilla.org/show_bug.cgi?id=1167690) and the [wiki](https://wiki.mozilla.org/NPAPI:AudioControl). This should hopefully allow Firefox to show a sound playing indicator in the near future.

**Comment by i-rinat** [comment]
Are there any browsers with that feature support, by any chance?

**Comment by evilpie** [comment]
See the Mozilla Bug and some of its blockers/dependencies. They are actively working on implementing this.

**Comment by i-rinat** [comment]
Implemented in https://github.com/i-rinat/freshplayerplugin/compare/a317c4cc528a3fc868e5768071737117e633dc94...5251ec7c9b9195fe48525747b18ead5e26ac248f.

**Comment by i-rinat** [comment]
Browser-side code is already in Firefox Nightly, so you could check it out.
