### ISSUE TITLE
google translate

### ISSUE THREAD

**Issue by MALLER-LAGOON** [i-rinat/freshplayerplugin#233]
the listen plugin in the google translate is not working since some versions of freshplayerplugin.
i'm not sure yet if it has to do with the freshplayer it self, the google translate page, or the pepperflash. but when i try the google translate in chrome it works fine.
i'll watch for some of the commits if i found someone that works in this functionality, and if i found something, i'll report it to you.

**Comment by i-rinat** [comment]
I tried several times, from about day after reporting, some days later, and just now. It worked on my machine, although I need to enable plugin [1] before pressing "speak" button. It doesn't popup as there is no visible instance to click. Running under Valgrind didn't reveal any hidden issue too.

So, more information is needed to reproduce the bug.

[1] I use "ask to activate" mode

**Comment by MALLER-LAGOON** [comment]
what is that "ask to activate"?, maybe that is the problem and i didn't see it before. but is rare. :/

**Comment by i-rinat** [comment]
> what is that "ask to activate"?

On about:addons page select "Plugins" tab. There are listed all plugins you have installed, each having a drop-down menu with three options, "Always activate", "Ask to activate", and "Never activate". Last one disables plugin completely, first one enables it on all pages, unconditionally. But "ask to activate" shows a gray box instead. If one wants to activate plugin on the page, they activate it manually.

https://support.mozilla.org/en-US/kb/set-adobe-flash-click-play-firefox

Google translate uses hidden Flash movie to output sound, so there are no place to click. But there are still plugin icon in the address bar. It can be clicked too, with same effect.

**Comment by MALLER-LAGOON** [comment]
nop, there is no improve.

the site appears allowed, also the flash plugin https://ssl.gstatic.com/translate/sound_player2.swf is allowed (i allowed it apart, just in case). but nothing. :(

what i notice, is that every time that i press the sound button, this messages appears:

>** (firefox:5058): CRITICAL **: gst_app_src_set_size: assertion 'GST_IS_APP_SRC (appsrc)' failed

**Comment by i-rinat** [comment]
> NPP_GetValue npp=0x7f3be6b9f220, variable=NPPVpluginNativeAccessibleAtkPlugId

That's new, related to accessibility toolkit (ATK), I never seen this on my machine. I've seen that in reports though, but it didn't bother other functions anyhow.

> gst_app_src_set_size: assertion 'GST_IS_APP_SRC (appsrc)' failed

That error message is from GStreamer. `appsrc` is a GStreamer plugin that allows applications to push data into the graph. Firefox uses it and `appsink` to decode audio/video via GStreamer. I could be Flash is not used at all, since Firefox advertise Web Audio API support.

For experiment, try to disable GStreamer by setting `media.gstreamer.enabled` to `false` on `about:config` page.

**Comment by MALLER-LAGOON** [comment]
yeah, that solves the problem. thank u @i-rinat

**Comment by i-rinat** [comment]
That's not a solution — by turning off GStreamer support you're cutting off H.264 and MP3 playback in HTML5. Although Google Translate will fall back to Flash, other sites may not.
