### ISSUE TITLE
Doesn't work on The Daily Show or The Nightly Show site

### ISSUE THREAD

**Issue by tylendel** [i-rinat/freshplayerplugin#234]
When using on the Daily Show (www.thedailyshow.com/full-episodes/) or The Nightly Show (www.cc.com/shows/the-nightly-show), which I'm sure use the same player, it says the video is not available.  Opening in Chromium with pepper flash works fine.

**Comment by beew** [comment]
Works here. freshplayerplugin 0.3.0 on Ubuntu 15.04 Firefox 39

**Comment by tylendel** [comment]
OK got it to work, sorry to bug you.  It was refcontrol.  I had allowed referrers to the specific sites so I discounted it as the issue.  Turns out it's mtvnservices.com you have to allow referrers for (in case anyone else comes across this).
