### ISSUE TITLE
Support Flash Audio Channel Notifications

### ISSUE THREAD

**Issue by Caspy7** [i-rinat/freshplayerplugin#237]
Now that Flash supports audio channel notifications in the NPAPI plugin, Mozilla is building support for it
https://bugzilla.mozilla.org/show_bug.cgi?id=1167690
in order to support visual notifications for audio content in tabs
https://bugzilla.mozilla.org/show_bug.cgi?id=486262#c71
It would be great if this built in support so Linux users could also enjoy this feature in its fullness.

**Comment by i-rinat** [comment]
(related to #228)

**Comment by i-rinat** [comment]
Implemented in https://github.com/i-rinat/freshplayerplugin/compare/a317c4cc528a3fc868e5768071737117e633dc94...5251ec7c9b9195fe48525747b18ead5e26ac248f.

**Comment by i-rinat** [comment]
Browser-side code is already in Firefox Nightly, so you could check it out.
