### ISSUE TITLE
Nhk streaming does not work.

### ISSUE THREAD

**Issue by luigi121** [i-rinat/freshplayerplugin#238]
Hi,

I'm using debian 8.1 amd64, default configuration with only change: enable_3d = 0.

libfreshwrapper-pepperflash.so (git pull today)  (libpepflashplayer.so 18.0.0.209) works fine with youtube and others sites.

But "http://www3.nhk.or.jp/nhkworld/en/live/" does not work. Flash rectangle show icons at bottom, but no video, no audio.

Thanks.

**Comment by i-rinat** [comment]
Hi. Are there any regional restrictions on that translation? The page tells me "Video streaming not available on this device" when I try to load it in both Firefox and Chrome.

**Comment by dilworks** [comment]
NHK World doesn't geoblock content (it's a station meant for overseas users), but I can say that it doesn't even work on Chrome under Linux (I get the same "not available on this device" error message). Maybe it is enforcing OS-level lockout? I'll give it a try on a Windows VM.

**Comment by i-rinat** [comment]
Setting User-Agent string to such of Windows version of Chrome helps indeed. At least swf movie loads. But doesn't work.

What actually helps is using PepperFlash from ChromeOS. That means that translation uses DRM.

**Comment by i-rinat** [comment]
Just to reiterate.
PepperFlash from desktop version of Chrome won't work, it doesn't have DRM-related code compiled (neither have desktop Chrome). But PepperFlash from ChromeOS have everything required. I don't know whenever it's legal to redistribute it, so I avoid doing so. But it's still possible for end users to acquire plugin by themselves.

There is instruction in https://github.com/i-rinat/freshplayerplugin/issues/13#issuecomment-60490990, which still works, except version numbers are different. After you extract plugin, put it somewhere in filesystem, add `pepperflash_path` parameter with full path to `~/.config/freshwrapper.conf`. That should be enough to get it working.
