### ISSUE TITLE
PPAPI 2 NPAPI

### ISSUE THREAD

**Issue by johanbrunius** [i-rinat/freshplayerplugin#239]
Hi!

I was thinking about using the converter the other way around.

As you probably know Chrome is dropping NPAPI support and I could see that alot of companies would be interested in buying a service to automatically convert their npapi to ppapi.

What do you think?

Kind regards
Johan

**Comment by i-rinat** [comment]
What do I think about what particularly? Implementing such "converter"? I'm not interested in such converter myself, since I don't have a use case.

**Comment by i-rinat** [comment]
By the way, it would be comparable with [Wine](https://www.winehq.org/) in terms of complexity.

Much easier to just convert sources of plugins to use PPAPI directly.

**Comment by johanbrunius** [comment]
Hi!

I was thinking that you could sell it to alot of different players out there, cause their solutions don't work with Chrome any longer. It would be a hassle for them to rewrite it to PPAPI. I was thinking about providing a service that took their NPAPI app and made it work using PPAPI instead. Like a layer ontop of it to made it seem like a PPAPI.

The reason why I contacted you was that you had worked with both specifications. 
I feel like this is an opportunity that soon will be closed and wanted to hear your insights into this.

**Comment by i-rinat** [comment]
If you like the idea, feel free to use it as you wish.

I personally don't think it's feasible. As said earlier, one need to intercept all native calls made by NPAPI plugin and wrap them into corresponding PPAPI calls. That's lot harder than to do opposite (which I'm doing in current project). Wine project does a similar translation. But it centers on providing implementation of only Windows calls. Converter you are going to build must handle all Windows, Mac OS X, and Linux.

**Comment by i-rinat** [comment]
By the way, I've got an implementation idea. So I'll describe it here, for anyone interested.

Chrome runs plugin host process in a sandbox, which effectively blocks NPAPI plugin operation. But network communication is still possible. Therefore, one could implement externally launched host process which loads NPAPI plugin and then listen for incoming commands. Another part will be custom PPAPI plugin, which will supply that host process with commands. One need to implement passing of keyboard and mouse events, and also graphics images.
