### ISSUE TITLE
fullscreen isn't working on old video cards

### ISSUE THREAD

**Issue by dmnord** [i-rinat/freshplayerplugin#240]
Hi, I'm using Fedora Workstation that hosted on a computer with core2duo processor and its integrated video adapter. People who also use the plugin have reported that the plugin works well on a newest video adapters than my one.

Every time when I'm trying to get a fullscreen mode of played video, I get an empty black screen.
Also when I'm setting enable_3d to 0, the fullscreen works, but only when I try to play a video from youtube. Video from another sites works bad with the same conditions.

I've tried to use your latest commit of plugin, but I see the same thing while playing video.

Look at the misc information to assist in problem:
http://koji.russianfedora.pro/koji/taskinfo?taskID=43808
http://koji.russianfedora.pro/kojifiles/work/tasks/3810/43810/build.log

**Comment by i-rinat** [comment]
I've just added a patch (491b5b47c742b56105a18519420f0ed58bf36ac9) which changes the way fullscreen geometry is determined. Could you try again?

**Comment by dmnord** [comment]
Hi! I 've checked a package from commit 491b5b4, you've chosen. It work correctly!
This link may useful for someone: http://koji.russianfedora.pro/koji/taskinfo?taskID=44339
