### ISSUE TITLE
glXMakeCurrent failed on Nvidia Hardware.

### ISSUE THREAD

**Issue by Zombie-Ryushu** [i-rinat/freshplayerplugin#241]
NOT SANDBOXED
[fresh 21466] not implemented: PPB_OpenGLES2VertexArrayObject;1.0
[fresh 21466] not implemented: PPB_OpenGLES2DrawBuffers(Dev);1.0
[fresh 21466] [PPB] {zilch} ppb_network_monitor_update_network_list
[fresh 21466] [PPB] {zilch} ppb_flash_set_instance_always_on_top instance=11, on_top=1
[fresh 21466] [PPB] {zilch} ppb_network_monitor_update_network_list
[fresh] [error] [NP] caught Xlib error 8
[fresh] [error] [NP] caught Xlib error 8
[fresh] [error] [NP] caught Xlib error 171
[fresh] [error] [NP] caught Xlib error 171
[fresh] [error] ppb_graphics3d_create, glXMakeCurrent failed
[fresh] [error] ppb_graphics3d_create, glXMakeCurrent failed

**Comment by i-rinat** [comment]
Acquiring GLES2 context doesn't work for some reason. You could try to use GLES2 emulator by adding `-DWITH_GLES2=0` to cmake parameters:
```
$ cmake -DWITH_GLES2=0 ..
$ make
```

**Comment by i-rinat** [comment]
I've switched to GLES2 emulation by default in 69825502c631b252571b02f214b242c3ee135a3f. Hence path for GLES2 over GLX is now avoided, and that error should not trigger anymore.
