### ISSUE TITLE
While in Fullscreen the video does not show properly in Fresh Player on Xubuntu 14.04 with Kwin.

### ISSUE THREAD

**Issue by TheIntelligentMan** [i-rinat/freshplayerplugin#243]
When watching a flash video if I click Fullscreen the video does not show properly and the only thing I get is a black screen or the videos becomes corrupted.This issue however doesn't occur with HTML5 so I think it's a issue with Fresh Player.

**Comment by i-rinat** [comment]
I've just added a patch (491b5b47c742b56105a18519420f0ed58bf36ac9) which changes the way fullscreen geometry is determined. Could you try again?

**Comment by TheIntelligentMan** [comment]
i-rinat,I seem to be having some issue with compiling your plugin fresh player.When I put the cmake command for compiling  it gives me this error:
CMake Error at CMakeLists.txt:151 (add_subdirectory):
  add_subdirectory given source "tests" which is not an existing directory

Care to explain what I should do to fix this and get it to compile properly?

**Comment by i-rinat** [comment]
That's odd. You surely have `CMakeLists.txt` at source root, that's where you get error from. But don't have `tests` subdirectory?

Where did you get source from? Is there `tests` subdirectory? Which directory are you calling cmake from?

**Comment by TheIntelligentMan** [comment]
Weird I got it to compile by getting the tests sub directory and CMakeLists.txt out of the directory that includes the make files.After I compiled the plugin and put it on firefox the issue I had with Fresh player was fixed.So thank you i-rinat that patch you put fixed my issue with your plugin and now I can finally enjoy videos without it tearing needlessly.I'll now close two of my bug reports seeing as flash is now working properly.
