### ISSUE TITLE
No option to not autoconnect in Jack

### ISSUE THREAD

**Issue by AstralStorm** [i-rinat/freshplayerplugin#244]
Jack output seems to automatically connect to default outputs. This unfortunately is incorrect in my setup and interferes with Ladish session handling by adding the spurious connection.

Please add an option to not autoconnect to the default ports - should be very easy.

**Comment by i-rinat** [comment]
Hi.
I've added a number of options for JACK related code in https://github.com/i-rinat/freshplayerplugin/compare/8aced7539f00ac2b4624bcc79f7c7fec98272807...a317c4cc528a3fc868e5768071737117e633dc94.
One of them is named `jack_autoconnect_ports`. Its default value is `1`, which enabled freshwrapper to automatically connect ports. Put `jack_autoconnect_ports = 0` line to configuration file to prevent that behavior.
