### ISSUE TITLE
Fullscreen videos at like 1fps on Firefox

### ISSUE THREAD

**Issue by Shaxine** [i-rinat/freshplayerplugin#245]
I'm using elementaryOS Freya and when I switch to fullscreen the videos drop to like 1fps and even when accessing Flash Settings(Right-Click). I have tried enable and disable the "enable_3d", with no changes on the performance.

**Comment by i-rinat** [comment]
Hi.
That could be vsync gone wild.
Please try to add `enable_vsync = 0` line to `~/.config/freshwrapper.conf` and restart browser. Does it help?

**Comment by Shaxine** [comment]
Hi,
Thank you very much, that did the trick.
And congratulations for your amazing work man.

**Comment by i-rinat** [comment]
I wonder why did it work so strange. What video adapter do you use?

**Comment by Shaxine** [comment]
I'm on a Samsung laptop with a hybrid video card one its a AMD Radeon™ HD 7670M and the other a Intel HD 3rd Gen.
