### ISSUE TITLE
latest git compile fails with new mesa 11.x

### ISSUE THREAD

**Issue by m00ster** [i-rinat/freshplayerplugin#247]
Hello,

latest git fails to compile against latest mesa:

[ 66%] /home/jon/Source/freshplayerplugin/src/ppb_graphics3d.c: In function ‘ppb_graphics3d_create’:
/home/jon/Source/freshplayerplugin/src/ppb_graphics3d.c:171:14: error: ‘GLX_Y_INVERTED_EXT’ undeclared (first use in this function)
         case GLX_Y_INVERTED_EXT:
              ^
/home/jon/Source/freshplayerplugin/src/ppb_graphics3d.c:171:14: note: each undeclared identifier is reported only once for each function it appears in
/home/jon/Source/freshplayerplugin/src/ppb_graphics3d.c:176:14: error: ‘GLX_BIND_TO_TEXTURE_RGBA_EXT’ undeclared (first use in this function)
         case GLX_BIND_TO_TEXTURE_RGBA_EXT:
              ^
make[2]: *** [src/CMakeFiles/freshwrapper-obj.dir/ppb_graphics3d.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
Building C object src/CMakeFiles/freshwrapper-obj.dir/ppb_memory.c.o
make[1]: *** [src/CMakeFiles/freshwrapper-obj.dir/all] Error 2
make: *** [all] Error 2

**Comment by m00ster** [comment]
I was able to correct the build by pulling in external mesa headers:

```javascript
diff --git a/src/ppb_graphics3d.c b/src/ppb_graphics3d.c
index b9575c9..325fd36 100644
--- a/src/ppb_graphics3d.c
+++ b/src/ppb_graphics3d.c
@@ -28,6 +28,7 @@
 #include "ppb_graphics3d.h"
 #include <stdlib.h>
 #include <GL/glx.h>
+#include <GL/glxext.h>
 #include <GLES2/gl2.h>
 #include "trace.h"
 #include "tables.h"
diff --git a/src/ppb_video_decoder.c b/src/ppb_video_decoder.c
index 799bd28..f912e38 100644
--- a/src/ppb_video_decoder.c
+++ b/src/ppb_video_decoder.c
@@ -25,6 +25,8 @@
 #include "ppb_video_decoder.h"
 #include <stdlib.h>
 #include <ppapi/c/pp_errors.h>
+#include <GL/glx.h>
+#include <GL/glxext.h>
 #include "trace.h"
 #include "tables.h"
 #include "reverse_constant.h"
```

**Comment by i-rinat** [comment]
There were difficulties with compiling when `GL/glxext.h` included together with `GLES2/gl2.h` (#236), so inclusion of `GL/glxext.h` was removed.

I've added defines for texture_from_pixmap extension in e939d2e75187d4e93b57eebdf438f9f6e863db83. Does it help?

**Comment by m00ster** [comment]
That fixes the first error, but the decoder still needs the defines as well as seen here:

[ 98%] Building C object src/CMakeFiles/freshwrapper-obj.dir/ppb_video_decoder.c.o
/home/jon/Source/freshplayerplugin/src/ppb_video_decoder.c: In function ‘initialize_decoder’:
/home/jon/Source/freshplayerplugin/src/ppb_video_decoder.c:513:9: error: ‘GLX_Y_INVERTED_EXT’ undeclared (first use in this function)
         GLX_Y_INVERTED_EXT,             True,
         ^
/home/jon/Source/freshplayerplugin/src/ppb_video_decoder.c:513:9: note: each undeclared identifier is reported only once for each function it appears in
/home/jon/Source/freshplayerplugin/src/ppb_video_decoder.c:514:9: error: ‘GLX_BIND_TO_TEXTURE_RGBA_EXT’ undeclared (first use in this function)
         GLX_BIND_TO_TEXTURE_RGBA_EXT,   True,
         ^
/home/jon/Source/freshplayerplugin/src/ppb_video_decoder.c: In function ‘issue_frame’:
/home/jon/Source/freshplayerplugin/src/ppb_video_decoder.c:723:72: error: ‘GLX_FRONT_EXT’ undeclared (first use in this function)
     display.glXBindTexImageEXT(display.x, vd->buffers[idx].glx_pixmap, GLX_FRONT_EXT, NULL);
                                                                        ^
/home/jon/Source/freshplayerplugin/src/ppb_video_decoder.c:723:5: warning: passing argument 3 of ‘display.glXBindTexImageEXT’ makes integer from pointer without a cast [enabled by default]
     display.glXBindTexImageEXT(display.x, vd->buffers[idx].glx_pixmap, GLX_FRONT_EXT, NULL);
     ^
/home/jon/Source/freshplayerplugin/src/ppb_video_decoder.c:723:5: note: expected ‘int’ but argument is of type ‘int32_t *’
/home/jon/Source/freshplayerplugin/src/ppb_video_decoder.c: In function ‘ppb_video_decoder_assign_picture_buffers’:
/home/jon/Source/freshplayerplugin/src/ppb_video_decoder.c:900:13: error: ‘GLX_TEXTURE_TARGET_EXT’ undeclared (first use in this function)
             GLX_TEXTURE_TARGET_EXT, GLX_TEXTURE_2D_EXT,
             ^
/home/jon/Source/freshplayerplugin/src/ppb_video_decoder.c:900:13: warning: initialization makes integer from pointer without a cast [enabled by default]
/home/jon/Source/freshplayerplugin/src/ppb_video_decoder.c:900:13: warning: (near initialization for ‘tfp_pixmap_attrs[0]’) [enabled by default]
/home/jon/Source/freshplayerplugin/src/ppb_video_decoder.c:900:37: error: ‘GLX_TEXTURE_2D_EXT’ undeclared (first use in this function)
             GLX_TEXTURE_TARGET_EXT, GLX_TEXTURE_2D_EXT,
                                     ^
/home/jon/Source/freshplayerplugin/src/ppb_video_decoder.c:900:13: warning: initialization makes integer from pointer without a cast [enabled by default]
             GLX_TEXTURE_TARGET_EXT, GLX_TEXTURE_2D_EXT,
             ^
/home/jon/Source/freshplayerplugin/src/ppb_video_decoder.c:900:13: warning: (near initialization for ‘tfp_pixmap_attrs[1]’) [enabled by default]
/home/jon/Source/freshplayerplugin/src/ppb_video_decoder.c:901:13: error: ‘GLX_MIPMAP_TEXTURE_EXT’ undeclared (first use in this function)
             GLX_MIPMAP_TEXTURE_EXT, GL_FALSE,
             ^
/home/jon/Source/freshplayerplugin/src/ppb_video_decoder.c:901:13: warning: initialization makes integer from pointer without a cast [enabled by default]
/home/jon/Source/freshplayerplugin/src/ppb_video_decoder.c:901:13: warning: (near initialization for ‘tfp_pixmap_attrs[2]’) [enabled by default]
/home/jon/Source/freshplayerplugin/src/ppb_video_decoder.c:902:13: error: ‘GLX_TEXTURE_FORMAT_EXT’ undeclared (first use in this function)
             GLX_TEXTURE_FORMAT_EXT, g3d->depth == 32 ? GLX_TEXTURE_FORMAT_RGBA_EXT
             ^
/home/jon/Source/freshplayerplugin/src/ppb_video_decoder.c:902:13: warning: initialization makes integer from pointer without a cast [enabled by default]
/home/jon/Source/freshplayerplugin/src/ppb_video_decoder.c:902:13: warning: (near initialization for ‘tfp_pixmap_attrs[4]’) [enabled by default]
/home/jon/Source/freshplayerplugin/src/ppb_video_decoder.c:902:56: error: ‘GLX_TEXTURE_FORMAT_RGBA_EXT’ undeclared (first use in this function)
             GLX_TEXTURE_FORMAT_EXT, g3d->depth == 32 ? GLX_TEXTURE_FORMAT_RGBA_EXT
                                                        ^
/home/jon/Source/freshplayerplugin/src/ppb_video_decoder.c:903:56: error: ‘GLX_TEXTURE_FORMAT_RGB_EXT’ undeclared (first use in this function)
                                                      : GLX_TEXTURE_FORMAT_RGB_EXT,
                                                        ^
/home/jon/Source/freshplayerplugin/src/ppb_video_decoder.c:903:54: warning: initialization makes integer from pointer without a cast [enabled by default]
                                                      : GLX_TEXTURE_FORMAT_RGB_EXT,
                                                      ^
/home/jon/Source/freshplayerplugin/src/ppb_video_decoder.c:903:54: warning: (near initialization for ‘tfp_pixmap_attrs[5]’) [enabled by default]
/home/jon/Source/freshplayerplugin/src/ppb_video_decoder.c: In function ‘ppb_video_decoder_reuse_picture_buffer’:
/home/jon/Source/freshplayerplugin/src/ppb_video_decoder.c:966:85: error: ‘GLX_FRONT_EXT’ undeclared (first use in this function)
                 display.glXReleaseTexImageEXT(display.x, vd->buffers[k].glx_pixmap, GLX_FRONT_EXT);
                                                                                     ^
/home/jon/Source/freshplayerplugin/src/ppb_video_decoder.c:966:17: warning: passing argument 3 of ‘display.glXReleaseTexImageEXT’ makes integer from pointer without a cast [enabled by default]
                 display.glXReleaseTexImageEXT(display.x, vd->buffers[k].glx_pixmap, GLX_FRONT_EXT);
                 ^
/home/jon/Source/freshplayerplugin/src/ppb_video_decoder.c:966:17: note: expected ‘int’ but argument is of type ‘int32_t *’
make[2]: *** [src/CMakeFiles/freshwrapper-obj.dir/ppb_video_decoder.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [src/CMakeFiles/freshwrapper-obj.dir/all] Error 2
make: *** [all] Error 2

**Comment by i-rinat** [comment]
What about 98b0d25f8fc87653040cf8a10140f50a414a2f11?

**Comment by m00ster** [comment]
Yep, all is good now, I removed my local includes and all is good. I use this a lot on Linux and it has worked well for me for over a year now. The only thing I notice that doesn't work is vdpau hardware acceleration with nvidia drivers. But I can live without it. Thanks!
