### ISSUE TITLE
Black screen youtube video in firefox 38.1

### ISSUE THREAD

**Issue by erness** [i-rinat/freshplayerplugin#248]
![captura de pantalla de 2015-08-04 14-17-22](https://cloud.githubusercontent.com/assets/12767103/9070191/b2fecda6-3ab3-11e5-873a-c192c46d9d19.png)
In page http://codefirefox.com/video/marketing-yourself

**Comment by i-rinat** [comment]
Hi.
Are you sure it's not a HTML5 player? Flash version looks different.

**Comment by erness** [comment]
I was confuse, it's html5, but now everything it's ok (i don't know why suddenly works) thanks for the response
