### ISSUE TITLE
Causes SIGSEGV in RSSOwl when enabled.

### ISSUE THREAD

**Issue by Radagast** [i-rinat/freshplayerplugin#25]
After enabling fresh player RSSOwl crashes instantly when attempting to view feeds. Disabling fresh player prevents the problem.

The console shows:

A fatal error has been detected by the Java Runtime Environment:

```
#
#  SIGSEGV (0xb) at pc=0x00007f2938ff5bd6, pid=5751, tid=139817356359424
#
# JRE version: OpenJDK Runtime Environment (7.0_55-b14) (build 1.7.0_55-b14)
# Java VM: OpenJDK 64-Bit Server VM (24.51-b03 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libxul.so+0xb65bd6]  ffi_closure_unix64+0x3590
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/gcb/hs_err_pid5751.log
#
# If you would like to submit a bug report, please include
# instructions on how to reproduce the bug and visit:
#   http://icedtea.classpath.org/bugzilla
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
```

I posted this on classpath bugzilla but as they pointed out, the error is with native code, i.e. RSSOwl. 

I have a full log file - very long - if needed.

**Comment by coder5** [comment]
i have same problem with Eclipse

NOT SANDBOXED
[ERROR:flash/platform/pepper/common/pep_process.cpp(19)] CHECK(g_process_type == PROCESS_TYPE_UNKNOWN) failed
using openjdk version "1.8.0_45"
with freshplayerplugin-git v0.2.4.r92.g96ba6ad-1
