### ISSUE TITLE
No hardware rendering and decode

### ISSUE THREAD

**Issue by xpris** [i-rinat/freshplayerplugin#250]
Hi.

Im use latest version of freshplayerplugin 3.1 but don't can use hardware rendering and decode.

When I watch youtube videos I see only "software video rendering, software video decoding".

I make enable_hwdec to 1 and VA-API to 1.
Also have installed ffmpeg with lib64avcodec56-2.4.9-1.mga5.tainted and you write on main site to use hardware accelerated needed version 54.39.0 - I have newer!

So any know how to use hardware rendering and decoding? Maybe some I make wrong?

**Comment by i-rinat** [comment]
Hi.
PepperFlash won't use hardware decoder if 3d is not available. From "software video rendering" I can say it's not available for some reason.

* What graphics card do you have?
* Are you using opensource drivers or proprietary ones?
* Are there any messages in the output when you start browser from terminal emulator? (Freshwrapper will tag own messages with `[fresh]`, and probably `[warning]` or `[error]`).

**Comment by xpris** [comment]
Hi.

I use AMD Radeon HD 5850 with Catalyst 15.7 proprietary driver.

In konsole i have:

"[x@localhost firefox]$ ./firefox

(process:13248): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
libva info: VA-API version 0.36.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib64/dri/fglrx_drv_video.so
libva info: Found init function __vaDriverInit_0_33
libva info: va_openDriver() returns 0
NOT SANDBOXED
[fresh 13620] not implemented: PPB_OpenGLES2VertexArrayObject;1.0
[fresh 13620] not implemented: PPB_OpenGLES2DrawBuffers(Dev);1.0
[fresh] [warning] ppb_graphics3d_create, some of GLX_ARB_create_context, GLX_ARB_create_context_profile, GLX_EXT_create_context_es2_profile missing
[fresh] [error] execute_script_ptac, NPN_Evaluate failed
[fresh] [error] execute_script_ptac, NPN_Evaluate failed
[x@localhost firefox]$ 
"

**Comment by i-rinat** [comment]
Try to configure with
```
cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_GLES2=0 ..
```
and then usual `make`.

Proprietary drivers seem to have no support of `GLX_EXT_create_context_es2_profile`, so OpenGL|ES 2 context is not created, and therefore accelerated rendering is not used by PepperFlash. However there are part of ANGLE library in the code, which can emulate OpenGL|ES 2 interface by converting shaders to desktop version of GLSL at runtime. Parameter `-DWITH_GLES2=0` activates it, but code needs to be recompiled.

The structure hardware video decoding interfaces in PPAPI depends on PPB_Graphics3D. One need functioning 3d acceleration to use hwdec.

**Comment by i-rinat** [comment]
By the way, VA-API/XvBA from AMD proprietary driver is known to have issues, especially xvba-va-driver compatibility layer [1].
But just getting 3d available for PepperFlash can reduce CPU load dramatically.


[1] It had workarounds for previous driver versions, which with new fixed drivers can cause various bugs.

**Comment by xpris** [comment]
Thanks for the help.

Unfortunately, I use packages from the repository and compile it can be for me, too difficult or time-consuming: /

**Comment by i-rinat** [comment]
Freshplayerplugin uses a lot of libraries, so locating and installing all of them could take a time, but there should be no other obstacles.
