### ISSUE TITLE
Error #2032 for ted.com

### ISSUE THREAD

**Issue by beew** [i-rinat/freshplayerplugin#252]
Hi,

When try to watch a video on ted,com with Firefox 40 and freshplayerplugin (compiled from master may be a few weeks ago) produces error#2032 while with flash11.2 on Firefox and Chrome the video loads fine  e.g http://www.ted.com/playlists/74/our_brains_predictably_irrati
Interestingly if you try the same video again and again then may be once in a while it works, but then try again and it again doesn't load (but with 11.2 and Chrome it always works)

OS is Ubuntu 15.04 64 bit.

**Comment by beew** [comment]
Seems to be ted's end of the problem. It is working now. Sorry for the false alarm.

**Comment by i-rinat** [comment]
Indeed. I've seen that error once, after you opened the issue here. But never since then. It's odd however that it worked in Chrome. Perhaps it's still a bug in freshwrapper.
