### ISSUE TITLE
Right click doesn't work in vm's console in vcenter

### ISSUE THREAD

**Issue by worldowner** [i-rinat/freshplayerplugin#255]
From time to time I use vcenter to see "console" of virtual machine. Right click doesn't work in this view (menu doesn't appear in virtualized Windows). Everything is fine under chrome where wrapper is not used.

**Comment by i-rinat** [comment]
Hi. There were similar issue: #177. What helped then is to change browser User-Agent header, removing any mention of "Linux" from it. Could you check whenever that works in your case?

Another possible fix is to add `enable_windowed_mode = 0` to `~/.config/freshwrapper.conf`

**Comment by i-rinat** [comment]
Hello? Have you tried any of those workarounds?
