### ISSUE TITLE
Conflict with some Java applications

### ISSUE THREAD

**Issue by orschiro** [i-rinat/freshplayerplugin#26]
Hi there,

I cannot launch some Java applications, such as smartgithg or Crashplan, when I have installed freshplayerplugin.

The produced error output:

```
[ERROR:flash/platform/pepper/common/pep_process.cpp(19)] CHECK(g_process_type == PROCESS_TYPE_UNKNOWN) failed
/usr/bin/smartgithg: line 99: 21690 Aborted                 (core dumped) $_JAVA_EXEC $_VM_PROPERTIES -Xmx${SMARTGITHG_MAX_HEAP_SIZE} -Xverify:none -Dsmartgit.vm-xmx=${SMARTGITHG_MAX_HEAP_SIZE} -jar "$SMARTGIT_HOME/lib/bootloader.jar" "$@"
```

Any ideas what could cause the conflict?

Thanks!

**Comment by coder5** [comment]
i have same problem with Eclipse

NOT SANDBOXED
[ERROR:flash/platform/pepper/common/pep_process.cpp(19)] CHECK(g_process_type == PROCESS_TYPE_UNKNOWN) failed
using openjdk version "1.8.0_45"
with freshplayerplugin-git v0.2.4.r92.g96ba6ad-1

**Comment by i-rinat** [comment]
> i have same problem with Eclipse

@coder5, it's not the same, actually. It's more like #187.

From version you're using, I can guess it's a 96ba6ad. Patch with a fix was added later, in cbaa3d62d1657cdad58fd948b6a4e8053ea8fdbe. Try to build code from the tip of the `master` branch.

**Comment by coder5** [comment]
thanks for fast response i'm using aur arch linux auto installer so which command should i edit in PKGBUILD ?
https://aur.archlinux.org/packages/freshplayerplugin-git/

**Comment by i-rinat** [comment]
I'm not familiar with Archlinux's PKGBUILDs. From its name I guess it takes the most recent commit from `master` branch. Installing it again may give you newer version.
It's worth to try to change `pkgver=v0.2.4.r92.g96ba6ad` line to `pkgver=v0.2.4.r107.g0ec8719` in case AUR somehow figures which revision to pick from version string.

**Comment by coder5** [comment]
i did try that remove this package and reisntallit by editing pkgver=v0.2.4.r107.g0ec8719 and restart the laptop but still no luck, i always have same error on Eclipse , maybe i should try to install it from git without AUR, and do some workaround

**Comment by i-rinat** [comment]
Perhaps, there is other code running on wrong thread. If it crashes, could you collect a backtrace?

**Comment by coder5** [comment]
i did installing from scratch and just copy `libfreshwrapper-pepperflash.so` to `/usr/lib/mozilla/plugins/`
and still simply get 
'./eclipse 
NOT SANDBOXED
[ERROR:flash/platform/pepper/common/pep_process.cpp(19)] CHECK(g_process_type == PROCESS_TYPE_UNKNOWN) failed'
why eclipse java go to mozilla plugin to check flash maybe i should disable flash in eclipse ...

**Comment by i-rinat** [comment]
> copy

`~/.mozilla/plugins` is another common place for plugins. Since it's in user directory, one don't need to be root to install plugin.

> why eclipse java go to mozilla plugin

I think it uses browser engine, either Gecko or Webkit. It's browser engine who loads plugins.

**Comment by coder5** [comment]
Ok great i still no success with `~/.mozilla/plugins` 
> I think it uses browser engine, either Gecko or Webkit. It's browser engine who loads plugins.
Then i change external browser to chrome, it's works charm ...
it's ok even the bugs not fixed ... as along i can use eclipse which i never use browser integration

**Comment by i-rinat** [comment]
I've installed Eclipse. It uses WebKitGTK+ via `libswt-webkit-gtk-3836.so`.

**Comment by coder5** [comment]
hmm... i think i should change the config 
`Window->Preferences->General->Web Browser`
and select Use External web browser to firefox ... 
i rather use google chrome for more stability

**Comment by i-rinat** [comment]
Does switching to an external browser helps? It doesn't switch off internal webengine on my Eclipse installation. (I don't have issue you are talking about though.)

**Comment by i-rinat** [comment]
By the way, do you do anything to trigger crashes? Maybe I'll manage to reproduce issue on my machine. Then it will be easier to fix.

**Comment by coder5** [comment]
yes sure it's help,
hmm... maybe it's because Arch Linux different Distro with ubuntu
Perhaps your code is for ubuntu only 
Anyway thanks a lot for developing freshplayerplugin it's help me a lot ..
Adobe Flash latest outdated version on linux is sucks ... always crash
and using this freshplayer works fine even watch Youtube and other Site using Flash 20 more tabs no crash :+1:  :+1:  :+1:

**Comment by fbt** [comment]
The PKGBUILD in question always pulls the latest version (the pkgver function is what actually gets and sets the package version), so no manual modification is required. It will always build the current HEAD from master.

**Comment by coder5** [comment]
ok thanks @fbt  but will it auto update ? if i do `yaourt -Syua` ?

**Comment by fbt** [comment]
No, you need to specifically rebuild the package to update it. I only push new versions of PKGBUILDS when I have to due to chenges in the way the package needs to be built, not arbitrarily because the git master has gotten a few commits.

It will, however, pull in a new version if you specifically do yaourt -S freshplayerplugin-git. Or it should. Haven't used yaourt in quite a while.

**Comment by i-rinat** [comment]
@coder5, could you try again with newest version? In 1c4f11baed7041073da85065b09b1ce10deba764 `ppp_get_interface()` calls were moved away from `NPP_New`. Perhaps they had some effect.

**Comment by coder5** [comment]
ok sory just read and i build from latest git and its success with `eclipse internal browser` :D

**Comment by i-rinat** [comment]
So, it doesn't crash anymore?

**Comment by coder5** [comment]
no it's doesnt crash ... thanks a lot :+1:

**Comment by i-rinat** [comment]
OK, great.
