### ISSUE TITLE
Severe Firefox crash...

### ISSUE THREAD

**Issue by nicolaasjan** [i-rinat/freshplayerplugin#261]
Hi i-rinat,

With the latest version of the freshplayer plugin Firefox crashes even before its window opens.
Affects at least Firefox 40.0.3 and 41.0b5.
[crashreport on crash-stats.mozilla.com](https://crash-stats.mozilla.com/report/index/93eeaf1e-5dfc-4b19-a5f8-33da52150902)
This happens with the version from [ppa:nilarimogard/webupd8](https://launchpad.net/~nilarimogard/+archive/ubuntu/webupd8), but with my self-compiled version as well...

**Comment by daddy33** [comment]
same here.

**Comment by i-rinat** [comment]
Should be fixed by 86f31237c65d695881ac1f0ce0e624160ae3613d.

I never set `flash_command_line` parameter in config file, that's why I didn't notice the bug.

**Comment by nicolaasjan** [comment]
Thank you very much i-rinat!
I have never seen software fixed so fast!

No crash (yet).

**Comment by i-rinat** [comment]
BTW, crash could be worked around by removing `flash_command_line` parameter from configuration file. That parameter have no visible effect anyway.

**Comment by gaining** [comment]
Thanks, that's fixed for me too.

**Comment by mcl21014** [comment]
Thanks for fixing this. I noticed it yesterday, so I went to email the Webupd8 site owner that the PPA he maintains with the development branch of this application suffered from the issue. But I just arrived here, and see not only that it's fixed, but there's a workaround. Yay!

**Comment by michaldaniel** [comment]
Yup since Webupd8 added this to their ppa it sure hit a lot of users, including me. Chrome noticed count jump. I'm just glad it's fixed.

**Comment by yxmline** [comment]
thanks
