### ISSUE TITLE
freshplayerplugin not reading config file

### ISSUE THREAD

**Issue by beew** [i-rinat/freshplayerplugin#263]
Hi, 

freshplayerplugin (master Sept 03)was having difficulties parsing the config file (freshwrapper.conf) The culprit appears to be the line "quirk_plasma5_screensaver = 0". Commented it out then it worked again.

**Comment by i-rinat** [comment]
Indeed. Forgot to add that option. Added in c73cff7643d5ccf77cb0ddc6688b9ef0c7cbd54e.

**Comment by i-rinat** [comment]
Looks like libconfuse is picky about unknown options, and treat them as error.

**Comment by i-rinat** [comment]
libconfuse deliberately treats unknown keys as whole file error, and refuses to continue parsing.

Let's hope new parser (aaa095a81b04eb59e97cd578515c11a4fc2786d2) won't cause so much pain as previous ones. Now it will only notify about unknown parameter (a969976671879791a58431da736c7c6ebf99272f).
