### ISSUE TITLE
Build error on latest version when building with cmake -DWITH_HWDEC=0 -DCMAKE_BUILD_TYPE=RelWithDebInfo

### ISSUE THREAD

**Issue by gaining** [i-rinat/freshplayerplugin#265]
I get some errors when building with make ` -DWITH_HWDEC=0 -DCMAKE_BUILD_TYPE=RelWithDebInfo` but not with cmake `-DCMAKE_BUILD_TYPE=RelWithDebInfo .. ` it builds just fine.
I'm using Linux mint 17.2 and Firefox 40.0.3 and pepperflash 18.0.0.233. I build from the latest source on here. I installed ffmpg from ppa:kirillshkrogalev/ffmpeg-next in case I needed it as a prerequisite for using the -DWITH_HWDEC=0 option,

[ 25%] Building C object src/CMakeFiles/freshwrapper-obj.dir/main_thread.c.o
[ 26%] Building C object src/CMakeFiles/freshwrapper-obj.dir/reverse_constant.c.o
[ 27%] Building C object src/CMakeFiles/freshwrapper-obj.dir/tables.c.o
[ 28%] Building C object src/CMakeFiles/freshwrapper-obj.dir/trace.c.o
/home/gaining/freshplayerplugin/src/trace.c: In function ‘trace_var_as_string’:
/home/gaining/freshplayerplugin/src/trace.c:100:44: error: expected ‘)’ before ‘PRId64’
         res = g_strdup_printf("{ARRAY:%d:%"PRId64"}", ref_count, var.value.as_id);
                                            ^
/home/gaining/freshplayerplugin/src/trace.c:100:44: warning: format ‘%d’ expects a matching ‘int’ argument [-Wformat=]
/home/gaining/freshplayerplugin/src/trace.c:100:44: warning: spurious trailing ‘%’ in format [-Wformat=]
/home/gaining/freshplayerplugin/src/trace.c:105:49: error: expected ‘)’ before ‘PRId64’
         res = g_strdup_printf("{DICTIONARY:%d:%"PRId64":%s}", ref_count, var.value.as_id, s_dict);
                                                 ^
/home/gaining/freshplayerplugin/src/trace.c:105:49: warning: format ‘%d’ expects a matching ‘int’ argument [-Wformat=]
/home/gaining/freshplayerplugin/src/trace.c:105:49: warning: spurious trailing ‘%’ in format [-Wformat=]
make[2]: *** [src/CMakeFiles/freshwrapper-obj.dir/trace.c.o] Error 1
make[1]: *** [src/CMakeFiles/freshwrapper-obj.dir/all] Error 2
make: *** [all] Error 2

**Comment by i-rinat** [comment]
`trace.c` doesn't include `inttypes.h` (where `PRId64` macro is defined) directly, but on my machine it's somehow included nonetheless.

Added explicit inclusion in 8cc1005bdb1651af8b105bd5630d539e35634b00, that should fix it.

**Comment by gaining** [comment]
Yep, it did. Thanks again. I really appreciate the work that you do here. :)
