### ISSUE TITLE
Flash hangs and crashes on ovh.net

### ISSUE THREAD

**Issue by Pazns** [i-rinat/freshplayerplugin#266]
Warning : Firefox could freeze during 10 seconds or more when trying to reproduce this bug.

http://ovh.net displays a speed test flash application.
The ping step works ; when the download step starts, Flash hangs (and Firefox too) and after some seconds crashes without further explanation.

**Comment by i-rinat** [comment]
It hang on my machine too.

Most probably #82 causes it. I thought PepperFlash doesn't use additional message loops. This is the first ever swf which somehow triggers their usage.

**Comment by i-rinat** [comment]
I've fixed #82 by 32e6d3fe9c387e87fdb96d5779e698814f9e46e1, and indeed, that also fixed application on http://ovh.net

**Comment by Pazns** [comment]
I confirm it works like a charm.
Thanks :-)
