### ISSUE TITLE
Firefox hangs, hard drive runs constantly, when trying to use flash

### ISSUE THREAD

**Issue by kalinda99** [i-rinat/freshplayerplugin#268]
I am not sure when this started (probably with the latest version of freshplayer, though it also does it when using the GIT version, which I am currently, or with Firefox 40), but when I go to a page with Flash (any page at all), my hard drive will start running constantly and Firefox will either hang or become really slow. If I'm lucky I will be able to close the tab, if I not I have to login in a new TTY and kill Firefox.

I am running Firefox 40 (the special OpenSuse fork that has KDE integration, but it's otherwise identical, I think) and my Linux distro is Arch Linux. I get the following terminal output when I try to use flash, it repeats continuously:

>Assertion failure: IsSingleThreaded(), at /usr/src/packages/BUILD/firefox-kde-opensuse/src/mozilla-release/security/sandbox/linux/Sandbox.cpp:442
[Parent 14769] WARNING: pipe error (49): Connection reset by peer: file /usr/src/packages/BUILD/firefox-kde-opensuse/src/mozilla-release/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 459

Is this a bug or does it mean something else? It's worth noting that Freshplayer did work fine until around the end of last month.

Thanks!

**Comment by i-rinat** [comment]
Maybe it crashes and Firefox tries to restart it indefinitely?

Could you collect a [backtrace](https://github.com/i-rinat/freshplayerplugin/blob/master/doc/debugging-guide.md#use-gdb-to-get-a-backtrace)?

It could be freshplayerplugin have a massive memory leak, which uses all the memory and forces system into swapping. That would explain active hard drive usage. You can check it by examining `top` output. If system becomes unresponsive, it's better to launch `top` before you open page with Flash content.

**Comment by kalinda99** [comment]
Hello. Okay, so getting backtraces in Arch Linux seems to be a pain because just compiling Freshplayer with drugging enabled isn't enough, gdb still says no debugging symbols found, so I guess I'm going to have to recompile all the library files it depends on (libconfig, libevent, and libgl. Hopefully just libgl) with debugging enabled. I may need to just recompile Firefox. Which other library/package do you think I need to recompile?

I also tried to use coredumpctl and it didn't give me anything, although Freshplayer's crashes are recorded by it, but there's no backtraces. The wiki is only somewhat helpful and I'm a newbie at this kind of thing.

But you're correct, since I did run top and plugin-container does crash and Firefox does try to restart it as long as I'm on a page with flash. I'm not sure if it's a memory leak as plugin-container isn't using that much memory, but it's definitely crashing over and over again and that definitely can make Firefox unusable.

I'll look into it more and try and get that backtrace.

**Comment by i-rinat** [comment]
Despite the fact I'd be happy to blame any other software, often bugs were in my code. And if that's the case this time, no debugging symbols from other binaries are necessary. Yes, gdb will complain about missing debug info, and show no line numbers, but most of the time that's fine.

If you did get backtraces, what were they like? Were freshwrapper function in it?

**Comment by kalinda99** [comment]
I can't seem to get it to give me a backtrace. https://wiki.archlinux.org/index.php/Debug_-_Getting_Traces#Getting_the_trace - I followed these instructions (including compiling freshplayer (the GIT version) from the AUR with debugging enabled and running gdb with /usr/lib/firefox/plugin-container), but it won't give me anything.

I also tried to do it the way the link you gave me suggested and that didn't work either, and gdb complained freshplayer had no debugging symbols. That's why I thought it would be necessary to recompile the libraries with debugging enabled, only I don't know which libraries and so far I've had no luck building the nvidia-libgl package.

**Comment by kalinda99** [comment]
Okay, I found something strange; Firefox (on about:plugins) thinks I have an older version of flash than the Chromium Pepper Flash package provides, maybe that's it. Going to look into it.

**Comment by kalinda99** [comment]
Okay! I hope this is something useful (there's a lot of ?? in there, though) since it's all I've been able to manage so far. I used `coredumpctl` (with systemd) to get this and I was using freshplayer GIT with debugging enabled, even though gdb (as you see) says no debugging symbols were found. I included all the text that appeared when I ran `coredumpctl gdb`

https://gist.github.com/kalinda99/0493c99d7e157c431813

**Comment by i-rinat** [comment]
Backtrace shows crash was in `SandboxEarlyInit` (I never thought there is a sandbox!), which is part of Firefox. So you need to get debugging info for Firefox.

As I can say from https://projects.archlinux.org/svntogit/packages.git/tree/trunk/mozconfig?h=packages/firefox, Archlinux have debuging symbols disabled for Firefox. I think removing line "ac_add_options --disable-debug-symbols" and building from PKGBUILD should be enough.

**Comment by karolgrudzinski** [comment]
I also have this problem. My findings so far:
1. Everything works ok with e10s disabled :( (btw multiprocess firefox is great)
2. Plugins which crash firefox: kpartsplugin, pipelight, flashplayer (freshplayer)
3. Plugins which works: google talk.
I found today bug on [gentoo bugzilla](https://bugs.gentoo.org/show_bug.cgi?id=562388). Seems like it's a problem with firefox's sandbox, not freshplayer.

**Comment by kalinda99** [comment]
Hmm, I am not sure what happened to the other comment posted here, the one I got an email notification about, but the person mentioned that they were getting similar crashes with Pipelight and Flashplayer both and that the problem most likely IS Firefox's sandbox. They'd also linked to this bug report: https://bugs.gentoo.org/show_bug.cgi?id=562388

I can confirm that I am also getting exactly the same kind of crashes with Pipelight as I did with Freshplayer. So I think this must be a Firefox problem. I'll try Flash 11 and see if it crashes as well.

I haven't managed to compile Firefox with debugging enabled successfully; debugging is a pain in Arch Linux. I'll work on it some more, and look into this further, see what the Pipelight people have also found out.

Will get back to this soon, I hope.

**Comment by i-rinat** [comment]
> I haven't managed to compile Firefox with debugging enabled successfully; debugging is a pain in Arch Linux.

I haven't tried to build debug version of Firefox in Arch, but from experience with other packages, can guess it should be done like that:
  * download all files from https://projects.archlinux.org/svntogit/packages.git/tree/trunk?h=packages/firefox;
  * change `mozconfig` file:
    * delete `ac_add_options --disable-debug-symbols` line;
    * add `ac_add_options --disable-jemalloc` line;
    * add `ac_add_options --enable-optimize="-g -O"` line (flags vary, can be `-O0` to disable optimization completely, or `-g3` to increase debug information verbosity);
    * if you want to run code under Valgrind, add `ac_add_options --enable-valgrind` line;
  * invoke `makepkg`;
  * install generated package by `pacman -U /path/to/packagename.tar.gz`.

**Comment by i-rinat** [comment]
I was re-reading bug reports again and noticed `libnvidia-glcore.so.352.41` in backtrace. Could it be that you're using nVidia proprietary video driver? If yes, did you enable threaded optimizations? Or maybe they are enabled in settings panel?

Some time ago to enable threaded optimizations one had to set environment variable `__GL_THREADED_OPTIMIZATIONS` to `1`. Don't know for sure if there are any other modern way to control that.

**Comment by kalinda99** [comment]
Hello!

Okay wow, this all feels very silly now. It's not a bug or a problem with Firefox or your software. You were right, it is Nvidia (which I am using) and it is because of that environment variable. But the problem was that I had it enabled and it was buried in my /etc/profile.d folder in a shell script I put in there ages ago to try and fix a problem I had with my old video card. I had completely forgotten about it, but removing it fixed the problem and everything works now! I should start keeping track of settings changes like that lol

Sorry for all the bother this has caused, but at least it's something to keep in mind if it comes up in the future.

Thanks for your help, though! I wouldn't have looked at this today or known where to look if you'd not pointed me in the right direction.

**Comment by i-rinat** [comment]
> it is Nvidia (which I am using) and it is because of that environment variable

I would say, Firefox sandboxing code was unprepared for that kind of behavior. They were expecting all libraries to play nice, which most of libraries do. But since ELF objects have initializers, which get executed when shared library loaded, before any function was called, everything could happen during loading. nVidia's libGL just happened to launch a thread from an initializer.

**Comment by i-rinat** [comment]
Forwarded to  https://bugzilla.mozilla.org/show_bug.cgi?id=1222500

**Comment by i-rinat** [comment]
Firefox team fixed the issue. Sandbox is disabled if unexpected threads are present, but browser shouldn't crash now.
