### ISSUE TITLE
FreshPlayerPlugin can hang when Sound card is inaccessible

### ISSUE THREAD

**Issue by Zombie-Ryushu** [i-rinat/freshplayerplugin#270]
FreshPlayerPlugin can hang when Sound card is inaccessible by permissions (I saw this happen using another user's browser session via kdesu and gksu.)

**Comment by i-rinat** [comment]
PepperFlash relies on audio card to provide synchronization events. Without working audio playback will freeze.

I've added a "noaudio" backend, which only eats data with appropriate speed, in bad481deca5ba58bff5f4c7b65f0268b0f1b0ac2. That should fix the issue.
