### ISSUE TITLE
video, audio is ok, but toolbar caption not seen

### ISSUE THREAD

**Issue by kuh3h3** [i-rinat/freshplayerplugin#271]
i compiled ok git bad481deca5ba58bff5f4c7b65f0268b0f1b0ac2 version
and copied library successfully with fedora 22 on x86 system.

sudo cp /home/reandr/freshplayerplugin/build/libfreshwrapper-pepperflash.so /usr/lib/mozilla/plugins/

but some build error with ffmpeg header redefinition occurred.
so needed to comment out some line in some code.

    src/pp_resource.h

//struct AVVDPAUContext {
//    VdpDecoder decoder;
//    VdpDecoderRender *render;
//    char reserved[256];
//};

------------------------------
   src/ppb_video_decoder.c

//static inline AVFrame *
//av_frame_alloc(void)
//{
//    return avcodec_alloc_frame();
//}

-----------------------
//static inline void
//av_frame_free(AVFrame **frame)
//{
//    av_free(*frame);
//    *frame = NULL;
//}

------------------------
//static
//void
//avcodec_free_context(AVCodecContext **pavctx)
//{
//    avcodec_close(*pavctx);
//    av_free(*pavctx);
//   *pavctx = NULL;
//}
-------------------------

Generally work well on firefox,palemoon etc.
video, audio is ok, but toolbar caption not seen.
when click on toolbar location(for example stop),  it work.
but toolbar caption not seen.

working video,audio,caption(flash 11.2.202.521)
http://i.imgur.com/iNNBCXi.png

not seen caption,working video,audio(flash 19.0.0.185)
http://i.imgur.com/qfEMA9Q.png

what make this error ?

**Comment by kuh3h3** [comment]
sorry, fixed by add enable_3d = 0 to freshwrapper.conf

**Comment by i-rinat** [comment]
Are you sure Flash is used at all? http://i.imgur.com/iNNBCXi.png looks like HTML5 player.

Youtube changed default player to HTML5 for Firefox 40 and more recent versions. It won't try to use Flash until HTML5 player fails to play anyhow.

**Comment by kuh3h3** [comment]
what you mean?
no html5.
http://i.imgur.com/O5Z2HNY.png

**Comment by i-rinat** [comment]
HTML5 and Flash versions are slightly different. You can discern one from another just by looking on screenshot. Look at the timeline and buttons at the bottom of the player:
![comparison of HTML5 and Flash versions](http://i.imgur.com/NUHANeC.png)

Then look at your original screenshots. One of them is definitely HTML5. Other have no controls visible, so I can't tell. Version on screenshot in your recent comment https://github.com/i-rinat/freshplayerplugin/issues/271#issuecomment-146180291 is definitely Flash one.
