### ISSUE TITLE
Unable to build in Ubuntu 14.04

### ISSUE THREAD

**Issue by yegle** [i-rinat/freshplayerplugin#285]
I think it's due to 14.04 shipped with libav instead of ffmpeg. Since 14.04 is a LTS version this should be fixed.

```
-- Performing Test HAVE_AVPixelFormat
-- Performing Test HAVE_AVPixelFormat - Success
-- Performing Test HAVE_AV_PIX_FMT_VDPAU
-- Performing Test HAVE_AV_PIX_FMT_VDPAU - Failed
-- Performing Test HAVE_AVCodecID
-- Performing Test HAVE_AVCodecID - Success
-- Performing Test HAVE_AVCodecContext_get_buffer2
-- Performing Test HAVE_AVCodecContext_get_buffer2 - Failed
-- Performing Test HAVE_AVVDPAUContext
-- Performing Test HAVE_AVVDPAUContext - Failed
-- Looking for av_frame_alloc
-- Looking for av_frame_alloc - not found
-- Looking for av_frame_free
-- Looking for av_frame_free - not found
-- Looking for avcodec_free_context
-- Looking for avcodec_free_context - not found
```

**Comment by i-rinat** [comment]
Those are configuration tests, their successes or failures are equally expected. I have workarounds in code, which for example, defines structure `AVPixelFormat` if it wasn't defined.

Are there any errors during build?

**Comment by yegle** [comment]
Hmm... I made a mistake. After installing all necessary packages as indicated in the README.md file I can successfully build the plugin now.
