### ISSUE TITLE
libfreshwrapper-flashplayer.so appears in [INVALID] section of pluginreg.dat

### ISSUE THREAD

**Issue by dyaniv** [i-rinat/freshplayerplugin#287]
I have placed the plug-in in all location known to man. 
Also added conf for the chrome flash in case it is not detected. 
I'm using elementary OS which is based on Ubuntu 14.04 LTS with firefox 42.

Can you help?

**Comment by i-rinat** [comment]
I don't know why it ends up in invalid section. Does deleting of `pluginreg.dat` file helps? Firefox will regenerate it.

**Comment by dyaniv** [comment]
I made a mistake that  caused this. Therefore I closed this ticket.
I would like to say this is a great project and thanks!

**Comment by i-rinat** [comment]
> Therefore I closed this ticket.
OK, got it.
