### ISSUE TITLE
USB?

### ISSUE THREAD

**Issue by hetzbh** [i-rinat/freshplayerplugin#289]
Hi,

I installed the plugin from the GIT and it's working on my system (Fedora 22, Firefox from the Fedora repo). 

One strange thing that happens when the plugin starts working, is that the wrapper/plugin seems to scan my USB and in my case it mounts my Samsung Phone each and every time the plugin/wrapper starts working. 

I assume that this happens since Flash tries to find my webcam and microphone, so my question is: is there a way to disable it? it's quite irritating ;)

Thanks

**Comment by i-rinat** [comment]
Does version from https://github.com/i-rinat/freshplayerplugin/tree/dev make any difference?

**Comment by hetzbh** [comment]
Looks like this version solves this issue, thanks ;)

**Comment by i-rinat** [comment]
This is still not a final solution. I can't push this into the `master` branch as is. Perhaps a configuration file option would be fine? Note, with that options enabled, all your capture devices names will be "Unknown".

**Comment by i-rinat** [comment]
Pushed as ee3953d31f1682920b1b0629d831491c601557b4. It's now controlled by configuration file option, whenever video devices are probed.

Add `probe_video_capture_devices = 0` to `~/.config/freshwrapper.conf` to activate (or deactivate, I don't know how to say it. Anyway, that should fix the issue.)

**Comment by hetzbh** [comment]
If I may suggest, how about changing the option to: allow_usb =1 to enable, allow_usb = 0 to disable, and by default the allow_usb should be 0.

**Comment by i-rinat** [comment]
> allow_usb

That would be misleading. Option controls whenever video capture devices are opened, regardless of their connection type. Code itself have nothing USB-specific.

> and by default the allow_usb should be 0.

I understand it would be better for you. But I (and perhaps many others) expect it to get thing working "out of the box".

Imagine a person who have two webcams, one integrated and other connected via USB. He wants to change which webcam is used, opens settings dialog, and sees there two "Unknown" entries. How he is expected to fix it?
