### ISSUE TITLE
audio input via pulse is very slow

### ISSUE THREAD

**Issue by msalle** [i-rinat/freshplayerplugin#290]
When using freshplayer using pulseaudio, audio input is extremely slow (unusable). Disabling pulse and running via alsa works fine. Running the pepperflash plugin directly (via chromium) works fine both using pulse and alsa.
See e.g. https://www.onlinemictest.com/microphone-test-in-adobe-flash to test.

**Comment by i-rinat** [comment]
> audio input is extremely slow

Could you be more specific about "slow"? What does it mean? Sample rate doesn't match?

I used to use https://i-rinat.github.io/flash-test-cases/RecordAudio/index.html to make tests. That test app first records for five seconds from microphone, then plays recorded samples. Does it work well?

**Comment by msalle** [comment]
It misses a lot of input, about half the input I would say (saying 5x test results in only 2-3), a bit like working on a very slow old computer. The flash testpage I linked shows also something like only half time audio getting through, while the other half just seems to be dropped and the visualization is very slow there (which it is not on a 'native' pepperflash plugin) with a screen refresh only once every second or so instead of continuously. This was also what I experienced in a adobeconnect meeting I was in this afternoon, the audio output was fine, but the audio input was stuttered and slow.

**Comment by i-rinat** [comment]
Test app you gave link to, also freezes in Chrome on my machine.

And I realized I didn't try to capture longer than five seconds of sound. I think I need to make another test app to check whenever it's that app was broken or Flash itself acts that way.

**Comment by msalle** [comment]
Ah, that's annoying... Longer samples certainly might be useful for debugging.
I found http://www.adobe.com/devnet/flash/articles/flcs5_features_microphone_event.html
which might have been used by the one writing it.

**Comment by i-rinat** [comment]
Created [MicrophoneOscilloscope](https://i-rinat.github.io/flash-test-cases/MicrophoneOscilloscope/index.html) test. I didn't like the test app from title message because it painted only sample from immediate capture, without storing a number of them for visual history. Does it work on your machine? I didn't notice any freezes on mine.

**Comment by msalle** [comment]
I've created screencaptures (xvidcap) for Firefox using alsa and pulse, plus one for chromium, see 
https://surfdrive.surf.nl/files/public.php?service=files&t=b591b37ccf5c62fb3c1a567d0495c539
(The link will expire at the end of the year).

**Comment by i-rinat** [comment]
As far as I understand, PulseAudio tries to maximize latency, unless requested otherwise. I've changed the way capture streams created in 4ef12af9aa95e866c3609c097c3a054b8692c9b2. Could you test whenever that gives any positive effects?

**Comment by msalle** [comment]
Yes it does! Works perfectly. Many thanks for the quick fix! (and no, I don't like pulse (-; )
For completeness I've uploaded two captures from both your test and the other microphone test to https://surfdrive.surf.nl/files/public.php?service=files&t=b591b37ccf5c62fb3c1a567d0495c539
two files called pulse_master.mpeg and pulse_master2.mpeg.

**Comment by i-rinat** [comment]
OK, that's great.
