### ISSUE TITLE
Can't play this video on Facebook

### ISSUE THREAD

**Issue by DanielFragaBR** [i-rinat/freshplayerplugin#293]
I'm using the latest git with latest Chrome on Firefox 42 and I can't play this video on Facebook. Click on the following link:

https://www.facebook.com/AutoMoto.it/videos/836939869714027/

Anyone experienced the same issue? If you need more info, just ask.

![277 _automoto it_-_2015-11-29_17 35 51](https://cloud.githubusercontent.com/assets/6537729/11459516/c7f5f348-96bf-11e5-9c56-27b322cc6159.jpg)

**Comment by i-rinat** [comment]
Plays fine. However with hardware decoder enabled, occasionally visual glitches occur.

**Comment by i-rinat** [comment]
Facebook changed player. It now uses HTML5 by default, and falls back to Flash on failure.

**Comment by DanielFragaBR** [comment]
You're right. So i'm closing this since it's not related to Flash.
