### ISSUE TITLE
Garbled text after pepperflash 20.0.0.228 update

### ISSUE THREAD

**Issue by tmuncks** [i-rinat/freshplayerplugin#295]
Since updating pepperflash to 20.0.0.228, some flash text come out mangled. Works fine in Chromium, so I'm thinking it must be a freshplayer issue?

I'm running Freshplayer (Git) from November 11th, I believe (let me know if you need me to try out a specific version)

![screenshot from 2015-12-11 08-11-43](https://cloud.githubusercontent.com/assets/9822186/11743021/1c60ce2c-9fe3-11e5-8f93-05c184206751.png)

**Comment by i-rinat** [comment]
Yeah, I've noticed that too (Chrome was updated yesterday). Fixed in 8f5e6beea4d531c7172c7a65cd2e2e3eeae5ff4b.

**Comment by tmuncks** [comment]
Awesome! Fast response as always... I'll try it out!

**Comment by tmuncks** [comment]
Works perfectly after mentioned commit. Thanks a lot!
