### ISSUE TITLE
Bad install path (0.3.4)

### ISSUE THREAD

**Issue by rezso** [i-rinat/freshplayerplugin#297]
Compiled with -DMOZPLUGIN_INSTALL_DIR="lib/firefox/plugins/".

DESTDIR-aware Makefile found.
make
	DESTDIR=/var/uhubuild/work/install
	install
[  0%] Built target git-revision
[  0%] Built target parson-obj
[ 36%] Built target shader_translator
[ 38%] Built target st
[ 40%] Built target stringify_text
[ 40%] Built target txt-resource-srcs
[ 42%] Built target txt-resources
[ 42%] Built target generate-config-parser-fsm
[ 42%] Built target config-parser-obj
[ 43%] Built target link_check
[ 96%] Built target freshwrapper-obj
[ 97%] Built target generate_fsm
[ 97%] Built target uri-parser-obj
[ 98%] Built target freshwrapper-flashplayer
[100%] Built target dep_check
Install the project...
-- Install configuration: ""
-- Installing: /var/uhubuild/work/install/var/uhubuild/work/compile/build/lib/firefox/plugins/libfreshwrapper-flashplayer.so
-- Removed runtime path from "/var/uhubuild/work/install/var/uhubuild/work/compile/build/lib/firefox/plugins/libfreshwrapper-flashplayer.so"

The correct paths in this case:
built lib: /var/uhubuild/work/compile/build/libfreshwrapper-flashplayer.so
install path: /var/uhubuild/work/install/usr/lib/firefox/plugins/libfreshwrapper-flashplayer.so

**Comment by i-rinat** [comment]
db69414ccc11ff04f6031079133cd2e75f1059e8 should fix it.

I was using `PATH` type for `MOZPLUGIN_INSTALL_DIR` which caused cmake to resolve relative paths from a current working directory. Changing type to `STRING` should prevent paths from expanding.

**Comment by rezso** [comment]
Yes, it fixed now:

Install the project...
-- Install configuration: ""
-- Installing: /var/uhubuild/work/install/usr/lib/firefox/plugins/libfreshwrapper-flashplayer.so
-- Removed runtime path from "/var/uhubuild/work/install/usr/lib/firefox/plugins/libfreshwrapper-flashplayer.so"

Thank you.
