### ISSUE TITLE
no video playback on FB livestreams

### ISSUE THREAD

**Issue by ahjolinna** [i-rinat/freshplayerplugin#299]
when I get a notification that someone has started a livestream on Facebook and when went to check stream it wont play it, it's just a black/blank screen. Normal FB videos do work normally, also the "archived"/saved livestreams.

I'm using the git version of freshplayerplugin, with FF43.0.4 on chakraOS

**Comment by i-rinat** [comment]
I don't use Facebook usually. Is there a way to find a live stream?

**Comment by ahjolinna** [comment]
find? no, you have to have a friend or follow someone who starts a livestream...there are few that I follow who does it few times a week...I will check if it was nvidia beta driver problem

**Comment by madovsky** [comment]
should be fixed since FB uses ovbiously RTMP/RTMFP/RTMPE/RTMPTE protocols
please try the last git thanks

**Comment by i-rinat** [comment]
@ahjolinna, does it work now? Or bug's still there?

**Comment by i-rinat** [comment]
If I recall correctly, PepperFlash started to use other parts of API for making UDP connections. Since real-time communication protocols are implemented over raw UDP, that most probably was the reason. Since new API parts were implemented long ago, there is no sense in keeping this issue open.
