### ISSUE TITLE
[question] problems with NVIDIA 361.18 (beta) driver?

### ISSUE THREAD

**Issue by ahjolinna** [i-rinat/freshplayerplugin#300]
I like to know if I'm the only one who has problems with freshplayerplugin not working using the NVIDIA 361.18 beta driver, thanks to the GLVND feature.

I have no idea but could this be related even thought its about game(s): [NVIDIA dev explains why Civ V and KOTOR2 segfault with NVIDIA 361.18 driver](https://devtalk.nvidia.com/default/topic/911079/linux/361-18-breaks-kotor2-linux-version-/post/4785761/#4785761)

I have now reverted back to stable, version...I will wait for next (beta) version

**Comment by i-rinat** [comment]
> could this be related even thought its about game(s)

Doubt the same could apply to freshwrapper, since OpenGL calls are not explicitly issues in freshwrapper code itself. They are only passed from Flash to a platform. And a GL context is explicitly made current before every GL call. (That frequent context binding thing is the main reason why graphics performance on discrete video adapters is far from optimal).

I'll try to reproduce it as soon as I get to the machine with nVidia GPU.

**Comment by ahjolinna** [comment]
okay, I also think the [fb issue](https://github.com/i-rinat/freshplayerplugin/issues/299) was because of the driver...I have to check if it works with the normal/stable driver. Also I had weird issues with mpv, I got segfault (error in libnvidia-glcore.so.361.18) if I tired to open 3rd mpv (at the same time)

**Comment by ahjolinna** [comment]
one place where freshplayer didn't work with the beta driver was on discshop.fi ...[example](http://www.discshop.fi/elokuvat/bluray/katilo_blu_ray/P106872)
it does work just fine on the stable

btw. I'm using the git version of freshplayerplugin

**Comment by i-rinat** [comment]
> example

That page doesn't even try to load Flash player in Iceweasel 43.0.4 (it's a Debian unbranded version of Firefox) on my machine. What browser are you using?

**Comment by ahjolinna** [comment]
firefox-kde(opensuse kde patches) 43.0.4 ...on chakraOS

**Comment by ahjolinna** [comment]
@i-rinat : wierd, about the example...on beta driver it used flash/fresh -player but it never started to play the video, it was just stuck on some loading animation...but now on stable driver it goes to [HTML5 video](http://fin.clip-1.filmtrailer.com/16719_61300_a_4.mp4?log_var=33|3581100172-1|-) ...for some reason

**Comment by i-rinat** [comment]
Sites tend to use third-party video players (video.js framework in this case). Perhaps, they've disabled Flash fallback, and now everybody get HTML5 video.

I've just tried Opera 12.16 on that site. It supports WebM, but doesn't support MP4/H.264. But that site still uses HTML5 video, which doesn't work.

**Comment by madovsky** [comment]
I can't understand how people are so control minded to think that HTML5 video streaming is better than flash player.... anyhow, good luck for them

**Comment by tpruzina** [comment]
new beta drivers changed how GL wrapper worked with libglvnd thingy and modified paths.
It's broken on Gentoo as well, but I would wait for distributions to iron out ways of handling this before doing anything to code itself (freshplayer isn't the only thing broken, many other apps are).

**Comment by i-rinat** [comment]
I've seen news about 361.28 release. Is the issue the same with 361.28?

**Comment by ahjolinna** [comment]
well apprently there is some [pkg issue with GLVND](https://devtalk.nvidia.com/default/topic/915789/linux/-solved-361-28-gtx-580-steam-several-games-don-t-start-up/1), so I haven't used glvnd with the 361.28 ..for now at least. Well at least GLVND is an optional feature.

**Comment by ahjolinna** [comment]
I have been using the latest beta driver 364.xx with glvnd and freshplayerplugin seems to work just fine, at least on my behalf this can be closed
