### ISSUE TITLE
RTMP and RTMPF server connection on mozilla browsers don't connect

### ISSUE THREAD

**Issue by madovsky** [i-rinat/freshplayerplugin#305]
installed on Fedora 23 64 bits seamonkey, firefox, chrome
chrome connect to my flash project server in RTMP and RTMFP
but seamonkey and firefox not with freshplugin.
do you think ti's related to freshplugin?
I disabled firewalld but still not connecting

**Comment by i-rinat** [comment]
> do you think ti's related to freshplugin?

Could be. Are there any text messages if you run Firefox from terminal?

How could I reproduce the same setup to test it?

**Comment by madovsky** [comment]
let me see...

**Comment by i-rinat** [comment]
So, the site was http://www.boophone.com, however any swf which uses UDP networking should trigger the bug. It looks like recent PepperFlash versions were updated to use `PPB_UDPSocket` rather than `PPB_UDPSocket_Private`, but `PPB_UDPSocket` is not implemented in freshplayerplugin:
```
[fresh  7398] not implemented: PPB_UDPSocket;1.2
[fresh  7398] not implemented: PPB_UDPSocket;1.1
[fresh  7398] not implemented: PPB_UDPSocket;1.0
[fresh  7323] not implemented: PPB_HostResolver;1.0
```

**Comment by madovsky** [comment]
ok, is those foundmentally different or only the name changes?

**Comment by i-rinat** [comment]
API was changed a bit. Network addresses are no longer structs, but resources.

**Comment by madovsky** [comment]
Ha ok. do you think there is any solution?

**Comment by i-rinat** [comment]
Yeah, sure, I'll figure it out.

**Comment by madovsky** [comment]
I will see your changes and for sure will help me to understand the code

**Comment by i-rinat** [comment]
Pushed fixes as 3d10d47772a35f6c6267835272a5ce599b8b4abf and  cecfd52016fd0e31c7346bdaa1eb6ecb85c01d0d.

**Comment by madovsky** [comment]
Brilliant Rinat! my tests are a full success, it even works better than flash in chrome....

**Comment by madovsky** [comment]
I consider this issue fixed and will open a new issue if the latency persists. thanks
