### ISSUE TITLE
Epiphany browser does not recognize freshwrapper anymore

### ISSUE THREAD

**Issue by madovsky** [i-rinat/freshplayerplugin#309]
it was working a while on Epiphany but since I updated my system Fedora 23 64bits and git pull freshwrapper now Epiphany does not see any flash plugin

**Comment by i-rinat** [comment]
Tested in VM with F23 upgraded from F22 and [current](https://github.com/i-rinat/freshplayerplugin/tree/1839b0ec9caf0050484017ed0b5fd862f7e5206c) version of freshwrapper. Works fine mostly, but transparency doesn't work properly, plugin content is opaque.

Try to remove file `~/.cache/webkitgtk/plugin` and start Epiphany again. It's possible that Epiphany decided that Flash plugin is not working, and cached that information.

**Comment by madovsky** [comment]
this seems to make the trick.
also I installed another Fedora 23 on an another USB key
and everything is working well, even with Icecat browser.
the only issue I had with epiphany was SElinux that blocked the libfreshwrapper to read from libflashplayer so it needed to save another selinux rule
