### ISSUE TITLE
version 0.3.4 crash with firefox 38.6.1

### ISSUE THREAD

**Issue by netfab** [i-rinat/freshplayerplugin#312]
On gentoo I'm using freshplayerplugin-0.3.4-r1 with firefox-38.6.1.
Some days ago, all GNOME related packages were updated (glib-2.46.2-r2, gtk+, ...), and
firefox started to crash very often when using freshplayerplugin.
If necessary I can try to rebuild some packages with debug symbols. Do you need something ?

[freshwrapper-backtrace-1456740268-7549.txt](https://github.com/i-rinat/freshplayerplugin/files/150662/freshwrapper-backtrace-1456740268-7549.txt)

**Comment by i-rinat** [comment]
Have you tried to compile freshplayerplugin from repository's master branch?

As far as I can see, `mozalloc_abort()` emits SIGSEGV. And from low number of threads it's probably early initialization, where PepperFlash wasn't started yet.

Are there any text messages during crashes if you start browser from terminal emulator?

**Comment by netfab** [comment]
> Have you tried to compile freshplayerplugin from repository's master branch?

Not yet. I will try it.

Attached file is the terminal output of firefox during my last try.
[firefox_output.txt](https://github.com/i-rinat/freshplayerplugin/files/150824/firefox_output.txt)

**Comment by netfab** [comment]
In fact you're right \: even when running firefox in safe-mode, it crash when viewing html5 videos.
I thought it was flash videos but I was wrong. So this has nothing to do with freshplayerplugin.
Sorry for the inconvenience.  Thanks anyway !

**Comment by madovsky** [comment]
btw I use firefox 44 with Fedora 23 64bits and last fresh git without any prob
