### ISSUE TITLE
can  switch gtk2 -> gtk3?

### ISSUE THREAD

**Issue by wtry** [i-rinat/freshplayerplugin#314]
can  switch gtk2 -> gtk3?

**Comment by i-rinat** [comment]
Sure. When configuring with cmake, add `-DWITH_GTK=3` parameter to command line. GTK+ 3 will used then.

Ensure, that software you are using are not trying to load GTK+ 2 (like Firefox in plugin-container does, for example), as GTK+ 2 and 3 are not designed to work together in the same address space.
