### ISSUE TITLE
White line in full screen mode when device_scale set to 1.5

### ISSUE THREAD

**Issue by Aetf** [i-rinat/freshplayerplugin#315]
Hi, thank you for your great work! I think this is the best flash solution for firefox on linux right now.

However, when I was trying to change `device_scale` to enlarge the content, I noticed a white line at the right of the screen when in full screen mode. It's rather annoying when you are watching videos in full screen like this. The white line can be easily seen. As shown in the screenshot. (It's hard to see in the thumbnail because of the white background but rather obvious when you click and open the image in another tab)

![white_line](https://cloud.githubusercontent.com/assets/1519759/13658552/327fb818-e646-11e5-88ed-46db51d8e7e3.png)

Here's my configuration
- MacBook Pro 13'' with a Retina display at resolution 2560x1600
- Archlinux 64bit, with Plasma 5
- Firefox Nightly 48.0a1 (2016-03-09) with `layer.css.devPixelsPerPx` set to 2
- Google Chrome 49.0.2623.87
- freshplayerplugin built at commit 7ba5f2d

This only happens when `device_scale` is 1.5 and if it's set to other value like 1 or 1.6, the white line disappeared. I can't test value at 2 because thing are too large and the full screen button is blocked.  And currently I can only reproduce this on http://www.bilibili.com/.

The white line is exactly one pixel in width and 1599 pixels in height. The right bottom corner pixel is black which is the correct color. It looks like some rounding errors due to the floating points.

![screenshot_20160309_224223](https://cloud.githubusercontent.com/assets/1519759/13658769/38e64792-e648-11e5-9778-aa712f1a78c2.png)

**Comment by i-rinat** [comment]
I've changed code to round floating point numbers instead of truncating them in 40e41ef06910bf18bbe83de8afcaecde2632e5ec. I don't have a display 2560 pixels wide to test it, but in Xephyr the patch seems to do its work.

**Comment by Aetf** [comment]
Yes, the patch works well. Thank you so much :+1:
