### ISSUE TITLE
Playback pause after 7 seconds

### ISSUE THREAD

**Issue by rabin-io** [i-rinat/freshplayerplugin#33]
same thing happens to me on youtube and with store.steampowered.com.
but i can still seek in the video and resume the playback, which will pause again after 7 seconds.

using Fedora 20/x64 with the latest commit - cbe7057

**Comment by i-rinat** [comment]
Direct PulseAudio support was implemented, so the root of the issue — interacting with ALSA compatibility plugin — was eliminated. Thus I believe issue is solved now.
If you still experience unexpected playback pauses, feel free open a new issue, or reopen this one.
