### ISSUE TITLE
Black flashes in Firefox 46 (GTK3)

### ISSUE THREAD

**Issue by i-rinat** [i-rinat/freshplayerplugin#331]
I think, it started with Firefox 46 with GTK3 by default.

Open a page with a Flash movie, reload a page multiple times. There is a black box of size about the same as the plugin instance size appears on the top left corner of the browser. It always a top left corner of a browser window, regardless where window in placed in the screen. Changing `.background_pixel` to `0xf00000` in `x11et_handle_task()` in `/src/x11_event_thread.c` makes flashes red.

Looks like window is displayed before embedding. Disabling windowed mode moves issue away. Disabling XEmbed makes flashes white (regardless mentioned before `.background_pixel` value).

**Comment by i-rinat** [comment]
With update to Firefox 46.0.1 I can't reproduce it anymore. There were another updates too, so maybe it was fixed by some other update.

**Comment by i-rinat** [comment]
Firefox 46.0.1 in Debian is using GTK2 again, so the issue most probably related to GTK3 version, as with using previous package version, Firefox 46.0, bug is back again.

**Comment by klausenbusk** [comment]
Hello @i-rinat, did you look any further on this?

We need GTK3 for touch support, but don't want to upgrade if it break flash.

**Comment by i-rinat** [comment]
> did you look any further on this

No, not yet.

> break flash

It doesn't really break Flash. When you load a page, for a fraction of a second plugin content is painted at top left corner. Usually initial content of a plugin is a black box, so flashes (no pun intended :smile:  ) are black. But after initial loading it works fine. But those visuals are kind of irritating when you start noticing them, I admit.

**Comment by klausenbusk** [comment]
This issue don't seems to be present on Firefox 47, or I at least don't see anything unusual on http://www.adobe.com/software/flash/about/

Can you confirm this? It could be my test setup.

**Comment by klausenbusk** [comment]
Nvm, I still see the issue on other sites.

Is there any disadvantage of disabling window mode?

**Comment by i-rinat** [comment]
>  Is there any disadvantage of disabling window mode?

Mouse wheel events and IME (Input Method Editor) work only in windowed mode.

**Comment by i-rinat** [comment]
Firefox in Debian is using GTK+ 3 for some time already, black flashes during initialization are still there. And I didn't try to fix it or to find the reason.

But what I want to note is that switching to multiprocess mode (in 50.1.0) stops flashes. Instead, plugin content is hidden completely during scrolling. Well, it's a bit better.

**Comment by i-rinat** [comment]
Looks like the issue was fixed upstream. No more black flashes during page load. Also, Firefox is now multiprocess by default, and there are no issues with plugin content rendering.
