### ISSUE TITLE
Crash in Firefox 46.0.1 with libpepflashplayer 21.0.0.242

### ISSUE THREAD

**Issue by booti386** [i-rinat/freshplayerplugin#334]
It just sadly crashes.

**Comment by i-rinat** [comment]
That's sad.

But without details I can't do anything about it. I've just checked 21.0.0.242 on a test page with freshwrapper from master branch in Firefox 46.0.1 and it works fine. It could be a particular swf causes it, or a particular set of other conditions.

**Comment by booti386** [comment]
I only have useless backtraces, and I'm not able to reproduce it on other computers, so I guess probably stupidness somewhere in an obscure library :/

**Comment by i-rinat** [comment]
What am I supposed to do with the report?

**Comment by booti386** [comment]
I don't really know... :/
You can probably archive it, for now... :/

**Comment by booti386** [comment]
Ok, so it happens only when 3D is enabled (enable_3d=1) :/

**Comment by kuboosoft** [comment]
I use Fedora 24 with Firefox 46.0.1, and no detect the plugin; what information you need? I can help.

**Comment by grizzler0031** [comment]
This looks like the same type of error, also with 21.0.0.242 and Firefox 46.0.1.

[2359] WARNING: pipe error (103): Verbinding is weggevallen: file /builds/slave/m-rel-l64-00000000000000000000/build/src/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 459

That's "Connection was lost" in the first line.
This is when visiting the page http://www.dumpert.nl/mediabase/6794585/fcc9ffe8/charge_.html

On some other pages this error is repeated every couple of seconds and the video sort of runs.

System is Debian Testing Xfce 64-bit on an ASUS H81M-E board (Intel Core i5-4430) with 8GB RAM.

**Comment by i-rinat** [comment]
Are there any `.txt` files in `/tmp` directory? There should be backtraces of crashed processes, if you have `gdb` installed on your machine. (Freshplayerplugin tries to collect backtrace of itself, if crashes).

**Comment by grizzler0031** [comment]
Nope, nothing. I didn't have gdb installed, installed it and went through the whole thing again. Same result. I even removed the other plugins to make sure they weren't interfering. Same result again.

**Comment by i-rinat** [comment]
> http://www.dumpert.nl/mediabase/6794585/fcc9ffe8/charge_.html

Looks like site blocks requests from Russia (why?), but through a proxy it works fine. Program crashes often happen in a different way depending on a particular computer. So absence of crashes on my machine doesn't actually prove anything. Just the fact I can't reproduce it on my machine for debugging. (Which is sad, since I can't fix it if I don't know what's failing).

> pluginreg.dat

It's safe to delete that file, Firefox will try all available plugins and create that file again. I think, you'll need to restart Firefox to make it check plugins.

**Comment by grizzler0031** [comment]
No idea why that site would be blocking anyone. Are you sure it's happening at their end?

Anyway, I've reinstalled a number of items on my system and things appear to be working correctly again, at least for now. So I suppose this was just "one of those things". Thanks for you efforts anyway.

**Comment by i-rinat** [comment]
> Are you sure it's happening at their end?

When I try to open the link, I get redirect to http://kudtkoekiewet.nl/?t=http://www.dumpert.nl/mediabase/6794585/fcc9ffe8/charge_.html, which takes couple of minutes to load, and shows me this:

![2016-06-06-231650](https://cloud.githubusercontent.com/assets/923956/15836356/7e079cb6-2c45-11e6-8a50-b97e7d5061f7.png)

**Comment by grizzler0031** [comment]
Weird. That site CloudFlare claims is offline has to do with the stupid cookie laws in the EU, but it's actually working fine from here. CloudFlare misconfiguration? No idea, I'm afraid.

**Comment by i-rinat** [comment]
@kuboosoft, what did you mean by "no detect the plugin"? Sometimes Firefox fails to load a particular plugin (freshplayerplugin, for example) and caches that information in `pluginreg.dat` file in browser profile directory. That way it doesn't waste time for checking when you launch the browser.

`pluginreg.dat` file can be deleted safely. When you start Firefox next time, it will try all available plugins and recreate `pluginreg.dat` file.

**Comment by i-rinat** [comment]
BTW, @booti386, did you try to build freshwrapper from sources? I've seen some repositories build freshplayerplugin with GTK+ 3 enabled, which is a time bomb. It works on some machines, but fails on others, without clean reason.

**Comment by booti386** [comment]
Yes, I build it from sources.
I patched it to use gl function pointers (glXGetProcAdress) instead of relying on globally exported functions, and it worked.
So there are (were) probably wrong redirections in my Mesa build.

**Comment by i-rinat** [comment]
I'm not sure how can I fix it. And whenever I should. I think, code uses only those symbols, that are guaranteed to be available. Others are requested by `glXGetProcAddress()`.
