### ISSUE TITLE
Version 0.3.5-22.1-x86_64 not visible in Firefox

### ISSUE THREAD

**Issue by wolfgjun** [i-rinat/freshplayerplugin#341]
Hello,
after installing 0.3.5-22.1-x86_64 on openSUSE 13.2 (from vendor http://packman.links2linux.de) and Firefox 47, the freshplayerplugin is no longer visible in Tools->Add-ons->Plugins

Any idea or help?

Thanks a lot
    Wolfgang

**Comment by i-rinat** [comment]
> Any idea

Have you tried to remove `pluginreg.dat` file? Firefox caches there information about plugins. Once it decides that plugin is not worthy to try again, it saves that information in `pluginreg.dat` file, and doesn't try to load plugin anymore, unless its timestamp is updated. To make Firefox try to load plugin again, you should delete that file.

[Here](https://support.mozilla.org/en-US/kb/troubleshoot-issues-with-plugins-fix-problems#w_re-initializing-the-plugins-database) is how to find that file.

**Comment by wolfgjun** [comment]
Hello,

I just deleted `pluginreg.dat,` but unfortunately this **did not help**.
In the generated pluginreg.dat, there is always the line:
```
[INVALID] /usr/lib64/browser-plugins/libfreshwrapper-flashplayer.so:$
1467568587000:$
```
I deleted the package and installed it again. Same effect.
 
Thanks
    Wolfgang

**Comment by i-rinat** [comment]
What
```
ldd -r /usr/lib64/browser-plugins/libfreshwrapper-flashplayer.so
```
says?

**Comment by wolfgjun** [comment]
Hello,

> ldd -r /usr/lib64/browser-plugins/libfreshwrapper-flashplayer.so 
        linux-vdso.so.1 (0x00007fff4fd38000)
        libasound.so.2 => /usr/lib64/libasound.so.2 (0x00007ffadb3bd000)
        libgio-2.0.so.0 => /usr/lib64/libgio-2.0.so.0 (0x00007ffadb046000)
        libXrandr.so.2 => /usr/lib64/libXrandr.so.2 (0x00007ffadae3b000)
        libXrender.so.1 => /usr/lib64/libXrender.so.1 (0x00007ffadac31000)
        libX11.so.6 => /usr/lib64/libX11.so.6 (0x00007ffada8f3000)
        libXcursor.so.1 => /usr/lib64/libXcursor.so.1 (0x00007ffada6e7000)
        libGL.so.1 => /usr/lib64/libGL.so.1 (0x00007ffada457000)
        libevent_pthreads-2.0.so.5 => /usr/lib64/libevent_pthreads-2.0.so.5 (0x00007ffada254000)
        libevent-2.0.so.5 => /usr/lib64/libevent-2.0.so.5 (0x00007ffada00a000)
        libpangocairo-1.0.so.0 => /usr/lib64/libpangocairo-1.0.so.0 (0x00007ffad9dfd000)
        libcairo.so.2 => /usr/lib64/libcairo.so.2 (0x00007ffad9adb000)
        libpangoft2-1.0.so.0 => /usr/lib64/libpangoft2-1.0.so.0 (0x00007ffad98c6000)
        libpango-1.0.so.0 => /usr/lib64/libpango-1.0.so.0 (0x00007ffad967b000)
        libgobject-2.0.so.0 => /usr/lib64/libgobject-2.0.so.0 (0x00007ffad942a000)
        libglib-2.0.so.0 => /usr/lib64/libglib-2.0.so.0 (0x00007ffad911b000)
        libfreetype.so.6 => /usr/lib64/libfreetype.so.6 (0x00007ffad8e84000)
        libcrypto.so.1.0.0 => /lib64/libcrypto.so.1.0.0 (0x00007ffad8a60000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007ffad885b000)
        librt.so.1 => /lib64/librt.so.1 (0x00007ffad8653000)
        libm.so.6 => /lib64/libm.so.6 (0x00007ffad8352000)
        libgtk-x11-2.0.so.0 => /usr/lib64/libgtk-x11-2.0.so.0 (0x00007ffad7d15000)
        libgdk-x11-2.0.so.0 => /usr/lib64/libgdk-x11-2.0.so.0 (0x00007ffad7a60000)
        libpulse.so.0 => /usr/lib64/libpulse.so.0 (0x00007ffad7814000)
        libjack.so.0 => /usr/lib64/libjack.so.0 (0x00007ffad75cb000)
        libsoxr.so.0 => /usr/lib64/libsoxr.so.0 (0x00007ffad7368000)
        libavcodec.so.57 => /usr/lib64/libavcodec.so.57 (0x00007ffad6c73000)
        libavutil.so.55 => /usr/lib64/libavutil.so.55 (0x00007ffad6a02000)
        libva-x11.so.1 => /usr/lib64/libva-x11.so.1 (0x00007ffad67fc000)
        libva.so.1 => /usr/lib64/libva.so.1 (0x00007ffad65e5000)
        libvdpau.so.1 => /usr/lib64/libvdpau.so.1 (0x00007ffad63e1000)
        libv4l2.so.0 => /usr/lib64/libv4l2.so.0 (0x00007ffad61d3000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007ffad5fb6000)
        libc.so.6 => /lib64/libc.so.6 (0x00007ffad5c0e000)
        /lib64/ld-linux-x86-64.so.2 (0x00007ffadb93e000)
        libgmodule-2.0.so.0 => /usr/lib64/libgmodule-2.0.so.0 (0x00007ffad5a0a000)
        libz.so.1 => /lib64/libz.so.1 (0x00007ffad57f4000)
        libselinux.so.1 => /lib64/libselinux.so.1 (0x00007ffad55cf000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00007ffad53b8000)
        libXext.so.6 => /usr/lib64/libXext.so.6 (0x00007ffad51a6000)
        libxcb.so.1 => /usr/lib64/libxcb.so.1 (0x00007ffad4f85000)
        libXfixes.so.3 => /usr/lib64/libXfixes.so.3 (0x00007ffad4d7f000)
        libexpat.so.1 => /usr/lib64/libexpat.so.1 (0x00007ffad4b55000)
        libglapi.so.0 => /usr/lib64/libglapi.so.0 (0x00007ffad492a000)
        libXdamage.so.1 => /usr/lib64/libXdamage.so.1 (0x00007ffad4727000)
        libX11-xcb.so.1 => /usr/lib64/libX11-xcb.so.1 (0x00007ffad4525000)
        libxcb-glx.so.0 => /usr/lib64/libxcb-glx.so.0 (0x00007ffad430c000)
        libxcb-dri2.so.0 => /usr/lib64/libxcb-dri2.so.0 (0x00007ffad4107000)
        libxcb-dri3.so.0 => /usr/lib64/libxcb-dri3.so.0 (0x00007ffad3f04000)
        libxcb-present.so.0 => /usr/lib64/libxcb-present.so.0 (0x00007ffad3d00000)
        libxcb-sync.so.1 => /usr/lib64/libxcb-sync.so.1 (0x00007ffad3afa000)
        libxshmfence.so.1 => /usr/lib64/libxshmfence.so.1 (0x00007ffad38f7000)
        libXxf86vm.so.1 => /usr/lib64/libXxf86vm.so.1 (0x00007ffad36f0000)
        libdrm.so.2 => /usr/lib64/libdrm.so.2 (0x00007ffad34e4000)
        libfontconfig.so.1 => /usr/lib64/libfontconfig.so.1 (0x00007ffad32a5000)
        libpixman-1.so.0 => /usr/lib64/libpixman-1.so.0 (0x00007ffad2ffa000)
        libEGL.so.1 => /usr/lib64/libEGL.so.1 (0x00007ffad2dd2000)
        libpng16.so.16 => /usr/lib64/libpng16.so.16 (0x00007ffad2b94000)
        libxcb-shm.so.0 => /usr/lib64/libxcb-shm.so.0 (0x00007ffad2991000)
        libxcb-render.so.0 => /usr/lib64/libxcb-render.so.0 (0x00007ffad2787000)
        libharfbuzz.so.0 => /usr/lib64/libharfbuzz.so.0 (0x00007ffad252d000)
        libffi.so.4 => /usr/lib64/libffi.so.4 (0x00007ffad2325000)
        libpcre.so.1 => /usr/lib64/libpcre.so.1 (0x00007ffad20b9000)
        libatk-1.0.so.0 => /usr/lib64/libatk-1.0.so.0 (0x00007ffad1e92000)
        libgdk_pixbuf-2.0.so.0 => /usr/lib64/libgdk_pixbuf-2.0.so.0 (0x00007ffad1c6f000)
        libXinerama.so.1 => /usr/lib64/libXinerama.so.1 (0x00007ffad1a6b000)
        libXi.so.6 => /usr/lib64/libXi.so.6 (0x00007ffad185b000)
        libXcomposite.so.1 => /usr/lib64/libXcomposite.so.1 (0x00007ffad1658000)
        libpulsecommon-5.0.so => /usr/lib64/pulseaudio/libpulsecommon-5.0.so (0x00007ffad13e2000)
        libjson-c.so.2 => /usr/lib64/libjson-c.so.2 (0x00007ffad11d7000)
        libdbus-1.so.3 => /lib64/libdbus-1.so.3 (0x00007ffad0f90000)
        libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007ffad0c87000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007ffad0a70000)
        libgomp.so.1 => /usr/lib64/libgomp.so.1 (0x00007ffad0861000)
        libswresample.so.2 => /usr/lib64/libswresample.so.2 (0x00007ffad0645000)
        libwebp.so.5 => /usr/lib64/libwebp.so.5 (0x00007ffad03e9000)
        libvpx.so.1 => /usr/lib64/libvpx.so.1 (0x00007ffad0008000)
        libvorbisenc.so.2 => /usr/lib64/libvorbisenc.so.2 (0x00007ffacfd5e000)
        libvorbis.so.0 => /usr/lib64/libvorbis.so.0 (0x00007ffacfb30000)
        libtheoraenc.so.1 => /usr/lib64/libtheoraenc.so.1 (0x00007ffacf8f0000)
        libtheoradec.so.1 => /usr/lib64/libtheoradec.so.1 (0x00007ffacf6d6000)
        libspeex.so.1 => /usr/lib64/libspeex.so.1 (0x00007ffacf4bd000)
        libschroedinger-1.0.so.0 => /usr/lib64/libschroedinger-1.0.so.0 (0x00007ffacf1f3000)
        libopus.so.0 => /usr/lib64/libopus.so.0 (0x00007ffacefa7000)
        libopenjpeg.so.1 => /usr/lib64/libopenjpeg.so.1 (0x00007ffaced7e000)
        libgsm.so.1 => /usr/lib64/libgsm.so.1 (0x00007ffaceb72000)
        libcelt0.so.2 => /usr/lib64/libcelt0.so.2 (0x00007fface95b000)
        libv4lconvert.so.0 => /usr/lib64/libv4lconvert.so.0 (0x00007fface6e2000)
        libXau.so.6 => /usr/lib64/libXau.so.6 (0x00007fface4dd000)
        libxcb-xfixes.so.0 => /usr/lib64/libxcb-xfixes.so.0 (0x00007fface2d6000)
        libgbm.so.1 => /usr/lib64/libgbm.so.1 (0x00007fface0c7000)
        libwayland-client.so.0 => /usr/lib64/libwayland-client.so.0 (0x00007ffacdeb9000)
        libwayland-server.so.0 => /usr/lib64/libwayland-server.so.0 (0x00007ffacdca7000)
        libgraphite2.so.3 => /usr/lib64/libgraphite2.so.3 (0x00007ffacda89000)
        libsystemd.so.0 => /usr/lib64/libsystemd.so.0 (0x00007ffacd860000)
        libsndfile.so.1 => /usr/lib64/libsndfile.so.1 (0x00007ffacd5f4000)
        libogg.so.0 => /usr/lib64/libogg.so.0 (0x00007ffacd3ed000)
        liborc-0.4.so.0 => /usr/lib64/liborc-0.4.so.0 (0x00007ffacd16a000)
        libjpeg.so.8 => /usr/lib64/libjpeg.so.8 (0x00007ffaccf15000)
        liblzma.so.5 => /usr/lib64/liblzma.so.5 (0x00007ffacccee000)
        libgcrypt.so.20 => /usr/lib64/libgcrypt.so.20 (0x00007ffacca0a000)
        libFLAC.so.8 => /usr/lib64/libFLAC.so.8 (0x00007ffacc7cb000)
        libgpg-error.so.0 => /usr/lib64/libgpg-error.so.0 (0x00007ffacc5b9000)

Another idea would be to simply use the previous version of freshplayerplugin, which worked fine.
Any idea, where I could find this rpm?

Thanks
    Wolfgang

**Comment by i-rinat** [comment]
> ldd

ldd output looks fine

> Any idea, where I could find this rpm?

Have no idea. I usually build from source.

**Comment by i-rinat** [comment]
Just tried to install OpenSuse 13.2 in virtual machine, with freshplayerplugin from Packman repo. Works fine.

**Comment by i-rinat** [comment]
It's also worth to try to launch Firefox with a fresh profile. Create, for example, directory `/tmp/1`, and launch Firefox with that directory as new user home dir:

```
$ mkdir /tmp/1
$ HOME=/tmp/1 firefox
```
You should shutdown running copy of Firefox before launching new one, of course. Otherwise, running copy will be reactivated, with current profile.

**Comment by wolfgjun** [comment]
Hello,
seems my Firefox profile was broken.
Starting Firefox with a fresh new profile works fine!!!
Thanks a lot!!

Best regards
    Wolfgang

**Comment by i-rinat** [comment]
Good to hear that.

It's still interesting what caused that. Did you changed settings on `about:config` page related to plugins? I can think of "dom.ipc", that are related.

**Comment by wolfgjun** [comment]
Hello,
I had not made any changes via `about:config`. 
I just compared the values of dom.ipc and there are no differences.
Anyway, the thing I learned is, that I include firefox-profile into my backups !!

Best regards
    Wolfgang
