### ISSUE TITLE
Doing a migration from the native plugin

### ISSUE THREAD

**Issue by Sworddragon** [i-rinat/freshplayerplugin#342]
I'm using the freshplayerplugin 0.3.5 and users that are comming from native NPAPI plugins like the Flash Player 11.2.x for Linux they will notice that their flash cookies like savegames aren't working anymore. Maybe the freshplayerplugin can do a migration for the old NPAPI data for example by copying existing flash cookies into its new path on the first configuration.

The same issue applies also to configuration files like mms.cfg and FlashPlayerTrust/*.cfg (in case the latter is still supported by the PPAPI). It would be nice if the freshplayerplugin would additionally support global ones and eventually also copying the NPAPI ones on the first configuration.

**Comment by i-rinat** [comment]
I don't think there is a specification what files go where. One can try to copy files by hand. But I don't think it's a good idea to make `freshplayerplugin` copy them. Using the same directory as NPAPI plugin is not a good idea either. Flash player doesn't expect other applications messing with its files.

> mms.cfg

I was told that it's in `~/.config/freshwrapper-data/Shockwave Flash/System/mms.cfg`
