### ISSUE TITLE
freshplayerplugin stops working

### ISSUE THREAD

**Issue by promeneur** [i-rinat/freshplayerplugin#347]
opensuse 13.1 x86_64
freshplayerplugin 0.3.5
firefox 49.0.1

this days there was an update to 23.0.0.185
but
in firefox, flashplayer is still 23.0.0.162 (last update 2016/08/27)

**Comment by ahjolinna** [comment]
did u try to open firefox in safemode? ("restart with add-ons disabled") if it works with that "mode" then its a problem/conflict with some of your addons/extensions, mostly because of Electrolysis feature in Firefox

**Comment by promeneur** [comment]
in fact if you play video this is well the 185 version which is used.
perhaps firefox does not refresh manifest.json.

**Comment by i-rinat** [comment]
In short, the easiest way to get a newer version of PepperFlash loaded is to restart Firefox.

Freshplayerplugin loads PepperFlash at startup, and does not load newer versions while running. It's just not possible — PepperFlash has an internal state, and there is no way to save it and reload later. Next, freshplayerplugin, as any NPAPI plugin is kept running while you have any tab with Flash content open. No matter how many tabs with Flash you have, Firefox uses single plugin host process. So closing and reopening a single tab won't help. But if you close all tabs with Flash and wait for about 30 seconds, Firefox will terminate `plugin-container` process. And then, after you open new tab with site with Flash again, Firefox will launch new copy of `plugin-container`, which will load freshplayerplugin, which will load newer PepperFlash.

I said earlier that unload time is about 30 seconds, but it could be a little longer. And there is a setting for that timeout, `dom.ipc.plugins.unloadTimeoutSecs` on `about:config` page.
