### ISSUE TITLE
freshplayerplugin blocked on Firefox 52

### ISSUE THREAD

**Issue by amiad** [i-rinat/freshplayerplugin#349]
Firefox 52.0 [block all plugins except Flash](http://www.ghacks.net/2016/10/06/firefox-52-nightly-plugin-support-except-flash-dropped/) ([bug 1269807](https://bugzilla.mozilla.org/show_bug.cgi?id=1269807))  freshplayerplugin blocked too.

I [opened bug in Mozilla Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1323177) and [Benjamin Smedberg wrote](https://bugzilla.mozilla.org/show_bug.cgi?id=1323177#c5):

> The "name" of this plugin is "Shockwave Flash 23.0 r0". This is very likely to cause web compatibility problems, so I'm going to close this and the freshplayer code should switch to the canonical "Shockwave Flash" name.

Please fix this.

**Comment by i-rinat** [comment]
Hi.

Actually, "name" the plugin reports is "Shockwave Flash" exactly. It's the "description" string, which is "Shockwave Flash 23.0 r0". Initially, name was different to avoid clashes with a native Flash player, but as Benjamin noticed, it caused compatibility issues, so it had to be changed to that exact name and description format.

To be sure, I've just tried Firefox Nightly with a clean profile, and Freshplayerplugin works there just fine.

What is probably the case, is Firefox marked Freshplayerplugin invalid. That happens from time to time. Firefox tries to load a plugin, something fails. To avoid trying to load failed plugin again and to make startup faster, Firefox stores status in `pluginreg.dat` file. Next time it doesn't even try to load a plugin unless its file modification time changed.

Please try to close Firefox, remove `pluginreg.dat` file, and then start Firefox again. The file is in Fx profile directory. You can find where your current profile directory is, by visiting `about:support` page in Firefox. There will be table with the button next to "Profile Directory" text. Press it, and Fx will open the directory. (Although Firefox will recreate the file, it's a good to backup profile anyway.)

**Comment by amiad** [comment]
OK, you right. After I deleted `pluginreg.dat` then Firefox loaded freshplayerplugin with the name "Shockwave Flash".
thanks
