### ISSUE TITLE
 Error CentOS 6 dependence unrecognized

### ISSUE THREAD

**Issue by amidevous** [i-rinat/freshplayerplugin#35]
[root@10807 src]# cmake --version
cmake version 2.8.8
[root@10807 src]# cmake ..
 checking for modules 'alsa;glib-2.0;x11;xinerama;egl;glesv2;liburiparser;libconfig;libevent;libevent_pthreads;cairo;pango;pangocairo;pangoft2;freetype2;gtk+-2.0'
   package 'liburiparser' not found
   package 'libevent' not found
   package 'libevent_pthreads' not found
CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:275 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPkgConfig.cmake:329 (_pkg_check_modules_internal)
  CMakeLists.txt:20 (pkg_check_modules)
 Configuring incomplete, errors occurred!
[root@10807 src]# yum -y install uriparser-devel libevent-devel
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
  base: mirror.nsc.liu.se
  elrepo: mirrors.coreix.net
  extras: centosn4.centos.org
  updates: centosh2.centos.org
Setting up Install Process
Package uriparser-devel-0.7.1-1.el6.x86_64 already installed and latest version
Package libevent-devel-1.4.13-4.el6.x86_64 already installed and latest version
Nothing to do
[root@10807 src]# cmake ..
 checking for modules 'alsa;glib-2.0;x11;xinerama;egl;glesv2;liburiparser;libconfig;libevent;libevent_pthreads;cairo;pango;pangocairo;pangoft2;freetype2;gtk+-2.0'
   package 'liburiparser' not found
   package 'libevent' not found
   package 'libevent_pthreads' not found
CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:275 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPkgConfig.cmake:329 (_pkg_check_modules_internal)
  CMakeLists.txt:20 (pkg_check_modules)
 Configuring incomplete, errors occurred!
[root@10807 src]#

**Comment by andykimpe** [comment]
This problem does not seem resolved

However, it is not suited to you about your code each distribution

under centos there <a href="https://access.redhat.com/documentation/en-US/Red_Hat_Developer_Toolset/1/html-single/Software_Collections_Guide/"> scl</a>

which allows to compile newest package for distribution

amidevous I did this project for you and all the other people who spineless sosu install centos 6

https://github.com/andykimpe/freshplayerpluginscl
