### ISSUE TITLE
new "stable" (v0.4) release?

### ISSUE THREAD

**Issue by ahjolinna** [i-rinat/freshplayerplugin#357]
@i-rinat : you haven't released a new "stable" (v0.4?) release in ~½ year and there has been many changes since then, maybe it would be a good time for one? (if you are uncertain about the stability, release a RC version first)

**Comment by i-rinat** [comment]
Let's call it v0.3.7: https://github.com/i-rinat/freshplayerplugin/releases/tag/v0.3.7

I sort of have a tradition to break things when their version changes from 0.3 to 0.4. So, 0.3.7 for now. 😄

**Comment by ahjolinna** [comment]
Sure that's fine, maybe 0.4-rc wouldn't have been a bad option either
