### ISSUE TITLE
Unable to use Freshplayerplugin with ChromeOS Flash 25/26 version

### ISSUE THREAD

**Issue by spstarr** [i-rinat/freshplayerplugin#361]
[19807] WARNING: pipe error (119): Connection reset by peer: file /builddir/build/BUILD/firefox-55.0.3/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 353
libva info: VA-API version 0.40.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib64/dri/radeonsi_drv_video.so
libva info: Found init function __vaDriverInit_0_40
libva info: va_openDriver() returns 0
NOT SANDBOXED
[fresh 19952] not implemented: PPB_OpenGLES2VertexArrayObject;1.0
[fresh 19952] not implemented: PPB_OpenGLES2DrawBuffers(Dev);1.0
[fresh 19952] not implemented: PPB_BrokerTrusted;0.3
[fresh 19952] not implemented: PPB_BrokerTrusted;0.3

Trying to see go.cnn.com, it fails.

Does this even work anymore?

$ strings libpepflashplayer.so | grep LNX
LNX 25,0,0,171

I tried different versions from each ChromeOS recovery image, same result.

**Comment by RodrigoDLPontes** [comment]
Have you had any success with it? I'm trying to watch HBO GO but keep getting an HDPC error.

**Comment by i-rinat** [comment]
I guess, it was somehow related to playing videos with DRM? If so, it should be fixed in 4a29ab58e28e31e0e8a92dfd65e45775e73dcb21, which is now pushed to the `master` branch.

**Comment by i-rinat** [comment]
v0.3.9 have the fix included.
