### ISSUE TITLE
ioError Error #2032

### ISSUE THREAD

**Issue by mrchojin** [i-rinat/freshplayerplugin#364]
On Firefox 57 using freshplayer 0.3.6 (opensuse leap package) flash applets seem to be unable to contact remote services.
For example, using Oracle Enterprise Manager Cloud Control 13c I get this error:

> Connection Fail
> Connection with database failed. Database instance might be down. Try again once it is up.
> Detail: [IOErrorEvent type="ioError" bubbles=false cancelable=false eventPhase=2 text="Error #2032"]

vSphere webclient fails with 

> Connection Error
> Could not connect to vSphere Web Client. Contact your administrator to fix this issue.

In Chrome  both still work correctly. Is this a freshplayer problem?

**Comment by i-rinat** [comment]
Could you try the same in Firefox 52 ESR?

Recently, there were bugreports related to request processing browser API. They were reported as DRM-related (digital rights management) failures, but when I tested that, I found that it's actually just plain HTTP POST-requests that stopped working, although they did before. Also, in Firefox 52 ESR it still worked fine.

I did not look into that yet. Could be freshplayerplugin fault, could be Firefox regression. Can't say for sure now.

**Comment by mrchojin** [comment]
yes, in Firefox 52 ESR all still works correctly.

**Comment by i-rinat** [comment]
Should be fixed in 4a29ab58e28e31e0e8a92dfd65e45775e73dcb21, which is now pushed to the `master` branch.

**Comment by i-rinat** [comment]
v0.3.9 have the fix included.
