### ISSUE TITLE
using Chromebook flash for desktop Chrome

### ISSUE THREAD

**Issue by beew** [i-rinat/freshplayerplugin#375]
Hi, this is not really an issue related to freshplayerplugin but a question. I am wondering if it is possible to use Chromebook's pepper flash on desktop Chrome for Linux to decode drm streams. I tried copying libpepflashplayer.so extracted from Chromebook to desktop Chrome's pepperflash directory but Chrome just complains that no flash is installed.

Thanks.

**Comment by i-rinat** [comment]
> if it is possible to use Chromebook's pepper flash on desktop Chrome for Linux to decode drm streams

Last time I checked, Chromium source had DRM-related code paths disabled for desktop builds. It should be possible to turn them on during compilation stage, with minor changes, perhaps. But I don't think that they do any changes during compilation of Chrome.

So, no. I don't think it's possible for Chrome. I also saw some people trying to do that here and there. But never heard that it worked for anybody.

> but Chrome just complains that no flash is installed.

Today, there is no bundled PepperFlash coming with Chrome. Instead, Chrome downloads the binary itself and puts it into `~/.config/google-chrome/PepperFlash/29.0.0.113/libpepflashplayer.so`. Part with `29.0.0.113` gets replaced by the current version of PepperFlash.

You may want to open Chrome, go to `chrome://components`, find there "Adobe Flash Player", click "Check for update" to get the newest version. And then to replace newly downloaded `libpepflashplayer.so` with the binary you've got from ChromeOS image. That way you'll be sure that Chrome indeed tries to load the PepperFlash version you have on hand.

**Comment by beew** [comment]
>  You may want to open Chrome, go to chrome://components, find there "Adobe Flash Player", click "Check for update" to get the newest version. And then to replace newly downloaded libpepflashplayer.so with the binary you've got from ChromeOS image. That way you'll be sure that Chrome indeed tries to load the PepperFlash version you have on hand.

That was exactly what I did. It didn't work, Chrome doesn't recognize flash from Chrome book, it just complain there is no flash if the one it downloaded was replaced.

Thanks anyway, I asked just out of curiosity. Actually the only thing I use flash for is doing the adobe drm test. :)
