### ISSUE TITLE
libfreshplayer does not show up in Firefox 69.0.1 64bit

### ISSUE THREAD

**Issue by TrIPpY-** [i-rinat/freshplayerplugin#384]
Hello,

Followed the build and install procedure from README.md
libfreshwrapper-flashplayer.so is in /usr/lib64/mozilla/plugins,
/usr/lib/mozilla/plugins and ~/.mozilla/plugins. It does not
show up under plugins in firefox. Hope there is something
that can be done.

Thank you.

**Comment by i-rinat** [comment]
First, the version of Firefox looks unusual. It's not an extended support release which I believe is 68. But it's also not the current version, which is 74.

Since Flash is almost gone from popular websites, I don't really use it. So I can't say for sure if freshplayerplugin was working in 69.0.1. It works on 74.0 though.

As for the possible reasons, it may be `pluginreg.dat` file contains stale data. If for some reason plugin crashed, Firefox remembers that in `pluginreg.dat`, and doesn't try to load failed plugin again. Sometimes it helps to stop the browser, remove `pluginreg.dat`, and start the browser again. File is located in your profile directory. You may find where it is on `about:support` page, search for "Profile Directory".

Another reason is freshplayerplugin built in previous versions of an OS. If it's not fresh-built, it may help to build from source again. Also freshplayerplugin loads PepperFlash itself, so your system libraries should be relatively recent. PepperFlash from desktop Chrome usually works on almost every distro versions, but if you use PepperFlash from ChromeOS, you may need recent `libc` and `libstdc++`.

**Comment by TrIPpY-** [comment]
Thanks very much for your answer.

Yeah sorry i'm on 73.0.1 now. Freshly installed fedora 31 workstation
but had not updated for the first time.

Removed pluginreg.dat

Started fresh, did the: cmake thing, make and make install.

copied libfreshwrapper-flashplayer.so to several locations
including where the firefox rpm installs firefox

so it's now in:

/usr/lib64/mozilla/firefox/plugins
/usr/lib/mozilla/firefox/plugins
/lib64/mozilla/firefox/plugins
/lib/mozilla/firefox/plugins
/usr/local/lib/mozilla/plugins
/usr/local/lib64/mozilla/plugins
~/.mozilla/plugins

and where about:support says the profile directory is: ~/.mozilla/firefox/2vq1u8b3.default-1517998618273-1526802550388

It still doesn't show up in firefox plugins.

Even if the libpepflashplayer.so can't be found freshplayer should still show up in firefox, right?
________________________________
Van: Rinat Ibragimov <notifications@github.com>
Verzonden: woensdag 11 maart 2020 23:21
Aan: i-rinat/freshplayerplugin <freshplayerplugin@noreply.github.com>
CC: TrIPpY- <tonynederpel@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [i-rinat/freshplayerplugin] libfreshplayer does not show up in Firefox 69.0.1 64bit (#384)


First, the version of Firefox looks unusual. It's not an extended support release which I believe is 68. But it's also not the current version, which is 74.

Since Flash is almost gone from popular websites, I don't really use it. So I can't say for sure if freshplayerplugin was working in 69.0.1. It works on 74.0 though.

As for the possible reasons, it may be pluginreg.dat file contains stale data. If for some reason plugin crashed, Firefox remembers that in pluginreg.dat, and doesn't try to load failed plugin again. Sometimes it helps to stop the browser, remove pluginreg.dat, and start the browser again. File is located in your profile directory. You may find where it is on about:support page, search for "Profile Directory".

Another reason is freshplayerplugin built in previous versions of an OS. If it's not fresh-built, it may help to build from source again. Also freshplayerplugin loads PepperFlash itself, so your system libraries should be relatively recent. PepperFlash from desktop Chrome usually works on almost every distro versions, but if you use PepperFlash from ChromeOS, you may need recent libc and libstdc++.

**Comment by i-rinat** [comment]
> fedora 31

As far as I know, Fedora uses SELinux. So it could be lack of SELinux policy that prevents library from loading. I'm not familiar with SELinux enough to check if that's the case. I usually just disabled it completely, but that was for testing purposes. The right solution would be to add a policy.

> Even if the libpepflashplayer.so can't be found freshplayer should still show up in firefox, right?

Yeah, it should. PepperFlash is loaded dynamically, so it should not prevent freshplayerplugin itself from loading.

**Comment by ROBERT-MCDOWELL** [comment]
@i-rinat 
There is an amazing project that will make any SWF made the last 20 years working for ever on the net.
https://github.com/ruffle-rs/ruffle
contributors are welcome!

**Comment by TrIPpY-** [comment]
Thanks again. With selinux disable it also doesn't show up in firefox.

________________________________
Van: Rinat Ibragimov <notifications@github.com>
Verzonden: vrijdag 13 maart 2020 12:38
Aan: i-rinat/freshplayerplugin <freshplayerplugin@noreply.github.com>
CC: TrIPpY- <tonynederpel@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [i-rinat/freshplayerplugin] libfreshplayer does not show up in Firefox 69.0.1 64bit (#384)


fedora 31

As far as I know, Fedora uses SELinux. So it could be lack of SELinux policy that prevents library from loading. I'm not familiar with SELinux enough to check if that's the case. I usually just disabled it completely, but that was for testing purposes. The right solution would be to add a policy.

Even if the libpepflashplayer.so can't be found freshplayer should still show up in firefox, right?

Yeah, it should. PepperFlash is loaded dynamically, so it should not prevent freshplayerplugin itself from loading.

**Comment by ROBERT-MCDOWELL** [comment]
@TrIPpY- 
check the right permissions of your libs

**Comment by TrIPpY-** [comment]
They are mostly all rwxr-xr-x

________________________________
Van: ROBERT MCDOWELL <notifications@github.com>
Verzonden: vrijdag 13 maart 2020 14:04
Aan: i-rinat/freshplayerplugin <freshplayerplugin@noreply.github.com>
CC: TrIPpY- <tonynederpel@hotmail.com>; Mention <mention@noreply.github.com>
Onderwerp: Re: [i-rinat/freshplayerplugin] libfreshplayer does not show up in Firefox 69.0.1 64bit (#384)


@TrIPpY-<https://github.com/TrIPpY->
check the right permissions of your libs

**Comment by i-rinat** [comment]
OK, I've tried to install Fedora 31 into a virtual machine. And indeed freshplayerplugin doesn't show up in `about:plugins` in Firefox. It's not permissions or SELinux interfering, it's just Fedora 31 have Wayland session enabled by default, and uses custom Firefox build with Wayland support enabled by default. As NPAPI plugins are tightly bound to X server technology, there is no way to support them in Wayland-enabled Firefox builds. So, plugins do not work there.

If you still need plugins, you have to run Firefox as `GDK_BACKEND=x11 firefox`. It will then work through implicitly started Xwayland. Or you may download Firefox build from Mozilla's website. While it supports Wayland too, it still uses X11 backend by default.

**Comment by TrIPpY-** [comment]
Ah. makes sense. Few versions back Fedora introduced wayland. I have this problem since 27 or 28. Thanks for your time.Op 13 mrt. 2020 19:17 schreef Rinat Ibragimov <notifications@github.com>:
OK, I've tried to install Fedora 31 into a virtual machine. And indeed freshplayerplugin doesn't show up in about:plugins in Firefox. It's not permissions or SELinux interfering, it's just Fedora 31 have Wayland session enabled by default, and uses custom Firefox build with Wayland support enabled by default. As NPAPI plugins are tightly bound to X server technology, there is no way to support them in Wayland-enabled Firefox builds. So, plugins do not work there.
If you still need plugins, you have to run Firefox as GDK_BACKEND=x11 firefox. It will then work through implicitly started Xwayland. Or you may download Firefox build from Mozilla's website. While it supports Wayland too, it still uses X11 backend by default.
