### ISSUE TITLE
xinerama_screen setting ignored with Intel HD Graphics

### ISSUE THREAD

**Issue by hackel** [i-rinat/freshplayerplugin#58]
I have set xinerama_screen = 1, however full-screen videos continue to play on my main display, 0.  This happens regardless of which display the window containing the Flash video is on prior to pressing the full screen button.  Ironically, this is the behaviour of the NPAPI Flash plugin, whereas Pepper Flash actually does the right thing when running from Chrome.
(I'm running the 20140829 nightly build from the Webupd8 PPA.)

**Comment by i-rinat** [comment]
There were many changes regarding fullscreen handling. Xinerama was removed from dependencies completely, and mentioned settings have no sense anymore. So I'm closing this issue.
If it still doesn't work well, feel free to open another issue, (or reopen this one).

**Comment by hackel** [comment]
Thank you, I just tested it again and it appears to be fixed, using the same screen as the source window and scaling correctly.  Great work!
