### ISSUE TITLE
Issues with prezi.com

### ISSUE THREAD

**Issue by orschiro** [i-rinat/freshplayerplugin#65]
Hi there,

Can someone reproduce the issue that the Flash editor of [prezi.com](http://prezi.com) does not load completely?

For me the it stops loading the editor like this:

![](http://i.imgur.com/bnTw30O.jpg)

```
firefox-beta-bin 33.0b6-1
freshplayerplugin-git 20140920-1
```

Thanks for testing and your help!

**Comment by kroumantov** [comment]
We confirm the described above issue with prezi.com
Since prezi.com is very popular web site we wonder what is the cause of the problem.
Other web sites might be affected as well and this is one more reason to understand the underling cause of the issue.

**Comment by orschiro** [comment]
I can confirm that the issue still persists with prezi.com and `freshplayerplugin-git 20150122-1`.

**Comment by i-rinat** [comment]
Looks like it wants `PPB_X509Certificate_Private;0.1`.

**Comment by i-rinat** [comment]
I've added implementation for `PPB_X509Certificate_Private`. Can you try again?

**Comment by orschiro** [comment]
@i-rinat,

Fixed. Many thanks!

Robert

**Comment by kroumantov** [comment]
We confirm the fix as well. Thank you!
