### ISSUE TITLE
speedtest.net sharing does not work.

### ISSUE THREAD

**Issue by BtbN** [i-rinat/freshplayerplugin#68]
On speedtest.net, the actual test works fine, but after it's finished, when trying to share the result, it comes up with an ID of 0, which obviously doesn't work.

Tested with current master freshplayerplugin, firefox 32, and ppapi flash from chrome 38.0.2125.77_beta1.

Works fine in same firefox with npapi flash 11.2, and also works fine in chrome where the ppapi flash comes from.

**Comment by i-rinat** [comment]
Fixed in 9359432822c405cf644a661541ca5186a1a99d1f
