### ISSUE TITLE
windowed operation mode / scroll support

### ISSUE THREAD

**Issue by i-rinat** [i-rinat/freshplayerplugin#72]
Currently Firefox doesn't pass wheel events to the _windowless_ plugins, and this is unlikely to change in observable future. There is a way to get wheel events however — use _windowed_ mode. Then since plugin runs its own window, it gets (and should process) all input events.

Consider adding _windowed_ operation mode, selected on plugin instantiation time.

For Flash, `wmode` parameter is used to determine which mode to use.

**Comment by Ri0n** [comment]
Hi! what should I patch in firefox or freshplayer to make scroll working in flash?

**Comment by i-rinat** [comment]
@Ri0n, I don't know what should be patched in Firefox, and should be it patched at all. Some sites, like prezi.com and maps.yandex.ru have workarounds, they handle scroll events in javascript, and then pass commands to a flash movie. Enabling scroll event passing in Firefox can break those sites.

As for the freshwrapper, in file `np_functions.c`, in `NPP_New()` there is a line `npn.setvalue(npp, NPPVpluginWindowBool, (void*)0);` which sets up windowless mode. One need to change it to select mode based on `wmode` parameter. Then add an event loop similar to `ppb_flash_fullscreen.c`, and handle events there.

**Comment by i-rinat** [comment]
Implemented, then disabled, then fixed, and then enabled again in bd52c83c3814c69cf04040bd109770aa96cfeaa2.

**Comment by Ri0n** [comment]
works great. thanks!

**Comment by Ri0n** [comment]
except one thing.
if I switch to another window and then back to window with flash, mouse events stop working.
as a workaround I minimize and restore back the window.

**Comment by i-rinat** [comment]
> if I switch to another window and then back to window with flash, mouse events stop working.

Could you give instructions on how to reproduce it? Step-by-step, please.

I've tried some flash movies working with mouse events, but they work if I switch to and back from another window. So it either I miss something crucial, or just doesn't happen on my machine.

**Comment by Ri0n** [comment]
sure

1) install gentoo (developer profile), kde4 and firefox (everything from ~ arch)
2) use latest git version of your freshplayer (I've added ebuild for it in my overlay)
3) start firefox and start playing thesettlersonline.ru
4) ensure everything works including mouse drag'n'drop and scroll.
5) activate any other window (konsole for example. doesn't matter)
6) click right on game's flash content in firefox
......... window is activated but mouse doesn't work ........
7) activate any other window again
8) click on window title of firefox (not on flash content)
......... mouse events work again in the game ........

**Comment by i-rinat** [comment]
Indeed, focus events interfered with messages sent over XEmbed protocol. Fixed in dffe087cd9efb1b3ceb1cdb00a96a875afda515e.

**Comment by Ri0n** [comment]
yep works fine now =)

**Comment by i-rinat** [comment]
OK, great :)

**Comment by Ri0n** [comment]
ah yes, a little unrelated but scroll size is now really big. 6 lines instead of one (actually I don't remember exactly how many it was).

**Comment by i-rinat** [comment]
I don't really know what values should be passed. There should be some multiplier, currently it's 10.0. Maybe that's too much.

**Comment by i-rinat** [comment]
Under Chrome PepperFlash calls only `GetTicks()` and values returned by that method are `+1.0` or `-1.0` with rare `2.0`. Multiplier in question is only affects `GetDelta()`, which is not called at all. So, there should be no visible difference from Chrome's behavior.

**Comment by Ri0n** [comment]
Ok in Firefox it scrolls two times more than in Chrome. At least in thesettlersonline.ru.
I believe underlaying flash version is the same, so the problem is either in Firefox or in Freshplayer.

**Comment by i-rinat** [comment]
I've created #170 to track scrolling issue there.
