### ISSUE TITLE
Hardware mouse cursor icon support

### ISSUE THREAD

**Issue by thieringgergo** [i-rinat/freshplayerplugin#75]
Well, done this wrapper seems to fawlessy support most of the sites as I seen. One of the remaining issues is the hardware cursor support.

From flash player 10.2 flash player can change the hardware cursor. Unfortunetely this is not translated with the fresh player plugin at the moment.

There is a demo .swf on adobe:
http://www.adobe.com/devnet/flashplayer/articles/native-mouse-cursors.html
The pepper flash plugin is loaded into chrome/chromium can have replaced mouse cursors, but not in firefox for example.

**Comment by i-rinat** [comment]
implemented in 4b2213e8ab5c41448a52a59424c71be6816ae39f
