### ISSUE TITLE
live.nicovideo.jp 's streaming

### ISSUE THREAD

**Issue by Artanejp** [i-rinat/freshplayerplugin#77]
When seeing live.nicovideo.jp (a.k.a. NicoNico namahousou) with freshpluyginwrapper, do not start movie.
Click right button on  movie screen, "No movies loaded.".
Additional information:
Seeing movie site (similar youtube) on same provider, "Noco Nico Douga" ( www.nicovideo.jp ) seems to be okay excepts posting comments.This (Douga's) issue is related by implementation of IME.
Cheers,
 Ohta.

Using belows:
OS: Debian GNU/Linux sid
Architecture: amd64
Browser: Iceweasel Version 32.0.3-1 
Flash player: 15.0.0.189 (amd64)
Freshplugin: 0b82cc515a7fb2119bcc4ee1b23c020e62ffebcc

**Comment by i-rinat** [comment]
Fixed in 2af07c84a2c52bc04ad96eda256c56099534496d

**Comment by i-rinat** [comment]
Fixed by b1fceb6301b564773d99f138487342b3ea697f9f. The live.nicovideo.jp/watch/... pages have explicitly specified base URL. They are different from the page URL itself, and that was the reason movie wasn't loaded from a correct address.

**Comment by Artanejp** [comment]
I confirmed to see live.nicovideo.jp with this version of freshplayre with adobe flkash 13.0.0.206.
Thanx for your work.
