### ISSUE TITLE
Fix handling of other thread message loops

### ISSUE THREAD

**Issue by i-rinat** [i-rinat/freshplayerplugin#82]
Callback passed to API functions should be called on the same thread. Now they are called on the main thread, which is fine — PepperFlash so far used only one thread and did not create any other message loops. Nonetheless, this should be handled correctly.

**Comment by i-rinat** [comment]
Implemented in 32e6d3fe9c387e87fdb96d5779e698814f9e46e1.

**Comment by Pazns** [comment]
I confirm it works like a charm.
Thanks :-)
