### ISSUE TITLE
cnBeta's video flash player white screen

### ISSUE THREAD

**Issue by wzhy90** [i-rinat/freshplayerplugin#85]
It seems only youku's flash player have white screen. This line is my test:http://www.cnbeta.com/articles/342325.htm

Copy the video's url and open Youku is OK

**Comment by i-rinat** [comment]
Please try again with the recent version.

5ce438a9277e40cbe19269e24b74eafb25f67349 changes context type to plain OpenGL, which should workaround the issue.

**Comment by i-rinat** [comment]
I still believe transparent instance rendering issues are related to recent changes in Mesa library. And I can't do anything about it.

So in 1f33dd0b23487bd6871a960729d8d649e23f0281 I've added config file option to disable 3d for transparent instances. Add `enable_3d_transparent = 0` line `~/.config/freshwrapper.conf` to activate it. That will degrade performance, but only for `wmode=transparent` flash movies.

**Comment by i-rinat** [comment]
Patch 28fe9e7cfb61012f7e5419141ded5781a9ef3272 makes use of XRender extension for mixing pixmaps, so there is no more texture readback required. So I think white screen issue should disappear now. Can you try again (with enable_3d=1)?

By the way, `enable_3d_transparent` configuration file option was removed in 68ed187034d9a57717600acb7a023d0e68d5363a as obsolete.

**Comment by wzhy90** [comment]
This fixed

**Comment by i-rinat** [comment]
ok, that's good.
