### ISSUE TITLE
Video playback starts at an accelerated rate

### ISSUE THREAD

**Issue by ShroudedNight** [i-rinat/freshplayerplugin#87]
freshplayerplugin v 0.2.0
pepper flash v 15.0.0.189
firefox 33.0.2

When video playback is engaged, videos initially play back at ~10x rate, and sound is severely mangled.  Video playback appears to self-correct in a probabilistic manner (seldomly, it happens right at the very beginning, sometimes it happens quickly, sometimes it takes quite a while)

I believe this happens with all flash video playback.  I've verified that this is happening consistently playing youtube videos, and the couple dailymotion videos I've tested also exhibit this behaviour.

**Comment by i-rinat** [comment]
Direct PulseAudio support was implemented, so the root of the issue — interacting with ALSA compatibility plugin — was eliminated. Thus I believe issue is solved now.
If you still experience unexpected accelerated playback, feel free open a new issue, or reopen this one.
