### ISSUE TITLE
Full screen views should be opened in the same display of the parent window

### ISSUE THREAD

**Issue by 3v1n0** [i-rinat/freshplayerplugin#89]
I've a multi-monitor setup, and for some reason, when I open a video (for example) from a firefox window in any monitor, I always get the fullscreen view in my "first" monitor.

It would be very nice to make sure that when a flash scene is set as fullscreen, then it's shown in the same display where the parent browser window was.

**Comment by i-rinat** [comment]
OK, another attempt. `Master` branch contains additional changes on fullscreen window handling.
