### ISSUE TITLE
Youtube video in fullscreen mode is not fully resized

### ISSUE THREAD

**Issue by 3v1n0** [i-rinat/freshplayerplugin#90]
This happened to me just once (at least the first time I tried it), but when in multi-monitor, I made a video full-screen and while the plugin window was using the whole display area, the actual player area was matching the secondary screen size.

![freshflashplayer multi-monitor](https://cloud.githubusercontent.com/assets/345675/4953909/c8baa306-6686-11e4-9264-650611f5def5.png)

PS: as you can see there's also another small issue, the fullscreen X window should have the `_NET_WM_STATE_SKIP_TASKBAR` and (maybe) `_NET_WM_STATE_SKIP_PAGER` atoms set on [`_NET_WM_STATE`](http://standards.freedesktop.org/wm-spec/1.3/ar01s05.html#idm140238712324208)

**Comment by i-rinat** [comment]
OK, another attempt. `Master` branch contains additional changes on fullscreen window handling.

**Comment by aubade** [comment]
Works fine now! Sorry for the slow reply--I was out of town over the weekend.

**Comment by ocumo** [comment]
Thanks i-rinat ,  
I have only now seen this, I was on vacation.  In the mean time, I had returned to the original firefox old version as I needed it to work.  Nevertheless, when I have a chance I will try again your new version and post here feedback.    In the meantime, it is great to see that aubade has it working, this hopefully means I will have also good result.  Thanks aubade, too.
Thanks a lot for all these efforts and good software!

**Comment by i-rinat** [comment]
Please try again with version 154a3eaa1d1b8f9f56af7a2404bbbfd1aac466aa.
Now smallest width and height across all monitors are reported as fullscreen width and height correspondingly. Multi-monitor setups with affected Flash movies can still result in a partial screen fill, but this is inevitable, I think.

If you use one of the monitors for full screen videos exclusively, you can specify its resolution as `fullscreen_width` and `fullscreen_height` parameters in `~/.config/freshwrapper.conf`.

**Comment by i-rinat** [comment]
On of the affected Flash movies can be found at [http://store.steampowered.com](http://store.steampowered.com). Navigate to any game with a video trailer and try to go fullscreen.

**Comment by aubade** [comment]
It's still working fine for me! But my screens are both the same size so I'm not sure I'd encounter the problem.
