### ISSUE TITLE
Tearing in full screen mode

### ISSUE THREAD

**Issue by daddy33** [i-rinat/freshplayerplugin#96]
Hello,

awesome plugin, but I still have one issue : I have video tearing in videos in full screen mode (flashing horizontal lines) and I didn't find a way to get rid of it.

Thanks in advance.

**Comment by daddy33** [comment]
Hello,

I just added enable_3d = 1 to my freshwrapper.conf file, and tearing in full screen is gone. Really great, thanks a lot for your awesome work.

**Comment by i-rinat** [comment]
You can try `compton`, various backends and vsync methods.

On my machine `compton --backend glx` works great, till some fullscreen OpenGL application launchs, which freezes graphics completely. Although `compton --backend xrender --vsync opengl` seems to be working fine.

**Comment by i-rinat** [comment]
There's no way to fight tearing inside application. As plugin model assumes all instances do drawing in one thread one after another, waiting for vsync makes no sense. There would be enormous lags.

**Comment by daddy33** [comment]
Hello,

I'm currently running mint 17.1 KDE 64 bits, and I now can say that I 
have absolutely no more tearing of any kind using your plugin. Last time 
I saw such a thing was like two months ago. This issue is completely 
solved for me.
So I now use your plugin all the time. Thanks a lot for your awesome work.

Best regards,
J. Poix
