### ISSUE TITLE
No sound + accelerated video with latest release

### ISSUE THREAD

**Issue by hackel** [i-rinat/freshplayerplugin#97]
I had been running Webupd8's 20141120 build and had no issues.  I installed the 20141124 build, and lost sound with the following error displayed on the console:
[fresh] [warning] audio_player_thread, snd_pcm_avail error -32

I also compiled from the latest source today (543056e8f3df7912361dd31b1030aa605386fc0c) and am getting the same issue.  In my freshwrapper.conf, I had set:
audio_buffer_min_ms = 2000
audio_buffer_max_ms = 15000
enable_stagevideo_auto=0

I commented these out, but it made no difference.  I assume the accelerated video is somehow tied to audio sync.  Oddly, if I keep Pulseaudio Volume Control open, I can see random flashes of audio output (milliseconds only) from plugin-container, though I don't hear any sound pops or anything.  Needless to say, my audio is working fine in other applications.

**Comment by i-rinat** [comment]
Are you still having sound issues with freshwrapper?
If you are using PulseAudio, it's better to install libpulse-dev before compilation to ensure PulseAudio output code will be enabled.

**Comment by hackel** [comment]
Thank you for your diligence, I forgot to close this.  Freshwrapper is now working wonderfully!
