### ISSUE TITLE
Can't play video on v.163.com and v.qq.com

### ISSUE THREAD

**Issue by i-rinat** [i-rinat/freshplayerplugin#99]
`v.qq.com` — video freezes after about 10 seconds (not reproduced yet)
`v.163.com` — can't get a video's url (repoduced).

**Comment by i-rinat** [comment]
Looks like v.qq.com has moved to HTML5 video, so that part is not relevant anymore.

**Comment by i-rinat** [comment]
Issue with v.163.com was caused by missing gb2312-80 encoding. I've added an alias in 59e67d3f744b2310bed01853172bb73ca61a6332, so it should work now.

**Comment by i-rinat** [comment]
@dirtycold, I see tv.sohu.com now tries to open UDP socket. That part of API is not implemented yet, and that missing API probably causing a malfunction.

**Comment by i-rinat** [comment]
That was some kind of translation on tv.sohu.com, I think. Other videos are working fine, I don't have any idea why it fails to load.

**Comment by dirtycold** [comment]
just upgraded to version 0.3.0 but the result was surprising...
* tv.sohu.com now plays perfect even in high resolution quality. no stuck, no freeze, just plays. (yey!) 
* v.163.com still complains "can't find video url" kind of thing...
looks a little weird, right?

**Comment by i-rinat** [comment]
> to version 0.3.0

which doesn't exist yet :-). I think you've meant latest version from git?

> v.163.com still complains "can't find video url" kind of thing

Can you post a link to some video which doesn't work? Perhaps not all videos there use the same parameters and I just tried only working ones.

**Comment by dirtycold** [comment]
sorry... i mean v0.2.3 from opensuse packman repository ;-)
here is an url that can't play: http://v.163.com/yule/V8GIAB8I2/VAH81NVF9.html

**Comment by i-rinat** [comment]
@dirtycold, I still can't reproduce on latest snapshot from `master` branch, that video works fine.

Version `v0.2.3` doesn't work though. Fix was added after 0.2.3 was released. So if package in packman repository was built exactly from `v0.2.3` tag, it won't work.

**Comment by i-rinat** [comment]
As one of the issues was fixed in `master` branch, and other was never reproduced by me, closing.
